### ISSUE TITLE
MATLAB DCS on new Legion (and remote submission)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#1]
MATLAB 2015a is available on new Legion, but the DCS is still being configured. I will update here when it is ready.

**Comment by heatherkellyucl** [comment]
Note that remote submission uses the DCS, so is also affected.

**Comment by heatherkellyucl** [comment]
Update: We have tried using Intel MPI instead of MATLAB's built-in MPI - jobs then start but get a segmentation violation on running.

Next step is to try installing 2015b now that is out and see if any of the fixes make a difference.

**Comment by balston** [comment]
We've finally been able to make some progress with DCS job submission from a Matlab session running on a Legion login node. Simple tests are now working. Note: we have been using Matlab R2015b.

Next step is to run some more complicated tests and then hopefully we will be in the position to install the support files and update the Matlab module.

**Comment by heatherkellyucl** [comment]
Remote submission is working for Matlab 2015b on Legion, and DCS jobs can be submitted but only within a single node. Matlab is not working on Grace at present: there is an issue with install paths. (Grace needs multi-node DCS submission to be fixed first because of the multi-node job requirements).

https://wiki.rc.ucl.ac.uk/wiki/Full_Matlab_on_Legion has been updated with the relevant files.

**Comment by heatherkellyucl** [comment]
We now have the Matlab install on Grace in the same state as the one on Legion. (Multi-node DCS not working).

We are next going to try building Intel MPI 4 as all the other institutions we can find with working Matlab DCS appear to be using Intel MPI 4 and not 5.

**Comment by balston** [comment]
Unfortunately using Intel MPI 4.x has not worked.

**Comment by owainkenwayucl** [comment]
We should report this to Mathworks when we do the 2018A install and the bug is still present.

**Comment by owainkenwayucl** [comment]
As above but 2018B

**Comment by heatherkellyucl** [comment]
Latest news on the DCS issues is at the end of https://github.com/UCL-RITS/rcps-buildscripts/issues/227 - Matlab 2018b was more promising but we are getting `makeFileStorageObject` errors instead.
