### ISSUE TITLE
Ambertools needs an mpi4py

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#100]
IN:02437243
```
File "/shared/ucl/apps/amber/amber-16-mpi/bin/MMPBSA.py.MPI", line 55, in <module>
raise MMPBSA_Error('Could not import mpi4py package! Use serial version '
MMPBSA_mods.exceptions.MMPBSA_Error: Could not import mpi4py package! Use serial version or install mpi4py.
```
```
module load python/2.7.9
module load amber/16/mpi/intel-2015-update2
```
Need to try an mpi4py built for ambertools only, using gcc and `mpi/intel/2017/update1/gnu-4.9.2`

**Comment by owainkenwayucl** [comment]
This will be interesting due to a couple of things:

1) Binaries built with GCC don't have the Intel libs linked in.
2) This means we *probably* can't use the "for Intel" version if Intel MPI that needs to be loaded for Amber to work with stuff compiled with GCC a la Python.

Fun times.

**Comment by owainkenwayucl** [comment]
I've added a **hopefully** suitable build of mpi4py to the Amber 16/mpi module on Legion. 

I don't have a suitable input file to test with though...

**Comment by owainkenwayucl** [comment]
I've tested that `mpi4py` works though.

**Comment by owainkenwayucl** [comment]
OK, I've now done a proper test with that version of mpi4py:

```none
$ mpirun python python_pi 600000000
Calculating PI with:
  600000000 slices
  12 process(s)
Obtained value of PI: 3.1415925991143169859753925265977
Time taken: 20.5909 seconds
```

https://github.com/UCL-RITS/pi_examples/blob/master/python_mpi_dir/python_pi

**Comment by heatherkellyucl** [comment]
MMPBSA.py.MPI reported as working fine now.
