### ISSUE TITLE
GROMACS - investigate hard links to specific MPI libraries and don't always set SSE4.1

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#101]
IN:02453797 and IN:02453994 (SSE4.1)

GROMACS' libgromacs_mdrun_mpi.so links libmpi.so.12 explicitly to the Intel 2015 one it was built with, while the other links pick up whichever is loaded.

```
ldd /shared/ucl/apps/gromacs/5.1.1/intel-2015-update2/lib64/libgromacs_mdrun_mpi.so.1.1.0

 libmpifort.so.12 => /shared/ucl/apps/intel/2017.Update1/impi/2017.1.132/intel64/lib/libmpifort.so.12 (0x00007f0d8cdb3000)
 libmpi.so.12 => /shared/ucl/apps/intel/2015/impi/5.0.3.048/intel64/lib/release_mt/libmpi.so.12 (0x00007f0d8c628000)
```
We should try to stop it doing that. It means that a single node job run using mdrun_mpi will work and a cross-node job will fail with the same modules loaded. 

I have put in the module requirement for 2015 for 
```
gromacs/5.1.1/intel-2015-update2
gromacs/5.1.3/plumed/intel-2015-update2
```

(In 5.1.3 with plumed, libgromacs_mpi.so.1.3.0 has the same thing, but 5.1.1 with plumed does not for some reason).

- [ ] Also make the `-DGMX_SIMD=SSE4.1` flag in the buildscripts only happen on Legion.

**Comment by heatherkellyucl** [comment]
The error you get on Thomas when running with a combination of the wrong MPIs linked is:
```
Warning: string_to_uuid_array: wrong uuid format: ^C
Warning: string_to_uuid_array: correct uuid format is:
xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

**Comment by owainkenwayucl** [comment]
Note: For "reasons", GROMACS have changed their numbering scheme, jumping from 5.1.4 to 2016.

This isn't even sane, because 2016.2 and 2016.3 were both released in 2017.

**Comment by owainkenwayucl** [comment]
Right.  I'll take a look at this.

My plan:

1) Build the most recent GROMACS (currently 2016.3) with fixes for the above issues.
2) Suggest that people move to that, or downgrace Intel modules for the older versions.

**Comment by owainkenwayucl** [comment]
Of course PLUMED doesn't explicitly support 2016.x, trying with settings for 5.1.0.

**Comment by owainkenwayucl** [comment]
Well that didn't work.  Trying without PLUMED.

**Comment by owainkenwayucl** [comment]
It does indeed look like PLUMED is the problem and we need a newer version of PLUMED.  Fair enough.

**Comment by owainkenwayucl** [comment]
Right.  So the newst PLUMED "fails" two of its tests, by tiny differences in the last S.F of output on a few values.

**Comment by owainkenwayucl** [comment]
Dropping optimisation doesn't help, but the differences are tiny.  Proceeding.

**Comment by owainkenwayucl** [comment]
I've put in builds with plumed.  Legion is lagging a bit.

**Comment by owainkenwayucl** [comment]
Of course Legion finished as I wrote that.

I guess the question is whether I need to do a non-plumed build as well?

**Comment by owainkenwayucl** [comment]
OK, I'm doing a non-PLUMED build as that adds a lot more stuff (serial etc.).

**Comment by owainkenwayucl** [comment]
It's built and installed on Legion and Thomas - just waiting on Grace.

**Comment by owainkenwayucl** [comment]
All done.  Closing.
