### ISSUE TITLE
Install Request: Update Python setuptools to latest suitable version (IN02467010)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#104]
Request from m.altaweel@ucl.ac.uk:

> Is it possible to upgrade the setuptools 0.9.8 to a more recent version? It would help with locally 
> installing relevant libraries I need.

https://github.com/pypa/setuptools

**Comment by owainkenwayucl** [comment]
Note: This user is doing something quite odd.  With `python2/recommended` loaded:

```none
setuptools (36.0.1)                          - Easily download, build, install, upgrade, and uninstall Python packages
  INSTALLED: 28.8.0
  LATEST:    36.0.1
```

**Comment by owainkenwayucl** [comment]
This is true for both the `python2` and `python3` bundles.  Regardless, I've upgraded those from 28.8.0 to 36.0.1 on Legion and will repeat on other platforms.

**Comment by owainkenwayucl** [comment]
Done.

**Comment by owainkenwayucl** [comment]
(just a note, it looks like the user is picking up the RHEL install of setuptools in `/usr/`)

```none
Legion [login06] ~ ☻ ➤ cd /usr
Legion [login06] usr ☻ ➤ find . -name setuptools*
./lib/python2.7/site-packages/setuptools
./lib/python2.7/site-packages/setuptools-0.9.8-py2.7.egg-info
./share/doc/python-setuptools-0.9.8/docs/build/html/_sources/setuptools.txt
./share/doc/python-setuptools-0.9.8/docs/setuptools.txt
```
