### ISSUE TITLE
Install Request: Update FSL to version 5.0.10 (IN02471287)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#105]
Request from nikhil.sharma@ucl.ac.uk to update FSL:

> Good morning,
> 
> Is it possible to update the FSL version on legion to 5.0.10 (or patch 5.0.9) so I can use ‘eddy’.
> 
> https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy
> 
> Thanks
> 
> Nik

**Comment by owainkenwayucl** [comment]
Note issue #54

**Comment by owainkenwayucl** [comment]
Version 5.0.10 is deployed on Legion and deploying on the other services as I type this.

**Comment by owainkenwayucl** [comment]
Now deployed on all services.

**Comment by owainkenwayucl** [comment]
So apparently the script didn't apply the parallel patches which would have failed anyway,

Re-opening.

**Comment by owainkenwayucl** [comment]
This is now resolved.
