### ISSUE TITLE
Update Intel Compilers + MPI to latest versions

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#106]
There are a number of bug fixes to the compilers and MPI in subsequent updates to 2017 versions which we'd like to have.

- [ ] - Install
- [ ] - Test related issues (MPI start up with long paths, `mpif**` wrappers erroneously choosing `gfortran` etc.).

- [ ] - Consider viability of making default.

**Comment by ikirker** [comment]
I've installed 2017.update3. I tried making a `.version` file and coercing the module system into believing that 2017.update1 was the default, but it didn't do anything, so I'm not putting a module in for now.

**Comment by owainkenwayucl** [comment]
We have one request for 2017.4 due to MKL bugs.

I'm sorry :(

**Comment by ikirker** [comment]
I don't know how to retrieve this: it's not in the SWDB and the instructions for download Intel software on our internal wiki are no longer accurate. 😕

**Comment by heatherkellyucl** [comment]
This may not be relevant if we're replacing with update4, but `/shared/ucl/apps/intel/2017.Update3/mkl/lib/intel64` has a bunch of stuff missing, including blacs and scalapack.

**Comment by ikirker** [comment]
Hm, I told it to install *everything* (`COMPONENTS=ALL`) but maybe those weren't in the tarball I'd created from the autodownloader.

**Comment by ikirker** [comment]
I'm re-creating the download tarball.

**Comment by ikirker** [comment]
I've re-installed Update3 with Scalapack and BLACS libs using the new tarball.

Haven't done update 4 yet, still don't have the bundle.

**Comment by ikirker** [comment]
Grabbed the link to the bundle from the Spack installer for it, have modified update 3's script, installing on Legion now.

**Comment by ikirker** [comment]
Installed PSXE 2017 update 4 (IMPI update 3) on Legion and generated interfaces for MKL.

**Comment by ikirker** [comment]
Ditto Thomas.

**Comment by ikirker** [comment]
Forgot to do this for Grace when it came back up, which caused a user issue, but this is now installed on Grace.

We're going to discuss how to sensibly handle differences in available software (whether intentional or otherwise) between clusters.

**Comment by ikirker** [comment]
Since the default-modules module loads specific Intel compiler and MPI modules, we added a module for this anyway. This means that people trying to load `compilers/intel` or `compilers/intel/2017` will get the new version.
