### ISSUE TITLE
Install request: YAMBO

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#109]
IN:02489911

http://www.yambo-code.org/

GPLed.

**Comment by owainkenwayucl** [comment]
This has a bunch of optional dependencies so I've asked the user if they need any of them.

**Comment by ikirker** [comment]
A lot of the dependencies for this can be grabbed automatically during the build.

I'm having trouble persuading it to use Scalapack at the moment (the command-line argument doesn't seem to do anything), and it doesn't print any output to indicate whether it's trying to use BLACS or not, but this appears to at least build a working version:

```
./configure \
  --with-fft-libs=-mkl \
  --with-blas-libs=-mkl \
  --with-lapack-libs=-mkl \
  --enable-etsf-io \
  --with-netcdf-libs=/shared/ucl/apps/NetCDF/4.3.3.1-intel-2015-update2 \
  --with-etsf-io-libs=/shared/ucl/apps/libetsfio/1.0.4/intel-2015-update2
```

with loaded modules:
```
gcc-libs/4.9.2
compilers/intel/2017/update1
mpi/intel/2017/update1/intel
hdf/5-1.8.15/intel-2015-update2
netcdf/4.3.3.1/intel-2015-update2
netcdf-fortran/4.4.1/intel-2015-update2
libetsfio/1.0.4/intel-2015-update2
```

**Comment by owainkenwayucl** [comment]
The user would find NetCDF useful as per their response but we can probably skip ETSF-IO if it's troublesome.

**Comment by ikirker** [comment]
Minor note: apparently you cannot use the automatic NetCDF download with HDF5 support enabled.

**Comment by ikirker** [comment]
Installed on Legion, with statically-linked ETSF-IO and NetCDF.

**Comment by ikirker** [comment]
Installed on Thomas.

**Comment by ikirker** [comment]
Checked back with originator of IN.

**Comment by ikirker** [comment]
No response from IN, closing.
