### ISSUE TITLE
Install request: Julia 0.6.0 

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#119]
IN02601457

Request for Grace.

**Comment by owainkenwayucl** [comment]
OK, since I did the previous Julia installs I'll do this one.

**Comment by owainkenwayucl** [comment]
Well this should have been simple but something changed in the options you have to pass through the Julia installer to its build of OpenBLAS and then I had to start again because it needs a much newer version of cmake.

So simple but time consuming.

**Comment by owainkenwayucl** [comment]
Oh cool:

```
Copying in usr/share/doc/julia/examples
Warning: git information unavailable; versioning information limited
    JULIA usr/lib/julia/inference.ji
ERROR: could not load library "/dev/shm/julia/tmp.7Omti6BCqm/julia-0.6.0/usr/bin/../lib/julia/sys.so"
/dev/shm/julia/tmp.7Omti6BCqm/julia-0.6.0/usr/bin/../lib/julia/sys.so: cannot open shared object file: No such file or directory
make[1]: *** [/dev/shm/julia/tmp.7Omti6BCqm/julia-0.6.0/usr/lib/julia/inference.ji] Error 1
make: *** [julia-inference] Error 2
```

**Comment by owainkenwayucl** [comment]
OK, it passed this stage on Legion which means it's something to do with how I set the arch to Nehalem on Legion, but not on Thomas or Grace.

**Comment by owainkenwayucl** [comment]
Right.  It's installed on all three services, optimised for nehalem because doing literally anything else breaks the build in any number of ways.

Will investigate this tomorrow.

**Comment by owainkenwayucl** [comment]
This is completed and I've confirmed it's working.
