### ISSUE TITLE
Install request: libXdmcp

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#12]
Add libXdmcp to the xorg-utils/X11R7.7 module - required by Amber12 which some people have personal installs of. IN00775845

ftp://ftp.x.org/pub/X11R7.7/src/lib/libXdmcp-1.1.1.tar.bz2

**Comment by owainkenwayucl** [comment]
Why on earth does Amber need Xdmcp? 

https://en.wikipedia.org/wiki/X_display_manager_%28program_type%29#X_Display_Manager_Control_Protocol

**Comment by owainkenwayucl** [comment]
OK, I've added this into that module.

**Comment by heatherkellyucl** [comment]
Informed user.
