### ISSUE TITLE
The BSC parallel profiling toolset

### ISSUE THREAD

**Issue by ilectra** [UCL-RITS/rcps-buildscripts#120]
Can we get these in legion and grace (Extrae - Paraver - Dimemas)? https://tools.bsc.es/

Cheers!

**Comment by ikirker** [comment]
It looks like only Extrae needs building from source: Paraver and Dimemas have working binary distributions for Linux. (And not using them looks like it would mean installing wxWidgets, which would probably be quite messy.)

Extrae has an optional dependency on libunwind. 

Libunwind fails 2/34 tests when built with GCC 4.9.2: 

```
FAIL: run-coredump-unwind
FAIL: run-coredump-unwind-mdi
```

Still investigating.

**Comment by ikirker** [comment]
Installed PAPI 5.5.1 with components `appio, coretemp, infiniband, net, lustre`, as another dependency of Extrae.

**Comment by ikirker** [comment]
Extrae also has an optional dependency of DynInst and with that, libdwarf and libelf.

Also on binutils, which must include either libbfd or libiberty. (Preferably both, I think?)

**Comment by ikirker** [comment]
binutils 2.29.1 fails over a hundred tests if built with the Intel 2017.4 compiler, just for the record.

**Comment by ikirker** [comment]
DynInst will compile libelf and libdwarf if you don't provide paths, BUT libelf at least is not then kept in a usable form, I think: there's no `libelf.a` or `libelf.so` in the final install. `libdwarf.so` is there, but maybe it'd be better to compile it separately anyway.

**Comment by ikirker** [comment]
Installed elfutils, libdwarf, and DynInst.

**Comment by ikirker** [comment]
Notes: 

 - needs all those binary tool libraries available dynamically at run time
 - this is an unfortunate mix of GCC and ICC compilations, rebuilding boost with the new Intel compilers should make the module deps work out though
 - `EXTRAE_HOME` should be set to the installation prefix
 - needs an XML config file, [described in manual](https://tools.bsc.es/sites/default/files/documentation/extrae-3.5.1-user-guide.pdf), example below

```xml
<?xml version='1.0'?>
<trace enabled="yes"
    home="@sed_MYPREFIXDIR@"
    initial-mode="detail"
    type="paraver"
    >
    <pthread
        enabled="yes"
        >
        <locks
            enabled="no"
            />
        <counters
            enabled="yes"
            />
    </pthread>
    <callers
        enabled="yes"
        >
        <mpi
            enabled="yes"
            >
            1-3
        </mpi>
        <sampling
            enabled="no"
            >
            1-5
        </sampling>
        <dynamic-memory
            enabled="no"
            >
            1-5
        </dynamic-memory>
    </callers>
    <counters
        enabled="yes"
        >
        <cpu
            enabled="yes" starting-set-distribution="1"
            >
            <set
                enabled="yes" domain="all" changeat-time="5s"
                >
                PAPI_TOT_INS,PAPI_TOT_CYC,PAPI_L1_DCM
                <sampling
                    enabled="yes" period="100000000"
                    >
                    PAPI_TOT_CYC
                </sampling>
            </set>
            <set
                enabled="yes" domain="user" changeat-globalops="5"
                >
                PAPI_TOT_INS,PAPI_TOT_CYC,PAPI_FP_INS
            </set>
        </cpu>
        <network
            enabled="yes"
            />
        <resource-usage
            enabled="yes"
            />
    </counters>
</trace>
```

**Comment by ikirker** [comment]
Current config line:

```bash
./configure --prefix=$install_prefix --with-mpi=$MPI_HOME --without-unwind --with-boost=/shared/ucl/apps/boost/1_63_0/gnu-4.9.2/ --with-dwarf=/shared/ucl/apps/libdwarf/20170709/gnu-4.9.2/ --with-elf=/shared/ucl/apps/elfutils/0.170/gnu-4.9.2/ --with-dyninst=/shared/ucl/apps/dyninst/9.3.2/gnu-4.9.2/ --with-papi=/shared/ucl/apps/papi/5.5.1/gnu-4.9.2/ --with-binutils=/shared/ucl/apps/binutils/2.29.1/gnu-4.9.2/
```

Could also add GPU stuff with:

```bash
--with-cuda=/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/ --with-opencl=/shared/ucl/apps/cuda/8.0.61/gnu-4.9.2/
```

but I couldn't test that, and it might be better to make a pure-GCC build for GPU stuff since that's what the entire toolchain is based on and it's flaky enough as-is.

**Comment by ikirker** [comment]
Extrae builds successfully, but without libunwind, and without several other optional dependencies: clustering, spectral, memkind, mrnet, and synapse.

I'm still trying to slog through those, but in the meanwhile, I've installed the self-contained binary distributions of Paraver and Dimemas.

**Comment by ilectra** [comment]
Thanks a lot, Ian! Does this mean we can `module load extrae` already?

**Comment by ikirker** [comment]
@ilectra There's no central installation yet, but hopefully I should be able to get it done on Monday. Their website is down at the moment, which isn't helping (and is slightly worrying given the situation in Catalonia). I should have all the files I need but we usually make the installers download straight from the source...

I've installed the binary distribution of ClusteringSuite, one of the other optionals, and I think I have a working installer for Spectral's binary distribution as well, and then :crossed_fingers: I should be able to make the install of Extrae able to use those as well.

I can't currently build `libunwind` in a way that passes all the tests, and I'm not sure what effect the test failures indicate, so I'm still leaving it out for now. Sorry if this means you're missing some level of stack data. (This is really weird: spack builds it successfully, but using the same compilers I can't: I think the only difference is using `rpath` but when I try to do that without spack part of the compilation fails.)

I'm leaving Memkind and Synapse out for now as well (issues with dependencies that I'm having trouble remembering right now).

**Comment by ikirker** [comment]
Central build of Extrae now done, for Legion, Grace, and Thomas. It has quite a few dependencies.

```
Loading dependency: gcc-libs/4.9.2
Loading dependency: compilers/intel/2017/update1
Loading dependency: mpi/intel/2017/update1/intel
Loading dependency: elfutils/0.170/gnu-4.9.2
Loading dependency: binutils/2.29.1/gnu-4.9.2
Loading dependency: libdwarf/20170709/gnu-4.9.2
Loading dependency: python/2.7.12
Loading dependency: boost/1_63_0/mpi/intel-2017-update1
Loading dependency: dyninst/9.3.2/gnu-4.9.2
Loading dependency: papi/5.5.1/gnu-4.9.2
Loading dependency: fftw/3.3.6-pl2/gnu-4.9.2
Loading dependency: spectral/3.4.0/bindist
Loading dependency: clusteringsuite/2.6.6/bindist
Loading dependency: libxml2/2.9.4
Loading: extrae
```
