### ISSUE TITLE
Install request: OpenFOAM-plus v1706

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#121]
IN:02411166

ESI-OpenCFD release of OpenFOAM, license is GPLv3. (Contains sponsored developments that the Foundation branch doesn't).

http://www.openfoam.com/releases/openfoam-v1706/
http://www.openfoam.com/download/install-source.php
http://www.openfoam.com/code/build-guide.php

If we can't install this version for some reason, then the OpenFOAM Foundation version v5.0 should be ok.

**Comment by owainkenwayucl** [comment]
Right.

Ignoring ParaView, and using GCC/OpenMPI rather than Intel I've managed a successful build on Grace.

Need to sort those things out tomorrow.

**Comment by owainkenwayucl** [comment]
I've had to give up doing either an Intel or a build with paraview as both fail pretty badly.

I've done a build with GCC+OpenMPI and put the modules on all three services.
