### ISSUE TITLE
Update Python recommended bundles.

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#123]
The packages in the Python recommended bundles are getting a little old.

We need to refresh the packages installed from pip, and upgrade to Python 3.6 (install a new version?).

We did this successfully with Python 3.4 -> Python 3.5 so aim to replicate this process.

**Comment by heatherkellyucl** [comment]
Put more / in the name this time so we can refer to python python/3 python/3/6 (or python/3/3.6 if you prefer).

**Comment by owainkenwayucl** [comment]
The new Python 3 environment is available to test as `python3/3.6`.  This will become `python3/recommended` on the 9th of November.  You will still be able to access the 3.5.x stack as `python3/3.5`.

**Comment by owainkenwayucl** [comment]
The `python2/recommended` module has its packages refreshed but you really should be moving to python 3.  I note that a number of packages in pip are no longer getting new versions for python 2.

**Comment by owainkenwayucl** [comment]
This is competed safely.  Closing
