### ISSUE TITLE
Install request: CASINO

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#125]
IN:02642205

https://vallico.net/casinoqmc/request-a-copy/

Need to get Robert Silk to sign http://www.tcm.phy.cam.ac.uk/~mdt26/academic_consent_form_comp_centre.pdf

Some 'interesting' license terms:
> 3.  I will not incorporate any part of CASINO into any other program system without prior written
permission of the authors.
> 7. ... I will report any difficulties encountered in using CASINO to the authors.

so need to contact the authors.

**Comment by heatherkellyucl** [comment]
I'd said
> Can we explicitly say that term 3 should be modified to this?
>
>3. I will not incorporate any part of the CASINO source code into any other program's source code without prior written permission of the authors.

Reply:
> Sure, if you like. I'll modify that on our web page this afternoon to make sure it's clear.

That was in October so I am reluctantly asking about it again.

**Comment by heatherkellyucl** [comment]
The individual download form was updated, but not the central computing centre PDF that has to be signed.

**Comment by heatherkellyucl** [comment]
Have asked Robert Silk to sign the computing centre agreement. IN:02795710

**Comment by heatherkellyucl** [comment]
We have code.

> You can proceed with the Installation of the software from:
>
> GroupFolder(S)<ISD_Software<Casino

I've looked at what S drives I can see and don't seem to have access to that one, so need @balston to get it.

**Comment by balston** [comment]
I've copied the source code from the ISD Software share to:
```
~ccaabaa/Software/CASINO/CASINO_standard_current_beta.tar.gz
```
on Thomas.

**Comment by heatherkellyucl** [comment]
Hmm, I've been doing test builds with this and getting our own arch file created, but we should maybe wait for a 2.14 release version to do a central install, as there has been regular development going on this year.

The beta version we have appears to be v2.13.690 based on https://vallico.net/casinoqmc/diary/, dated 2018-02-06. They are up to v2.13.727 now, dated 2018-08-12.

https://vallico.net/casinoqmc/update-casino/
> Note: The standard 2.12.1 version is now a few years old and verging on obsolescence; it will soon be replaced by a new public distribution 2.14. For the moment people are therefore strongly recommended to use the current beta version – which is a very close approximation to the final 2.14.

I'll finish getting the arch files ready, and the user wanted a gcc version too as that seemed to have better performance, so I can do an arch file for that as well. I currently have a `linuxpc-intel-sge-parallel.rc.ucl.arch` for our systems which should be able to auto-submit jobs to SGE. (Just need to check that you can still submit manually using it too, as it may be more annoying to have to run an interactive tool each time).
