### ISSUE TITLE
Install request: NAMD 2.12

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#126]
IN:02688912

User's specific simulations with colvars are only working with 2.12.

**Comment by owainkenwayucl** [comment]
Well since I'm the NAMD "expert" I'll take this on.

**Comment by owainkenwayucl** [comment]
It looks like this is as simple as giving the existing script the correct version info for NAMD and Charm++.

**Comment by owainkenwayucl** [comment]
Built successfully on Grace.  Waiting on the others.

**Comment by owainkenwayucl** [comment]
Completed.
