### ISSUE TITLE
Install request: Oxford Nanopore data analysis software

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#127]
IN02654288

- Albacore - converting raw data files into basecalled files -
https://community.nanoporetech.com/protocols/albacore-offline-basecalli/v/abec_2003_v1_revaa_29nov2016/linux https://community.nanoporetech.com/protocols/albacore-offline-basecalli/v/abec_2003_v1_revaa_29nov2016/linux 
We need to sign up to access - how?
- Porechop - demultiplexing and adapter trimming - https://github.com/rrwick/Porechop
- Centrifuge - taxonomic classification of reads - https://github.com/infphilo/centrifuge
- Canu - de novo genome assembly - https://github.com/marbl/canu
- Racon - developing consensus sequence - https://github.com/isovic/racon
- Nanopolish - polish consensus sequence - https://github.com/jts/nanopolish
- BUSCO - assessing genome assembly quality - https://gitlab.com/ezlab/busco
- Prokka - Annotation of genome - https://github.com/tseemann/prokka

**Comment by balston** [comment]
Update from user:

> I think I'll be able to install the majority onto my own
> folder, however ALBACORE needs to be installed by Administrator only.
> 
> I've downloaded the pip wheel for python3.5. It's at
> ucbtacw/bin/albacore/ont_albacore-2.1.2-cp35-cp35m-manylinux1_x86_64.whl
> 
> You are welcome to access it.
> 
> Here are the installation instructions from the Oxford Nanopore website
> below:
> 
> -------------
> 
> Use this installation process if installing from .whl:
> Download the wheel that matches the version of Python you have installed
> from the Oxford Nanopore website.
> 
> Python 3.4:
> 
> https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-2.1.2-cp34-cp34m-manylinux1_x86_64.whl
> 
> Python 3.5:
> 
> https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-2.1.2-cp35-cp35m-manylinux1_x86_64.whl
> 
> Python 3.6:
> 
> https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-2.1.2-cp36-cp36m-manylinux1_x86_64.whl
> 
> To check your Python version, type:
> 
> python3 --version
> 
> For example, if you have Python 3.4.3, the wheel you download should
> include "cp34" (for CPython 3.4) in the name.
> 
> Install the wheel using pip:
> 
> pip3 install path/to/ont_albacore-xxx_x86_64.whl
> 
> substituting "path/to/ont_albacore-xxx_x86_64.whl" with the location of
> the file, and the version of Albacore.
> 
> This should automatically install Albacore and its dependencies.
> Depending on how pip is being used (e.g. if installing to your system as
> opposed to a virtual environment), you may require root for the
> installation command.
> 
> If you have previously installed an older version of albacore via pip,
> you will need to add the --upgrade flag to the above command to install
> a newer version.
> 
> ------------------
> 
> Will you be able to install ALBACORE please? The UK Manager of Oxford
> Nanopore is visiting us on 20th November, so if there are any issues
> I'll be able to flag them with him then.
> 
> Many thanks,
> 
> Tim.
>

**Comment by qiuyixmm** [comment]
@balston hello, could you send the  ALBACORE wheel for python=3.6 to me? My e-mail adress is xumingmin@mail.kiz.ac.cn. Thank you!
