### ISSUE TITLE
Install request: CASTEP 17.2.1

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#129]
IN:02692251

There is a bug in 17.2.

Also requests higher level of optimisation as is currently compiled with 'intermediate' - change in Makefile.

**Comment by ikirker** [comment]
Currently trying to reset the password on our account -- having problems receiving the email, have contacted CCPForge support.

**Comment by ikirker** [comment]
Done, new account made and added to project on CPPForge.

`fast` build setting works fine on Grace and Thomas but fails tests on Legion (374/442 passed on Y-type node). Currently testing `intermediate` on Legion.

**Comment by ikirker** [comment]
`intermediate` on Legion Y-type node fails 1 test. Unfortunately CASTEP's testing methodology is extremely terse and doesn't keep logs of what it does, so I have no idea which test or what the failure is, and the only way of working it out seems to be to pore through 884 output files looking for numerical differences the test script found that exceeded its tolerances.

**Comment by ikirker** [comment]
So, I was trying to see if there was a way to make the test output more verbose (which there is, the Makefile passes `-q` for quiet by default), and the tests succeeded. So I built it from scratch in a fresh directory, and all the tests passed.

And then I rebuilt the whole thing again, including the MPI version, from scratch, and all the tests passed.

❓ ❓ ❓ :woman_shrugging:

**Comment by ikirker** [comment]
Installed.
