### ISSUE TITLE
Install request: OpenMPI 2.0.2

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#134]
IN02716942

Current MPI modules are incompatible with ORCA computational chemistry software

**Comment by ikirker** [comment]
Installed 2.1.2 (as the most recent stable version of the 2 line) and 3.0.0, with Intel compilers. Will do GNU compilers next week.

**Comment by certant** [comment]
I was the user that requested the OpenMPI install. 
Whilst I understand that 2.1.2 is the most recent stable version unfortunately the ORCA software is pre-compilled and distributed as binaries that use OpenMPI 2.0.2. 

Would it be possible to also have 2.0.2 available as a module please?

**Comment by ikirker** [comment]
Currently installing 2.0.2, then (Intel and GCC), as well as the GCC versions of 2.1.2 and 3.0.0. Should be done by tomorrow. (They're all queued up but each one takes a while to build.)

**Comment by ikirker** [comment]
Installed.
