### ISSUE TITLE
Install request: CRYSTAL 17

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#138]
IN:02802834 and IN:02805921

We only have CRYSTAL 14 versions installed anywhere at present.

**Comment by balston** [comment]
I will create a Crystal 17 build script to install the optimised for Thomas and Grace version created for us by STFC.

**Comment by balston** [comment]
The optimised build archive is now in:
```
.../build_scripts/files/Crystal17/Pdistrib-Linux-ifort_XE_openmpi_avx2-v1.0.tar.gz
```

**Comment by balston** [comment]
The optimised build archive is not after all included with the build scripts for licensing reasons. All the licensed Crystal17 archives are in:
```
/shared/ucl/apps/Crystal17/archives/
```
This is readable only by _ccspapp_. Build script is _crystal17-1.0.1_install_.

**Comment by balston** [comment]
Running the build script on Grace after fixing a few issues shows that some of the paths used in the optimised build archive are not correct for UCL clusters. For example some begin: _/apps/intel_. It looks like the file:
```
$BUILD_LOCATION/build/Xmakes/Linux-ifort_XE_openmpi_avx2.inc
```
will need changes for UCL. Will use sed to make the changes before running "make all".

**Comment by balston** [comment]
The build script now finishes without errors. Next step is to run some tests.

**Comment by balston** [comment]
First test job submitted using test11 from the supplied test cases.

**Comment by balston** [comment]
Test job has run after fixing a couple of problems with my test module file. Test result:
```
 TOTAL ENERGY(HF)(AU)(   7) -2.7466419186128E+02 DE-5.0E-10 tst 1.7E-12 PX 1.3E-04
```
Supplied result:
```
 TOTAL ENERGY(HF)(AU)(   7) -2.7466419186124E+02 DE-3.1E-09 tst 2.9E-10 PX 2.5E-04
```

**Comment by balston** [comment]
Now to repeat the build and test on Thomas.

**Comment by balston** [comment]
The build on Thomas has completed.

**Comment by balston** [comment]
I've submitted a test job on 48 cores on Thomas.

**Comment by balston** [comment]
Test job has finished:
```
 TOTAL ENERGY(HF)(AU)(   7) -2.7466419186128E+02 DE-5.0E-10 tst 1.7E-12 PX 1.3E-04
```

**Comment by balston** [comment]
Running a Ppropertires test job on Thomas now.

**Comment by balston** [comment]
Only the Grace one has finished and it looks like it has worked correctly. I'm going to update the module file now.

**Comment by balston** [comment]
Installation completed on:
- [ ]  Grace;
- [ ] Thomas.

Use module commands:
```
module unload mpi
module load mpi/openmpi/2.1.2/intel-2017
module load crystal17/v1.0.1
```

**Comment by balston** [comment]
Now to install on Legion. It will not be possible to optimise for the Legion hardware.

**Comment by balston** [comment]
Working out what changes if any are needed to:
```
crystal17_v1_0_1_Linux-ifort17_emt64_Pdistrib.tar.gz
```
to compiler the parallel version on Legion.

**Comment by balston** [comment]
Had to update the architecture config file and location for binaries.

**Comment by balston** [comment]
Build script updated and run on Legion. Will now need to slightly modify the module file with a Legion only section.

**Comment by balston** [comment]
Module file updated with info about optimised/non-optimised added to module help. Test job submitted.

**Comment by balston** [comment]
Test job has worked.

**Comment by balston** [comment]
Installation completed on:
- [ ] Legion.

**Comment by heatherkellyucl** [comment]
It needed the recompiled `crystal` to be copied over from the build (instructions were only to copy over `Pcrystal`) as otherwise it tries to link libibverbs which doesn't exist on Thomas. @balston changed this in the buildscript.
