### ISSUE TITLE
Gromacs 2018 (IN:02811273)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#139]

**Comment by ikirker** [comment]
Currently adapting from 2016.3 script.

**Comment by ikirker** [comment]
Installing...

- [ ] Legion
- [ ] Grace
- [ ] Thomas

**Comment by owainkenwayucl** [comment]
User has contacted us to thank us for installing (thanks @ikirker!).

Closing for now.
