### ISSUE TITLE
FoldX (IN:02819170)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#141]
A user has requested FoldX.  There are apparently free licenses available but no indication of the license terms and the documentation is pretty sparse about requirements.

http://foldxsuite.crg.eu/

**Comment by balston** [comment]
I've signed up for an account on the FoldX website as you cannot read the Academic License agreement until you have an account.

**Comment by balston** [comment]
Accessed and read the Academic License Agreement. It:
- Can be signed (on-line only) on behalf of UCL or by individuals.
- Central installs possible as a reserved application.
- License will terminate on 31st December 2018.
- Not clear how to renew.

I've signed myself but will also get Robert Silk to sign on behalf of UCL.

**Comment by balston** [comment]
I've now got access to the downloads and there is a 64 bit Linux binary plus support files. I've downloaded everything as the download link will time out after a few days.

**Comment by balston** [comment]
I've emailed Robert Silk  asking him to sign up to the Academic License on behalf of UCL.

**Comment by balston** [comment]
Robert has signed the Academic License for UCL so we can proceed with the central install on Legion. First we need to create the reserved application group (_legfldx_) and add _ccspapp_ to it.

**Comment by balston** [comment]
We have some information about installation:

> From: jdelgadoblanco@gmail.com
> Sent: Thu, Feb 1, 2018 15:16 PM
> To: cheng.zhang@ucl.ac.uk;
> Cc: rc-support@ucl.ac.uk; luis.serrano@crg.es;
> Subject: Re: Incident #02819170 (Ref:IN:02819170)
> 
> The executable is self contained, just copy it an make a rotabase.txt link in the running directory
> 
> Cheers
> 
> JAvier
> 

Also from the manual:
-    Add the binary location to PATH environment variable.
-    The file rotabase.txt or a soft link should be in the working directory.
-    Please consider repairing the pdb as a must for any further command.

**Comment by balston** [comment]
The reserved application group for FoldX has been created - _legfldx_. Unfortunately our application installation account is already in the maximum number of groups so cannot be added to _legfldx_. I'm creating a second account _ccspap2_ and will use this for the installation instead.

**Comment by balston** [comment]
I've installed the basic FoldX application on Legion. I now need to create a module and see if it actually works!

**Comment by lanselibai** [comment]
thank you so much! Hope to use it soon!

I am running the following script on my cmd on Win7. Hope it can be run on Legion.

```
FoldX --command=RepairPDB --pdb=RP.pdb
ren RP_Repair.pdb old.pdb

FoldX --command=RepairPDB --pdb=old.pdb
del /f old.pdb
ren old_Repair.pdb old.pdb
```

The `RP.pdb` can be downloaded from [here](http://foldxsuite.crg.eu/sites/default/files/RP.pdb)

**Comment by balston** [comment]
@lanselibai's example seems to have worked so I've uploaded the module file to Legion:
```
module avail foldx
```
```
------------------ /shared/ucl/apps/modulefiles/applications -------------------
foldx/4
```
Will email with a suggested job submission script.

**Comment by balston** [comment]
I need to add a group membership check to the module file.

**Comment by lanselibai** [comment]
Hi @balston , thank you for installing the FoldX! Could you please remove my email in one of your comments? Thank you very much!

**Comment by balston** [comment]
This is now completed.

**Comment by lanselibai** [comment]
thank you very much! I tested it and it worked!
