### ISSUE TITLE
Install request: blender

### ISSUE THREAD

**Issue by tcouch** [UCL-RITS/rcps-buildscripts#143]
The Slade School of Fine Art would like to try using blender on Legion to take care of some of the bigger jobs such as rendering that are currently running on their desktops for days at a time.

**Comment by tcouch** [comment]
Here's the manual:
https://docs.blender.org/manual/en/dev/getting_started/installing/index.html

**Comment by balston** [comment]
The Linux installation is very straightforward from the instructions: "Unpack the archive, then run the Blender executable. "

I've seen a number of google references to running blender in batch mode with SGE so this looks promising as well.

**Comment by balston** [comment]
I've installed the Blender binary distribution blender-2.79-linux-glibc219-x86_64.tar.bz2 on Legion in:
```
/shared/ucl/apps/Blender/blender-2.79-linux-glibc219-x86_64
```
Will now create a module file.

**Comment by balston** [comment]
Module file now created. Use:
```
module load  blender/2.79
```
