### ISSUE TITLE
Install request: skewer (IN: 02838594)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#144]
Mariana Pereira has asked for skewer a tool for processing next-generation sequencing (NGS) paired-end sequences to be installed on Legion.

https://github.com/relipmoc/skewer

**Comment by owainkenwayucl** [comment]
I'll take a pass at this.

**Comment by owainkenwayucl** [comment]
It looks like there's a tagged release 0.2.2 which is about the same age as every file in the repository so I guess we'll go for that?

**Comment by maribuon** [comment]
Yes, please :)

**Comment by owainkenwayucl** [comment]
OK, I've installed it on Legion and have put a module file in `skewer/0.2.2`.

You should be able to load it into your environment by doing:

```
module load skewer/0.2.2
```

**Comment by maribuon** [comment]
Thanks! On a quick test, it seems to be working :)

**Comment by owainkenwayucl** [comment]
Excellent - I'll close this issue then.
