### ISSUE TITLE
Install request: OpenMX DFT package (IN: 02839948)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#145]
Requested by Ji-Sang Park from Imperial.

http://www.openmx-square.org/

**Comment by owainkenwayucl** [comment]
Taking a pass at this.

According to the website this is GPL3 so no license issues: http://www.openmx-square.org/whatisopenmx.html

**Comment by heatherkellyucl** [comment]
User says it works.
