### ISSUE TITLE
Install request: LAPACK

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#149]
IN:02849537

Needed by a binary toolbox. GNU compiler build.

http://www.netlib.org/lapack/
http://www.netlib.org/lapack/lapack-3.8.0.tar.gz

**Comment by ikirker** [comment]
🤦‍♂️

**Comment by heatherkellyucl** [comment]
Both interested parties were emailed. (Was also 02849213 who might have wanted to use it).
