### ISSUE TITLE
Install request: fgbio (IN:02867476)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#151]
https://github.com/fulcrumgenomics/fgbio

**Comment by maribuon** [comment]
Any news?

**Comment by maribuon** [comment]
Hi! Do you have an estimation on when it might be installed? :)

**Comment by heatherkellyucl** [comment]
This is provided as a jar so just needs downloading from https://github.com/fulcrumgenomics/fgbio/releases. 
Current release is 0.5.1. Will need to load one of the java modules to run it as it needs 1.8. Will add a wrapper script like our other jars.

**Comment by heatherkellyucl** [comment]
fgbio is installed.
```
module load java/1.8.0_92
module load fgbio/0.5.1
```
You can run it like:
`java -Xmx4g -XX:+AggressiveOpts -XX:+AggressiveHeap -jar $FGBIOPATH/fgbio-1.5.0.jar`
or use our wrapper that sets the above options:
`fgbio`
