### ISSUE TITLE
Install request: Delly

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#156]
IN:02889398

https://github.com/dellytools/delly/blob/master/README.md

> Delly is an integrated structural variant (SV) prediction method that can discover, genotype and visualize deletions, tandem duplications, inversions and translocations at single-nucleotide resolution in short-read massively parallel sequencing data.

**Comment by ikirker** [comment]
This vendors in Boost, but seems to need libz, liblzma, and libbz2 as external dependencies.

It doesn't have a build system more substantial than just a `Makefile`, there's no install target, and with the vendoring in of Boost and rpathing as well, it looks like it either needs to be built using the static build option (which they release with so probably works), or in-place.

TBH we could just install the static build.

For building it, so far I'm at:
```
git clone --recursive --branch=v0.7.8 https://github.com/dellytools/delly.git
cd delly
make STATIC=1 PARALLEL=1 src/delly
```

PARALLEL in this case means use OpenMP, not anything more distributed.

**Comment by ikirker** [comment]
Yeah, I didn't see much point in rebuilding it with all the same settings and probably a worse compiler, so I just installed the binary.

**Comment by heatherkellyucl** [comment]
It needed the executable being given execute permissions and symlink adding in the right place - 
in `/shared/ucl/apps/delly/0.7.8-bindist/bin` do `ln -s delly_v0.7.8_parallel_linux_x86_64bit delly`

The symlink created by the buildscript was in `/shared/ucl/apps/delly/0.7.8-bindist` so doesn't exist, and that isn't in the PATH.
