### ISSUE TITLE
Install request: bio3d for R

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#157]
IN:02895975

bio3d: Biological Structure Analysis

https://cran.r-project.org/web/packages/bio3d/index.html

**Comment by balston** [comment]
This looks pretty straightforward without a large list of dependencies so running: 
```
cd /shared/ucl/apps/build_scripts
module load r/recommended
./R-package_install bio3d
```

**Comment by balston** [comment]
Installed without error and supplied demos run.

**Comment by balston** [comment]
I've informed the requester and asked them to test.

**Comment by balston** [comment]
User has responded:

> Hi Brian,
> 
> Yes, it works now! Thank you very much!
> 
> Yours sincerely
> 
> Cheng

**Comment by balston** [comment]
Added _bio3d_ to:
```
rcps-buildscripts/files/R_UCL/R_packages_UCL_5.R
```
For future R installations.

**Comment by balston** [comment]
bio3d installed in R 3.4.2 on:
- [ ] Legion;
- [ ] Grace;
- [ ] Thomas.

**Comment by balston** [comment]
Now installed on all clusters.
