### ISSUE TITLE
Install request: GNU compiler >=6.3

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#160]
IN:02903274

Needs gfortran >= 6.3 or 7.

This would be as a standalone module only, not updating everything to use the new gcc at present.

**Comment by ikirker** [comment]
```
wget ftp://ftp.mirrorservice.org/sites/sourceware.org/pub/gcc/releases/gcc-7.3.0/gcc-7.3.0.tar.xz
tar -xf gcc-7.3.0.tar.xz
cd gcc-7.3.0
contrib/download_prerequisites
./configure --prefix=/dev/shm/gcc-tmp-prefix --enable-libssp --with-system-zlib --with-quad --disable-multilib --enable-lto --enable-languages=c,c++,fortran,lto,brig --enable-bootstrap --enable-stage1-checking
make -l $(( $(nproc) - 1 )) -j
```

**Comment by ikirker** [comment]
There's some property of the system `cpp` that leads the `configure` script to declare it unsuitable, so I'm trying using the one from the 4.9.2 GCC. The bootstrap process should serve to ensure it isn't a dependency in the final build.

**Comment by ikirker** [comment]
Have to install autogen to run the tests.

**Comment by ikirker** [comment]
Hmm. It looks like the tests fail because they detect that the GMP version in `gmp.h` does not match that in the GMP library whatever binary is linked against. I *think* this is because it's finding the *system* `gmp.h` when it does this, since the complaint is that 6.0.0 != 6.1.0, and the system version is 6.0.0, and everything in the GCC build directory is 6.1.0.

**Comment by owainkenwayucl** [comment]
Would it be a sensible workaround to build it against 6.0.0 and then they'll match?

Or does 7.3.0 require 6.1 or higher?

**Comment by ikirker** [comment]
@owainkenwayucl I don't know -- the prereqs downloader script just grabs 6.1.0. From previous experience, though, I've had instances where gcc was *very* sensitive to library versions.

**Comment by owainkenwayucl** [comment]
damn :(

**Comment by ikirker** [comment]
I'm just giving it a try with the system gmp to see if that works.

(Uses the prereq downloader, and then deletes the GMP directory and tarfile.)

**Comment by ikirker** [comment]
Right, that works and all the tests run successfully, so I've replaced the previous installation with this new version.

**Comment by ikirker** [comment]
For the sake of consistency, and because we still don't have a blocking mechanism for inapplicable modules, I'll install it on Grace and Thomas as well.
