### ISSUE TITLE
Install request: New versions of STAR-CD (IN02962884)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#165]
Alex Kountouriotis  is asking for two new versions of STAR-CD on Legion and Grace:

> Could you please install two newer versions of STAR-CD?
> 
> The first is the version V4.26.022 which is the updated version of the default of the cluster, which possibly has a bug. I am using V4.26.022 for my models.
> 
> Could you also install the latest version which is V4.28.050?
> 
> Both are in my SCRATCH directory, my ID is ucem015
> 
> Kind regards,
> 
> Alex

**Comment by balston** [comment]
The installation files are in Alex's Scratch on Grace.

**Comment by balston** [comment]
The installation archives are now in _~ccspapp/Software/STAR-CD/_:
```
total 9.4G
-rw-r--r-- 1 ccspapp ccsp 4.3G May  4 14:46 STAR-CD_4.26.022_201609151211-Linux_x86_64.tar
-rw-r--r-- 1 ccspapp ccsp 5.2G May  4 14:48 STAR-CD_4.28.050_201801291142-Linux_x86_64.tar
```
on Grace.

**Comment by balston** [comment]
Starting with version 4.26.022 on Grace. Making new build script from _star-cd-4.26.011_install_ that @heatherkellyucl did last time.

**Comment by balston** [comment]
Installing 4.26.022. As _ccspapp_:
```
cd /shared/ucl/apps/build_scripts
./star-cd-4.26.022_install
```
Then answer questions:
- Installation directory: _/shared/ucl/apps/STAR-CD/4.26.022_
- Software Selection: Select all but remove the license manager - _A_, then _4_ followed by _Next_
- Packages Selection: Select all - _A_ followed by _Next_
- Packages Confirmation: _N_ to start installation

It is suggesting that the installation will take more that an hour so may have to re-start this on Tuesday.

**Comment by balston** [comment]
The packages installation stage has finished so continuing:
- Please enter CDLMD_LICENSE_FILE ... - _Enter_ to continue as access to LM will be setup in module file
- Please enter LM_LICENSE_FILE ... - _Enter_ again
- Secure Shell (ssh/scp) - _N_ (do not want to use an alternative)
- Please enter your selection (R=Restart C=Close): C

Finished!

**Comment by balston** [comment]
Now need to update the module file and run some tests next week.

**Comment by balston** [comment]
Module file updated. I'm now testing it before making it live ...

**Comment by balston** [comment]
I've finally managed to get my test job to start correctly (it is from the CFD/CCM TUTORIALS manual - Tutorial 1 Flow in a Mixing Pipe). _Time to wait and watch_ ...

**Comment by balston** [comment]
My test job completed at about 6pm:
```
   *** CALCULATIONS TERMINATED - CONVERGENCE CRITERION SATISFIED
 
  END OF EXECUTION - STAR 
  SOLVER: CPU time is     8629.48    Elapsed time is     8682.98
  TOTAL : CPU time is     9058.38    Elapsed time is     9317.85
 
PNP: Shutdown    [2018-05-09-18:03:57] Execution completed after 9324.29 seconds (OVERALL ELAPSED TIME).
```
This was using STAR-CD's default MPI: 
```
IBM Platform MPI ISV Edition 08.3.0.2
```
I'm now going to run the same example using Intel MPI.

**Comment by balston** [comment]
The Intel MPI version of the test has also completed successfully:
```
   *** CALCULATIONS TERMINATED - CONVERGENCE CRITERION SATISFIED
 
  END OF EXECUTION - STAR 
  SOLVER: CPU time is     6906.64    Elapsed time is     6931.39
  TOTAL : CPU time is     7193.97    Elapsed time is     7345.11
 
PNP: Shutdown    [2018-05-10-14:51:45] Execution completed after 7348.94 seconds (OVERALL ELAPSED TIME).
```
This used:
```
Intel MPI 4.1
```

**Comment by balston** [comment]
Just tested the prostar GUI on Grace Login01 and it appears to be working fine.

**Comment by balston** [comment]
STAR-CD Version 4.26.022 now installed on:
- [ ] Grace;
- [ ] Legion.

**Comment by balston** [comment]
Alex has run a test which uses the es-ice plugin which fails:
```
This version of the code requires license version 2016.09 or greater.
Licensing problem: Unable to find a path to any license file or license server. Please create the CDLMD_LICENSE_FILE environment variable and point it to the license server.
FLEXnet error: (-1,359)
A valid license is required for Ice ("proice").
Connected by a socket to "node-r99a-077:6543".
Failed.
```
I thought at first I had messed up the new module file but this doesn't seem to be the case.

Further investigation suggests that the problem may be caused by the FlexNet license manager not being installed even though we don't run the LM locally! Previous versions of STAR-CD have this installed so I'm going to install it.

**Comment by balston** [comment]
Even after the addition of the LM software, Alex still cannot run his test with the es-ice plugin. I've now got a copy of his simulation for further investigation.

**Comment by balston** [comment]
I've now submitted my copy of Alex's simulation and it runs fine for me. I've got one more thing to add to the installation process which I'm going to try next week.

**Comment by balston** [comment]
I've now reinstalled STAR-CD setting the license file location in multiple places not just in the module file. I've run my copy of Alex's simulation without problems so have asked Alex to try again.

**Comment by balston** [comment]
Alex says it is now working. So Grace installation is finally done.

**Comment by balston** [comment]
The correct installation procedure  for version 4.26.022 is this. As ccspapp:
```
cd /shared/ucl/apps/build_scripts
./star-cd-4.26.022_install
```
Then answer questions:
-    Installation directory: _/shared/ucl/apps/STAR-CD/4.26.022_
-    Software Selection: Select all including the license manager - A followed by Next
-    Packages Selection: Select all - A followed by Next
-    Packages Confirmation: N to start installation

When the packages installation stage has finished continue with:
-    Please enter CDLMD_LICENSE_FILE ... - _1999@ntsrv1.meng.ucl.ac.uk_
-    Please enter LM_LICENSE_FILE ... - _1999@ntsrv1.meng.ucl.ac.uk_
-    Secure Shell (ssh/scp) - N (do not want to use an alternative)
-    Please enter your selection (R=Restart C=Close): C

Finished!

**Comment by balston** [comment]
Now running tests on the legion installation.

**Comment by balston** [comment]
Both my test and Alex's more complex simulation run on Legion.

Installation of STAR-CD 4.26.022  completed.

**Comment by balston** [comment]
OK now beginning the installation of the latest STAR-CD version 4.28.050 on Grace.

**Comment by balston** [comment]
The installation procedure for version 4.28.050 is as follows. As _ccspapp_:
```
cd /shared/ucl/apps/build_scripts
./star-cd-4.28.050_install
```
Then answer questions:

    Installation directory: /shared/ucl/apps/STAR-CD/4.28.050
    Software Selection: Select all including the license manager - A followed by Next
    Packages Selection: Select all - A followed by Next
    Packages Confirmation: N to start installation

When the packages installation stage has finished continue with:

    Please enter CDLMD_LICENSE_FILE ... - 1999@ntsrv1.meng.ucl.ac.uk
    Please enter LM_LICENSE_FILE ... - 1999@ntsrv1.meng.ucl.ac.uk
    Secure Shell (ssh/scp) - N (do not want to use an alternative)
    Please enter your selection (R=Restart C=Close): C

**Comment by balston** [comment]
Module file prepared now ready for some tests ...

**Comment by balston** [comment]
First test job submitted:
```
~ccaabaa/Scratch/STAR-CD/test-star_Intel_MPI/TEST-32_Intel_MPI.sh
```

**Comment by balston** [comment]
I've also submitted:
```
~ccaabaa/Scratch/STAR-CD/test-star_IBM_MPI/TEST-32_IBM_MPI.sh
```
also for 12 hours.

**Comment by balston** [comment]
- The Intel MPI test completed successfully;
- The IBM MPI test also completed successfully.

Now to test Alex's more complex simulation.

**Comment by balston** [comment]
```
~ccaabaa/Scratch/STAR-CD/alex-test/TEST_UCL_BAA.sh
```
has been submitted.

**Comment by balston** [comment]
The Alex test failed the first time so I've cleaned the directory and re-submitted the test to start from the beginning.

**Comment by balston** [comment]
Now doing the Legion installation ...

**Comment by balston** [comment]
The install failed the first time round so I've had to start it again. It runs very slow on Legion - a couple of hours to install files.

**Comment by balston** [comment]
The install on Legion worked the second time.

**Comment by balston** [comment]
Test job using IBM Platform MPI has worked:
```
  FINISH ITERATION NO.  7394
  SOLVER: CPU time is    16359.72    Elapsed time is    16391.60
  TOTAL : CPU time is    16863.60    Elapsed time is    17284.29
  &&&& --------------------------------------------------------------  --------------------------------------------------------------


                                        **************************************************
                                        * THERE ARE      2 MASTER PROCESSOR REPORTED WARNINGS IN FILE static1.75RNG.info
                                        **************************************************


   *** CALCULATIONS TERMINATED - CONVERGENCE CRITERION SATISFIED
 
  END OF EXECUTION - STAR 
  SOLVER: CPU time is    16359.72    Elapsed time is    16391.60
  TOTAL : CPU time is    16864.38    Elapsed time is    17286.90
 
PNP: Shutdown    [2018-06-27-15:14:54] Execution completed after 17292.69 seconds (OVERALL ELAPSED TIME).
```
Repeating with Intel MPI ...

**Comment by balston** [comment]
The IBM Platform MPI test job simulation converged after about 4.75 hours.

**Comment by balston** [comment]
The Intel MPI test job also completed successfully and converged after about 2.25 hours!

Looking back at the tests runs of the same simulation on Grace:
- IBM Platform MPI 2.7 hours;
- Intel MPI 2.1 hours.

**Comment by balston** [comment]
Installation of STAR-CD Version 4.28.050 has now been completed on:
- [ ] Grace;
- [ ] Legion;
- [ ] Myriad.

**Comment by balston** [comment]
Myriad tests:
- IBM Platform MPI successfully converged 5 hours 10 mins.
- Intel MPI failed:
```
PNP: Initialized [2018-06-29-06:30:53] Automatic Sequential Automatic Parallel analyzer.
PNP:   Allocated "node-h00a-007,32" resource (32 processes).
PNP:   Assigned  "node-h00a-007,32" resource to STAR solver (32 processes).
PNP:   Activated "/usr/bin/ssh -o StrictHostKeyChecking=no" command for starting tasks on remote nodes.
PNP:   Activated "/usr/bin/scp -o StrictHostKeyChecking=no" command for copying files to/from remote nodes.
PNP: Loading     STAR double precision solver dynamic shared object plug-ins.
PNP: Loading     Intel MPI 4.1 dynamic shared object plug-ins.
PNP: Spawning    STAR process on single node.
APPLICATION TERMINATED WITH THE EXIT STRING: Segmentation fault (signal 11)
PNP: Shutdown    [2018-06-29-06:30:55] Execution terminated after 2.29 seconds (OVERALL ELAPSED TIME).

libi40iw-i40iw_ucreate_qp: failed to create QP, unsupported QP type: 0x4
```

**Comment by balston** [comment]
For the Intel MPI test job:
```
setenv I_MPI_FALLBACK   1
```
was missing which probably caused the failure. Resubmitted.

**Comment by balston** [comment]
I've pushed out the module file for STAR-CD Version 4.28.050 to the clusters and updated our Wiki pages.

**Comment by balston** [comment]
The Intel MPI version doesn't work on Myriad.

**Comment by heatherkellyucl** [comment]
(Switched to using Platform MPI to get it to work on Myriad)

**Comment by ikirker** [comment]
(Error with Intel MPI is same Mellanox-related one: `libi40iw-i40iw_ucreate_qp: failed to create QP, unsupported QP type: 0x4`.)
