### ISSUE TITLE
Install request: Nighres neuroimage software (IN:02967386)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#166]
Nighres neuroimage software (http://nighres.readthedocs.io/en/latest/) on Legion.

**Comment by owainkenwayucl** [comment]
OK, for the first step I'm going to install OpenJDK 11 since that is our plan going forwards.

**Comment by owainkenwayucl** [comment]
Right.  For "reasons" the Java folks moved where `.so` files were which breaks installing JCC.  I've put in sym-links as this will probably be a problem for other python <-> java packages.

**Comment by owainkenwayucl** [comment]
bleh.

```
Python 3.6.3 (default, Oct 10 2017, 15:11:55) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nighres
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/shared/ucl/apps/nighres/1.1.0b/lib/python3.6/site-packages/nighres/__init__.py", line 2, in <module>
    import nighres.brain
  File "/shared/ucl/apps/nighres/1.1.0b/lib/python3.6/site-packages/nighres/brain/__init__.py", line 1, in <module>
    from nighres.brain.extract_brain_region import extract_brain_region
  File "/shared/ucl/apps/nighres/1.1.0b/lib/python3.6/site-packages/nighres/brain/extract_brain_region.py", line 5, in <module>
    import nighresjava
  File "/shared/ucl/apps/nighres/1.1.0b/lib/python3.6/site-packages/nighresjava/__init__.py", line 3, in <module>
    from . import _nighresjava
ImportError: cannot import name '_nighresjava'
```

**Comment by owainkenwayucl** [comment]
OK, the pip install step is not pulling in the nighresjava stuff for some reason.

**Comment by owainkenwayucl** [comment]
As in the only thing in that folder after a pip install is `__init__.py`.

**Comment by owainkenwayucl** [comment]
I've opened an issue as they are on github: https://github.com/nighres/nighres/issues/102

Meanwhile I'll make the script copy the files manually.

It also looks like I need to put some other packages (e.g. six) in that folder if I want it to depend on `python/3.6.3` rather than the bundles.

**Comment by owainkenwayucl** [comment]
OK - I have written permission to install bgenie.
