### ISSUE TITLE
Install request: R.E.D. RESP

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#17]
>Myself, and at least two of my PhD students require an online service called  R.E.D. RESP (Restrained Electrostatic Potential). It essentially derives point charges of an atomistic structure for AMBER by first optimising the structure using Gaussian (Gaussian Inc. gave them a 'public' license to dump out the final structure but not any of the energetic or frequency data) and then running the structure through a series of python scripts according to some key-value parameter values provided in two input files. The final product is a zip file full of charge data and coordinate geometry.

>Unfortunately, a week ago the R.E.D. Server had gone down. The AMBER community has no idea what's happened. Thankfully, the service providers give away the source code under the GNU license so institutes can establish their own private R.E.D. RESP servers. The link to the scripts is below (rescued by someone before the service died) - as you can guess, any further information has vanished along with the website.

http://lysozyme.medchem.utah.edu/ros/public_html/RED/RED-III.52-Tools-Files/

Investigate if we can install this as a module on Legion. IN00799592

**Comment by heatherkellyucl** [comment]
Update from IN00800667, info on getting it running.

Update from IN00800667, info on getting it running.

>What I normally do is this:
>
>I build the molecule of whatever ligand I want to generate charges.
>Normally I use GaussView because is very simple for build small
>molecules and gives a nice pre-optimized structure.  I save the file
>as PDB (lets say init.pdb, initial.pdb)
>
>Then I run Ante-red to generate the optimization input file:
>
>$ Ante_RED-1.5.pl init.pdb
>
>This generates a few files:
>
>init-gam.inp
>init.gau.com
>init-info.txt
>init-out.p2n
>init.out.pdb
>init.pcg.inp
>
>These are different inputs for different QM programs and the p2n file
>which is the input for the actual charge fitting.
>
>The file init-gau.com is the input for gaussian.  It has all the
>necessary keywords.  Now, I have modified the script Ante_RED-1.5.pl
>so it will generate the g09 input specific for the cluster that we
>have, that is, it generates the .com file with the specific number of
>processors and memory and also I added more SCF cycles so it wont
>terminate, etc etc.  You can either modify teh Ante_RED-1.5.pl or
>change the resulting gaussian file.
>
>You then run the init-gau.com in gaussian.  It is an optimization so
>you need to have a Stationary point.  You will now have init-gau.log
>
>Now, adjust your init-out.p2n file.  Change the charge and
>multiplicity to match your molecule.
>
>This is one tricky step, the next step is to  actually run the RED
>fitting, but the RED-vIII.52.pl script only takes these files:
>
>Mol_red1.log
>Mol_red1.p2n
>
>So, what I do is create a sym link:
>
>ln -s init-out.log Mol_red1.log
>ln -s init-out.p2n Mol_red1.p2n
>
>Now you can run the fitting, but remind that it uses gaussian to do
>the actual fitting, so you need to have the gaussian directories
>declared.   The command looks like:
>
>perl RED-vIII.52.pl >& RED.log
>
>this will look for the Mol_red1* files and output to RED.log
>If you had all the gaussian variables declared, it will generate a lot
>of files and do the fitting.  At the end, what we want is this file:
>
>Mol_m1-o1.mol2
>
>That file has in the last column, the RESP charges for each atom.  Now
>you can run that file through antechamber to get the atom names
>according to GAFF, then run parmchk to generate the FRCMOD file  and
>if all the parameters are there, you are good to go.
>
>-------------------------------------
>This is my cluster submission script (using the SLURM queuing system)
>for the fitting:
>-------------------------------------------
>
>#!/bin/tcsh
>#SBATCH --job-name=8og
>#SBATCH --time=72:00:00
>#SBATCH --nodes=1
>#SBATCH --ntasks-per-node=12
>#SBATCH --account=owner-guest
>#SBATCH --partition=ember-guest
>#SBATCH --mail-type=ALL
>#SBATCH --mail-user=test@test.com
>set echo
>
>setenv PERL5LIB "/blah/common/home/user/scripts/lib/"
>set path = ($path
>/blah/common/home/user/scripts/RED-III.52-Tools-Files/resp-2
>.2)
>
>setenv GAUSS_SCRDIR "/blah/chpc_gen/user/$SLURM_JOBID"
>mkdir $GAUSS_SCRDIR
>
>cd $SLURM_SUBMIT_DIR
>
>setenv g09root /blah/sys/pkg/gaussian09/EM64T
>set path = ($path $g09root/g09/linda8.2/opteron-linux/bin)
>setenv MP_NEWJOB yes
>setenv LINDA_CLC network
>setenv LINDA_FLC network
>cat $SLURM_JOB_NODELIST | uniq > Gau.hosts
>set NODELIST = `xargs echo < Gau.hosts`
>cat Gau.hosts | xargs >tsnet.nodes
>echo $NODELIST
>source $g09root/g09/bsd/g09.login
>cp Gau.hosts nodes.tmp
>source $g09root/../etc/parascript.csh > Default.Route
>
>
>cp ~/scripts/RED-III.52-Tools-Files/RED-vIII.52.pl .
>
>perl RED-vIII.52.pl >& RED.log
>
>rm nodes.tmp Gau.hosts Default.Route tsnet.nodes
>--------------------------------------------------------------------------
>-------------------
>
>of course you will have to modify it according to your clusters.

**Comment by owainkenwayucl** [comment]
I think this shouldn't be too hard for the user to install themselves, looking at the SLURM script above - they just need to make sure that they have a copy of the scripts in their home directory, and load the perl module and set PERL5LIB appropriately.

**Comment by owainkenwayucl** [comment]
Also, somewhat complicating matters, the link above is to a directory of the stuff, not a place where there are tar files.

**Comment by owainkenwayucl** [comment]
Interestingly, both the Forcefieldtools.org page and the University of Picardie one (linked from http://ambermd.org/Questions/resp.html) have gone.

So something's happened.

**Comment by owainkenwayucl** [comment]
OK, the license is profoundly unclear, looking at mailing list archives.

E.g.

``` 
The R.E.D. III.x tools are not "FREE" programs (i. e. in the sense of
"freedom"; see the GNU web site for a clear definition). They are
provided at no cost for ACADEMIC users involved in NON-PROFIT RESEARCH
after signing a license. Industrial/COMMERCIAL users are asked to pay
3000.00 ? for using the R.E.D.III.x tools. The PI (Principal
Investigator or Director) of a laboratory has to be registered as a
R.E.D. III or R.E.D. III.x user to be authorized to download the
R.E.D. III.x tools (indeed, we do not accept anymore user agreement
from students or post-doc). During the registration procedure, the PI
has to select a license among the four different licenses available:
(1) License for Academic user & Non-profit research - User from north
& south America,
(2) License for Academic user & Non-profit research - User from Europe
& the rest of the world,
(3) License for Profit research (academic & non-academic user) - User
from north & south America,
(4) License for Profit research (academic & non-academic user) - User
from Europe & the rest of the world.
Please, see the Register section from the R.E.D. home page to
register, and display these licenses. 
```

**Comment by owainkenwayucl** [comment]
Although, here is a later message saying they are GPL: http://archive.ambermd.org/201310/0141.html

**Comment by heatherkellyucl** [comment]
We can't confirm the license status for this version - people can install it in their homes, but we will not be installing a central version at this point. The developers appear to be non-contactable.
