### ISSUE TITLE
Matlab toolboxs MOSEK, RAVEN and COBRA (IN:02987151)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#170]
RAVEN and COBRA appear to be open source.

It's less clear about MOSEK.

**Comment by owainkenwayucl** [comment]
MOSEK appears to be commercial.

**Comment by owainkenwayucl** [comment]
It looks like there's some sort of free academic license here: https://www.mosek.com/products/academic-licenses/

**Comment by balston** [comment]
MOSEK uses FlexNet for its license manager (token server) so should be fairly straightforward to install on the lm-server3 UCL license server box. I'll go ahead and apply for a academic site license for the default number of seats.

**Comment by balston** [comment]
I've completed the online form to request an academic site license for 50 seats.

**Comment by balston** [comment]
I've received the following email with the license:

> Dear user,
> 
> This email contains a Institutional Academic License file for the MOSEK optimization tools, valid until 2020-may-21. This license supports both current and earlier versions of MOSEK.
> 
> Since the license you are receiving is an Institution Academic License, you will need to follow special instructions to use it. These instructions can be found in our documentation: www.mosek.com/documentation.
> 
> Please contact MOSEK Support at www.mosek.com if you experience any problem.
> 
> Best regards
> 
>

**Comment by balston** [comment]
I'm going to do a test install of the license manager in my test environment.
