### ISSUE TITLE
Install Intel 2018 compiler, stop building with 2017

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#171]
As well as #167 numerical issues, today's Tier2 call confirmed multiple sites having problems with the Intel 2017 compiler and MPI. (CASTEP problems and bugs in MPI collective I/O write function, Fortran unable to write file errors).

These are supposed to be fixed with 2018, and seemed to have fixed the file writing errors. Sites intending to move to 2018 as the default compiler.

Suggest we install 2018 asap and stop building things with 2017.

**Comment by balston** [comment]
I'm downloading the latest 2018 Update 2 bundles from the Intel Registration Centre with my UCL site login.

**Comment by balston** [comment]
Install archive:
```
parallel_studio_xe_2018_update2_cluster_edition.tgz
```
now in:
```
/shared/ucl/apps/intel/installers
```
on Legion, Grace and Thomas. Will add to Myriad when we can scp files to it.

**Comment by balston** [comment]
The install archive is now also on Myriad in the same location.

**Comment by owainkenwayucl** [comment]
I guess we need a comms plan for migrating the default modules as we did for 2017 as well.

**Comment by balston** [comment]
Intel have just released update 3 so we should use this version. I'm starting to download it now ...

**Comment by balston** [comment]
```
parallel_studio_xe_2018_update3_cluster_edition.tgz
```
now in:
```
/shared/ucl/apps/intel/installers
```
on:
- [ ] Grace;
- [ ] Legion;
- [ ] Myriad;
- [ ] Thomas.

**Comment by owainkenwayucl** [comment]
OK - gonna take a pass at this.

**Comment by owainkenwayucl** [comment]
```
Name "PHONEHOME_SEND_USAGE_DATA" is not valid
/home/ccspapp/temporary-intel-dirs/intel-build.VyXR019Fkq/./silent_config_file.cfg has errors
```

Yay.

I bet there's literally no documentation for what it's changed to either.

**Comment by owainkenwayucl** [comment]
The documentation is a PDF because of course it is.

**Comment by owainkenwayucl** [comment]
Mostly dealing with Legion complexities at the moment.

**Comment by owainkenwayucl** [comment]
See here: https://github.com/UCL-RITS/rcps-buildscripts/commit/64c93f21049945359f3179ad6afcad7d70c0a26d

**Comment by heatherkellyucl** [comment]
It does fix the NAMD case - boundary box no longer expanding past 59 Angstroms.

**Comment by owainkenwayucl** [comment]
OK, I beleive I successfully have CESM working with Intel 2018 on Myriad so I'm pushing out those changes on the other services.

**Comment by ikirker** [comment]
We told them we were going to switch at the end of July, so remind users on Monday to give warning.

**Comment by owainkenwayucl** [comment]
This is now done and we've moved so closing.
