### ISSUE TITLE
Install request: Sambamba (IN03007031)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#172]
Install:

http://lomereiter.github.io/sambamba/

on Legion.

**Comment by balston** [comment]
User also needs:

samblaster (https://github.com/GregoryFaust/samblaster) [IN03017152]

as part of the same workflow.

**Comment by ikirker** [comment]
Given that the options for Sambamba are either:

 - install the binary release, a single statically-compiled executable

or

 - install a D compiler with a bunch of D libraries and then compile Sambamba

installing the executable seems like the sensible choice.

samblaster comes as C++ and looks fairly simple to compile. (It's only a couple of files and doesn't seem to have any dependencies outside libm and libstdc++.)

**Comment by ikirker** [comment]
Installed both Sambamba and samblaster everywhere:

```
$ module av samb

--------------------- /shared/ucl/apps/modulefiles/applications ---------------------
sambamba/0.6.7-bindist      samblaster/0.1.24/gnu-4.9.2
```

**Comment by ikirker** [comment]
Notified user.
