### ISSUE TITLE
Install Request: HDF5 with Intel 2018 compilers

### ISSUE THREAD

**Issue by utf** [UCL-RITS/rcps-buildscripts#176]
Please can you add a package for HDF5 compiled using the intel 2017 compilers (for both the default and impi version).

Thanks.

**Comment by heatherkellyucl** [comment]
Why is this needed?

`hdf/5-1.8.15/intel-2015-update2` and `hdf/5-1.8.15-p1-impi/intel-2015-update2` only require `compilers/intel` so should be usable with both 2015 and 2017.

On the whole we are trying not to build anything else with Intel 2017 as there are various issues with that compiler, and moving to 2018 as soon as we can.

**Comment by utf** [comment]
The reason why I originally suspected that HDF5 compiled with the 2015 version of the intel compilers might be to blame is the error message I'm getting:

```
ifort -fpp -qopenmp -DGPwxt -Dclusterprogressbar -DAGRESSIVE_SANITY -L../../lib -L/shared/ucl/apps/intel/2017.Update1/compilers_and_libraries_2017.1.132/linux/mkl/lib/intel64 -L/shared/ucl/apps/HDF/5-1.8.15-Intel_2015/lib -L/shared/ucl/apps/intel/2017.Update1/compilers_and_libraries_2017.1.132/linux/mpi/intel64/lib -I../../inc/libolle -I../../inc/libflap -I/shared/ucl/apps/intel/2017.Update1/compilers_and_libraries_2017.1.132/linux/mkl/include -I/shared/ucl/apps/HDF/5-1.8.15-Intel_2015/include -I/shared/ucl/apps/intel/2017.Update1/compilers_and_libraries_2017.1.132/linux/mpi/intel64/include -module ../../build/small_hello_world/  -o ../../build/small_hello_world/small_hello_world ../../build/small_hello_world/main.o -lolle -lflap -lpthread -lmkl_sequential -lmkl_intel_lp64 -lmkl_core -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lhdf5 -lhdf5_fortran -lmpi -lmpifort
/shared/ucl/apps/intel/2017.Update1/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64/libifport.so.5: undefined reference to `for_ifcore_version'
```

(This is when I try and use the 2017 compilers)

According to [1], the `for_ifcore_version` routine was added in the 2016 compilers:
https://software.intel.com/en-us/forums/intel-fortran-compiler-for-linux-and-mac-os-x/topic/590325

**Comment by utf** [comment]
Ok, I successfully compiled HDF5 using the intel 2017 compilers and this fixed my issue compiling the other package mentioned above.

As I know several other users who want to compile the other package, would it be possible to have HDF5 compiled using the 2017 compilers still?

**Comment by heatherkellyucl** [comment]
We won't be building it with 2017, but we can build versions with 2018. The plan is to make 2018 the default compiler and mpi once we have checked things work.

I'll update the issue title so we can see.

**Comment by heatherkellyucl** [comment]
`hdf/5-1.10.2/intel-2018` was built at some point. We don't have an impi version yet.

**Comment by owainkenwayucl** [comment]
Right - I seem to have this building and passing its tests.

Just rolling out across the services.

**Comment by owainkenwayucl** [comment]
@utf: this is now done.

**Comment by utf** [comment]
Great, thanks!
