### ISSUE TITLE
Update StarCCM+ to 13.02.011-R8 (IN:03031875)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#181]
I presume whoever does this needs to a) check that mecheng have a license and then b) get binaries from them.

**Comment by balston** [comment]
I've emailed Mech Eng asking for the installer if their license covers this version.

**Comment by balston** [comment]
I have received the following response from Mech Eng:

> Hi Brian,
> 
> I have looked at the release notes and there is no suggestion that the license server needs upgrading so we should be fine.
> 
> Do you have somewhere to upload the files, or should I just send a usb stick through the internal post?
> 
> 
> Regards,
> 
> 
> David Bevan
> Asst. IT manager
> UCL, Mechanical Engineering
> Torrington Place
> London, WC1E 7JE
> 
> http://www.mecheng.ucl.ac.uk/
>

**Comment by balston** [comment]
My reply:

> Hi David,
> 
> If you have a Legion account, you could leave the file in your Scratch directory, otherwise please upload the installer to the UCL Dropbox (https://www.ucl.ac.uk/dropbox/) for me to collect. Thanks,
> 
> Brian

**Comment by balston** [comment]
I now have been given the installer via the UCL Dropbox.

Staring installation on Grace.

**Comment by balston** [comment]
tar archive copied to:
```
~ccaabaa/Software/STAR-CCM+/STAR-CCM+13.02.011_01_linux-x86_64.tar.gz
```
As ccspapp:
```
cd Software/STAR-CCM+
tar xvzf ~ccaabaa/Software/STAR-CCM+/STAR-CCM+13.02.011_01_linux-x86_64.tar.gz
cd starccm+_13.02.011
./STAR-CCM+13.02.011_01_linux-x86_64-2.12_gnu6.2.sh
```
Settings used in the GUI:

1. Installation method: Custom as we do not need to install the license manager but point to the Mech Eng one.

1. Choose Install type: unselect the license manager.

1. Choose STAR-CCM+ Components: make sure all are selected.

1. Select Install Location: /shared/ucl/apps/STAR-CCM+/13.02.011/

1. Select additional tasks: unselect Add applications directlry to system PATH.

**Comment by balston** [comment]
Installation is progressing ...

**Comment by balston** [comment]
Change file ownership as STAR-CCM+ is a reserved application.
```
cd /shared/ucl/apps/STAR-CCM+/13.02.011
# chgrp -R legstarc *
chmod -R o-rwx *
```
Next step is to produce a module file and test.

**Comment by balston** [comment]
First test job with the default IBM Platform MPI has worked successfully. This is using the simple airfoil supplied example.

**Comment by balston** [comment]
The same test simulation is now also working with the supplied Intel MPI. Our default Intel MPI module needs to be unloaded first as it causes a clash and job failure.

**Comment by balston** [comment]
Running a longer test simulation now.

**Comment by balston** [comment]
This test ran out of time after 1 hour. Re-submitted with 15 hours. Using the default MPI for this one.

**Comment by balston** [comment]
I've also submitted an Intel MPI long test as well. Both using _Jet1.sim_.

**Comment by balston** [comment]
Long test with Platform MPI (default) ran out of wallclock time after 15 hours.

**Comment by balston** [comment]
Beginning install on Legion. 

Fixing long Intel MPI test on Grace.

**Comment by balston** [comment]
STAR-CCM+ 13.02.011 installed and tested on:
- [ ] Grace;
- [ ] Legion;
- [ ] Myriad

**Comment by balston** [comment]
Interestingly the long test simulation with Intel MPI  fails after about 3.25 hours with:
```
A floating point exception has occurred: floating point exception [Overflow].  The specific cause cannot be identified.  Please refer to the troubleshooting section of the User's Guide.
Context: star.segregatedenergy.SegregatedEnergySolver
Command: RunSimulation
   error: Server Error
A floating point exception has occurred: floating point exception [Overflow].  The specific cause cannot be identified.  Please refer to the troubleshooting section of the User's Guide.
Context: star.segregatedenergy.SegregatedEnergySolver
Command: RunSimulation
   command: CommandComplete
   error: Server Error

Auto save: /home/ccaabaa/Scratch/STAR-CCM+_examples/13.02.011_IntelMPI/Jet1@28607.sim
Saving: /home/ccaabaa/Scratch/STAR-CCM+_examples/13.02.011_IntelMPI/Jet1@28607.sim
Object state saved to /home/ccaabaa/Scratch/STAR-CCM+_examples/13.02.011_IntelMPI/Jet1@28607.sim (441MB in 1.4623s).
Design STAR-CCM+ simulation completed
Server process exited with code : 16
```
The same simulation run with IBM Platform MPI works and has been running in two stages for 30 hours without errors.

The version of Intel MPI supplied with STAR-CCM+ is 2017 update 2. This is one of the versions with known problems so don't run STAR-CCM+ with Intel MPI.

**Comment by balston** [comment]
Short test runs fine on Legion across 2 X Nodes.

**Comment by balston** [comment]
I've submitted the long test and it has started running.

I've emailed the user.

**Comment by balston** [comment]
Long test on Legion ran for full wallclock time without errors.

**Comment by balston** [comment]
Short test (32 cores) runs fine on Myriad. Submitted long test job.

**Comment by balston** [comment]
Long test ran for full wallclock time on Myriad without errors.

All Done.

**Comment by balston** [comment]
I've also told IN03031875 about this version.
