### ISSUE TITLE
Install request: FFTW 3 with Intel MPI 2018

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#182]
IN:03016935

Intel 2018 version of `fftw/3.3.4-impi/intel-2017-update1` wanted to see if 2018 toolchain fixes hanging issue with particular code on Thomas.

**Comment by ikirker** [comment]
3.3.4 exactly, or just any FFTW3?

**Comment by heatherkellyucl** [comment]
It sounded like any fftw 3. (It is for https://wiki.fysik.dtu.dk/ase/ so it is hard to tell)

**Comment by smujahed** [comment]
@heatherkellyucl @ikirker In relation to my very specific case, FFTW 3 (any version). We have used 3.3.4 and we haven't seen any issues. FFTW in my case is for CONQUEST (http://www.order-n.org/). Apologies, I would link to our Git but repository is private (for now..).

**Comment by ikirker** [comment]
I've written the script for the installation, I'll install it on the clusters next week.

**Comment by ikirker** [comment]
Hm, this is more complicated than I thought.

**Comment by ikirker** [comment]
Installed on all clusters.
