### ISSUE TITLE
Install request: serial OpenBLAS (performance reasons)

### ISSUE THREAD

**Issue by Majokux** [UCL-RITS/rcps-buildscripts#184]
There are 3 different OpenBLAS versions available on thomas, namely
1. openblas/0.2.14/gnu-4.9.2
2. openblas/0.2.14/intel-2015-update2
3. openblas/0.2.14-threads/gnu-4.9.2

I do not understand the difference between 1. and 3., since - after linking to them - in both cases
openblas_get_parallel() returns 1, i.e. pthread parallelization. Since my application is already OpenMP parallelized, I would much rather link to a serial version of OpenBLAS (i.e. make with USE_THREAD=0).
Others would probably like an OpenMP version, i.e. make with USE_OPENMP=1.

Is it possible to add these?

**Comment by heatherkellyucl** [comment]
Does it work to put `export OPENBLAS_NUM_THREADS=1` in your jobscript when running your application? (https://wiki.rc.ucl.ac.uk/wiki/OpenBLAS_on_Legion)

It tells OpenBLAS to only use one thread, separate from OMP_NUM_THREADS.

`openblas/0.2.14-threads/gnu-4.9.2` was built with USE_OPENMP=1 and the others weren't. It links libgomp where the other versions don't, but they all link libpthread.

**Comment by Majokux** [comment]
You are right - `openblas/0.2.14-threads/gnu-4.9.2` returns does 2 when calling `openblas_get_parallel()`, my initial statement was false.

Unfortunately, I still get much worse performance when linking to the OpenMP OpenBLAS than when I'm linking to my own serial built, even when I `export OPENBLAS_NUM_THREADS=1`.
I wrote a minimal example test program (here: 
[openblas_parallel_test.zip](https://github.com/UCL-RITS/rcps-buildscripts/files/2201854/openblas_parallel_test.zip)), that runs multiple `cblas_dgemm`s in a OpenMP parallel enviroment. With a loop size of 128, Matrix sizes of 512 and 24 threads the version linking to the parallel OpenBLAS built takes ~2.6 times as long.

**Comment by heatherkellyucl** [comment]
It sounds reasonable to have a serial install in that case. (It'll take a while to get to, but we'll leave this open as an install request).

**Comment by heatherkellyucl** [comment]
This was done, it seems.

We have these for 0.3.2
```
openblas/0.3.2-native-threads/gnu-4.9.2
openblas/0.3.2-openmp/gnu-4.9.2
openblas/0.3.2-serial/gnu-4.9.2
```

**Comment by owainkenwayucl** [comment]
OK, this is now definitely done (we had to fiddle some of the build options for the serial version.

Closing
