### ISSUE TITLE
Install request: GROMACS with Plumed 2.2

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#19]
Currently we have Plumed 2.1.2

IN00804561

**Comment by owainkenwayucl** [comment]
OK, the checksum appears to be 829f6c584b4448f9628b45b78a23b32e for version 2.2.

```none
VERSION=2.2 MD5=829f6c584b4448f9628b45b78a23b32e ./plumed-2.1.2_install
```

Appears to have worked, and I've put in place a module.

**Comment by owainkenwayucl** [comment]
Right.  Plumed 2.2 doesn't know about GROMACS 5.1.1.  I'm telling it that it's 5.1.0.  Let's see what happens.

**Comment by owainkenwayucl** [comment]
Well it seems to be compiling.

**Comment by owainkenwayucl** [comment]
```none
VERSION=5.1.1 MD5=5c075141aa69dc4859cad0a55e61d35e CMAKE_FLAGS=-DCMAKE_LINKER=icc ./gromacs-5.0.4-plumed_install
```

Seems to have worked.  Putting in module file now.

**Comment by owainkenwayucl** [comment]
And the module file is in.
