### ISSUE TITLE
Current GROMACS does not have working gmx view

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#20]
IN00824302

Looks like it was missing some parts of X11 when compiled, so trying to run gmx view gives
```
Compiled without X-Windows - can not run viewer.
```

**Comment by heatherkellyucl** [comment]
Gromacs 5.1.1 is out, so I may as well do that one and then build with plumed for #19

**Comment by heatherkellyucl** [comment]
cmake output doesn't mention anything about X11 either way... But it looks like the relevant flag is `-DGMX_X11=ON`

**Comment by heatherkellyucl** [comment]
`VERSION=5.1.1 MD5=5c075141aa69dc4859cad0a55e61d35e ./gromacs-5.0.4_install`

Building new one with gmx view for the serial versions.

**Comment by heatherkellyucl** [comment]
Something's changed in the config between 5.0.4 and now - with the same flags, it fails at the final linking stage not finding parts of the Intel compiler libraries.
```
Linking CXX executable ../../bin/template
ld: warning: libimf.so, needed by ../../lib/libgromacs.so.1.1.0, not found (try using -rpath or -rpath-link)
ld: warning: libsvml.so, needed by ../../lib/libgromacs.so.1.1.0, not found (try using -rpath or -rpath-link)
ld: warning: libirng.so, needed by ../../lib/libgromacs.so.1.1.0, not found (try using -rpath or -rpath-link)
ld: warning: libintlc.so.5, needed by ../../lib/libgromacs.so.1.1.0, not found (try using -rpath or -rpath-link)
ld: ../../bin/template: hidden symbol `__intel_cpu_features_init_x' in /shared/ucl/apps/intel/2015/composer_xe_2015.2.164/compiler/lib/intel64/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Bad value
make[2]: *** [bin/template] Error 1
make[1]: *** [share/template/CMakeFiles/template.dir/all] Error 2
make: *** [all] Error 2
```

Setting `-DCMAKE_LINKER=icc` instead of ld works.

**Comment by heatherkellyucl** [comment]
Going again as
`VERSION=5.1.1 MD5=5c075141aa69dc4859cad0a55e61d35e CMAKE_FLAGS=-DCMAKE_LINKER=icc ./gromacs-5.0.4_install`

**Comment by owainkenwayucl** [comment]
I've put in a module for 5.1.1.

I'm going to try an install with plumed.
