### ISSUE TITLE
ChemShell (for MCC workshop Sept 3rd)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#201]
IN:03147043

ChemShell will need restricted access after the workshop. 

> As the ChemShell licence manager I'm happy for all attendees to have access to ChemShell for the duration of the workshop. A temporary shared directory would be sufficient for this, although it would also be good to make ChemShell available as a module on Thomas for general use, but this would need to have access restricted to registered users only after the workshop.
>
> I'd recommend Intel 2018 and Intel MPI for compilation, and to build Tcl (8.5) from scratch for ChemShell. This should be sufficient for running the most basic tutorials. If GULP and GAMESS-UK can be installed we could also run the advanced tutorials (although I doubt there will be time). I can help with the compilation if needed.
>
> Kind regards,
>
> Tom

I confirmed that we can give non-UCL Thomas users access to the central install. We will need to email for confirmation before adding anyone to the restricted application group.

> Providing they are ChemShell licence holders anyone can have access. We licence ChemShell to individual research groups so this would need to be confirmed on a case-by-case basis (this applies to both UCL and non-UCL groups). On ARCHER this works by users contacting the helpdesk for access, who in turn check with us that the user has a licence before granting access to the ChemShell module. This is a bit fiddly but it works OK in practice.
> 
>  (NB: longer term we will transition to the new open source "Py-ChemShell" package which will not be restricted in this way, but the current "Tcl-ChemShell" is a proprietary code)
> 
> Hope that make sense,
>  
> Tom

**Comment by heatherkellyucl** [comment]
Doing a test Tcl/Tk 8.6.8 build.

**Comment by heatherkellyucl** [comment]
No failed tests.
```
Tests ended at Tue Aug 21 16:21:45 BST 2018
all.tcl:        Total   136     Passed  120     Skipped 16      Failed  0
Sourced 0 Test Files.
Number of tests skipped for each constraint:
        8       have_gdbm
        8       have_lmdb
```

**Comment by heatherkellyucl** [comment]
Tcl built on
- [ ] Thomas
- [ ] Grace
- [ ] Myriad
- [ ] Legion
- [ ] modulefile

**Comment by heatherkellyucl** [comment]
Serial standalone ChemShell
- [ ] Thomas
- [ ] Grace
- [ ] Myriad
- [ ] Legion
- [ ] modulefile

**Comment by heatherkellyucl** [comment]
Tests for the standalone:
```
Failures: 0      Passes: 71      Unsupported: 154        Unknown: 7
```
Unknown are ones without criteria - they 'pass' if they don't crash. The unsupported are all from other programs not being in the path (NWChem, GAMESS_UK, GULP etc).

I ran again with the GULP module loaded:
```
Failures: 0      Passes: 84      Unsupported: 141        Unknown: 7
```

**Comment by heatherkellyucl** [comment]
Building libgulp version #200

**Comment by heatherkellyucl** [comment]
Did a test build of ChemShell MPI+libgulp version. Ran the parallel test suite on 4 cores.
```
Pass 59 Fail 0 Unsupported 19 Other 7
```

**Comment by heatherkellyucl** [comment]
ChemShell MPI+libgulp
- [ ] Thomas
- [ ] Grace
- [ ] Myriad
- [ ] Legion
- [ ] modulefile (again not yet)

Build on the other clusters when restricted group set up.

**Comment by balston** [comment]
I'm setting up the reserved application group for ChemShell: _lgchemsh_

**Comment by balston** [comment]
ccspap2 is now in the _lgchemsh_ group. Should now be OK to proceed with installation on other clusters.

**Comment by heatherkellyucl** [comment]
Now restricted on Thomas.

**Comment by heatherkellyucl** [comment]
RITS-signed license was sent in and accepted.

**Comment by heatherkellyucl** [comment]
Info about how to give people access added to Licensed Software Licensing requirements page.
