### ISSUE TITLE
FHI-aims [IN:04019907]

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#203]
IN:03147043

UCL still has a 5 person license valid until 22 Oct 2023 (only used on IRIDIS), so even if we don't get this done in time for the workshop, we should probably install it anyway.

Have asked if we can get a copy of the code (as Robert Silk would need to sign up for aimsclub to get it) and if we can have an unrestricted install during the workshop.

**Comment by balston** [comment]
We now have a request [IN:04019907] to install FHI-aims on Grace so this now needs to be done as a reserved application.
