### ISSUE TITLE
OpenMolcas: Install on Thomas [IN03166549]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#204]
Request to install OpenMolcas on Thomas:

https://gitlab.com/Molcas/OpenMolcas

User offered "our internal notes for installation".

**Comment by balston** [comment]
Requested a copy of their  "internal notes for installation".

**Comment by sbutcher** [comment]
OpenMolcas notes for our Tier3..YMMV

### Download

    download the source from https://gitlab.com/Molcas/OpenMolcas.git
    cd into the OpenMolcas directory 

Prepare the environment

    Create the /share/apps/centos7/openmolcas/VER where VER is the version to OpenMolcas to be installed (i.e. 18.0) and chown to you
    Change directory to /share/apps/centos7/openmolcas/VER
    Load the 'python/3.6.3' module
    Create a python virtual environment: 'virtualenv -p `which python3` --include-lib venv'
    Unload the python module (otherwise the OpenMolcas compile will fail)
    Source the virtual environment: 'source venv/bin/activate'
    Install OpenMolcas test dependencies: 'pip install six pyparsing' 

### Compile

    Load the following modules: 'ga/5.7 cmake/3.8.0 intel/2018.1 intelmpi/2018.1'
    Create a build directory 'build' and cd into it

          mkdir build && cd build
          

    Run cmake enabling the Intel MKL and GA libraries and MPI:

          cmake -DCMAKE_INSTALL_PREFIX=/share/apps/centos7/openmolcas/VER -DLINALG=MKL -DMPI=on -DGA=on ..
          

    Compile the application (it may take a while)

          make -j ${NSLOTS}
          

### Verify Compilation and Run Tests

    Run the verifier:

          pymolcas verify
          

The full verification suite can take around 2 hours to complete. You can run a basic subset with 'pymolcas verify .basic' Run pymolcas verify --help to see more options.

Tests marked as "skipped" could not be completed because some necessary feature for that particular test is missing in your installation. Tests marked as "failed" did not finish for some other reason or produced results too different from the reference values, and they should be checked. Failed tests with a grayzone:* name are known to be problematic and can be ignored.

### Installation

    Install the binaries:

          make install
          

    Chown the directory to root

           sudo chown -R /share/apps/centos7/openmolcas/VER/
           

### Module file

Add the virtualenv commands to the modulefile:


    if { [ module-info mode remove ] } {
        puts stdout "deactivate;"
    }

    if { [ module-info mode load ] } {
        puts stdout ". /share/apps/centos7/openmolcas/XX.Y/venv/bin/activate;"
    }

**Comment by ikirker** [comment]
Trying to build Global Arrays for this, which we don't seem to currently have installed (surprisingly?).

Fails `make check` tests with:
```
FAIL: testing/perf
lt-perf: testing/perf.c:42: main: Assertion `nproc == 2' failed.
```
and altering the test code shows that `nproc` in fact equals 1, which suggests it isn't running MPI code properly, despite being told how to with the `MPIEXEC` makefile variable.

Running the GA test subset with `make check-ga` also fails for reasons that are not clear.

**Comment by ikirker** [comment]
Okay, the ComEx tests in Global Arrays seem broken in a way that I'm not sure how to fix, and in such a way that I'm not sure how this ever worked for anyone.

**Comment by ikirker** [comment]
https://github.com/UCL-RITS/rcps-buildscripts/commit/b1ec9a4f51d97b0b462fad2803af6588f3043fbd

**Comment by ikirker** [comment]
libwfa could probably be included for some extra analysis options, but it has a few dependencies we don't have rebuilt with Intel 2018 yet. (Armadillo, SuperLU, ARPACK-NG.)

So far:
```
module purge
module load gcc-libs/4.9.2
module load compilers/intel/2018/update3
module load mpi/intel/2018/update3/intel
module load hdf/5-1.10.2/intel-2018
module load python3/recommended
module load cmake
git clone https://gitlab.com/Molcas/OpenMolcas.git
export GAROOT=/shared/ucl/apps/ga/5.7/intel-2018
cd OpenMolcas
git submodule update --init External/{efp,grid_it,libmsym}
mkdir build
cd build
cmake -DLINALG=MKL -DGA=ON -DMPI=ON -DBUILD_SHARED_LIBS=ON -DBUILD_STATIC_LIB=ON -DGRID_IT=ON -DTOOLS=ON ../
```

**Comment by ikirker** [comment]
EFP inherits Molcas's CMake config options, and assumes that `BUILD_SHARED_LIBS` and `BUILD_STATIC_LIB` conflict, so if you have `BUILD_SHARED_LIBS=ON` and `BUILD_STATIC_LIB=ON` and `EFP=ON`, you'll get this error:

```
[ 35%] Building Fortran object CMakeFiles/integral_util_obj.dir/src/integral_util/drvefp.f.o
/tmp/molcas-build.aiwETny/OpenMolcas/src/integral_util/drvefp.f(14): error #6406: Conflicting attributes or multiple declaration of name.   [EFP]
      use EFP
----------^
compilation aborted for /tmp/molcas-build.aiwETny/OpenMolcas/src/integral_util/drvefp.f (code 1)
```

Accordingly, removing the static lib building.

----

**NB:** The build process drops the `pymolcas` script *somewhere* in your `PATH`. For me it was in `~/bin`, but I've not looked at the code that does it and the manual doesn't specify. The build script is going to have to clear that up.

----

Well, it builds, but all the tests fail, for lack of some `rc.global` file that is apparently missing.

**Comment by ikirker** [comment]
Left an [issue on the OpenMolcas Gitlab about it](https://gitlab.com/Molcas/OpenMolcas/issues/69), since I couldn't work out why it was missing or where it should come from.

**Comment by ikirker** [comment]
So, *something* between Molcas, GA, MKL, glibc, and MPI, causing segfaulting during linking. This is... Painful.

I'm trying to build a version just using OpenMP at the moment as an interim, so now instead I'm stuck on trying to put `pymolcas` in a sensible place. :tired_face:
