### ISSUE TITLE
Install request: singularity as a user service [IN03167234]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#205]
singularity is currently being tested as part of the Xpra istallation #186

**Comment by ikirker** [comment]
It's already usable by users on Myriad. They can't build their own containers on Myriad (or any of our clusters), though, since that requires root/sudo permissions. They can pull containers from Singularity Hub or Docker Hub or build their own on their own machines, though.

**Comment by balston** [comment]
The users have solved their issues with the NextFlow workflow using the following change to its config file:
```
process.beforeScript = 'source $HOME/.bashrc'
```
(See issue here: https://github.com/nextflow-io/nextflow/issues/850#issuecomment-417237243)

Hence this is no longer urgent.

**Comment by ikirker** [comment]
Singularity 2.5.2 is installed on Myriad and Grace, on both login and compute nodes.

**Comment by lconde-ucl** [comment]
Hi, is it possible to install singularity in legion too? There are some nextflow pipelines that we are very interested in that can only be installed via singularity (for example https://github.com/SciLifeLab/Sarek).

**Comment by heatherkellyucl** [comment]
Also requested on Thomas (add to Michael too).

**Comment by ikirker** [comment]
@lconde-ucl It's now installed on Legion.

**Comment by ikirker** [comment]
- [ ] Add Scratch and Shared to default binds

**Comment by heatherkellyucl** [comment]
Just confirming: Singularity is indeed available on Legion, Grace, Myriad, Thomas and Michael.

**Comment by heatherkellyucl** [comment]
In the meantime, to bind Scratch you can do:
```
singularity shell -B /scratch/scratch/uccaxxx
```
or for a job you can add this to your jobscript:
```
export SINGULARITY_BINDPATH=/scratch/scratch/uccaxxx
```
where you replace `uccaxxx` with your username. See https://www.sylabs.io/guides/2.5/user-guide/bind_paths_and_mounts.html#user-defined-bind-points

**Comment by heatherkellyucl** [comment]
From that same link, when pulling images it can also get write fail errors because /tmp is full, so set all the locations mentioned to somewhere in Scratch:
```bash
# Set all the Singularity cache dirs to Scratch
export SINGULARITY_CACHEDIR=/home/uccaxxx/Scratch/.singularity/
export SINGULARITY_TMPDIR=/home/uccaxxx/Scratch/.singularity/tmp
export SINGULARITY_LOCALCACHEDIR=/home/uccaxxx/Scratch/.singularity/localcache
export SINGULARITY_PULLFOLDER=/home/uccaxxx/Scratch/.singularity/pull
# Bind your Scratch directory so it is accessible from inside the container
export SINGULARITY_BINDPATH=/scratch/scratch/uccaxxx
```
I put different subdirectories for each so you can tell which files came from where.

**Comment by heatherkellyucl** [comment]
Changes to the image, including Singularity - do we need to put any of the above settings in? https://github.com/UCL-RITS/rhel-install/issues/101

**Comment by ikirker** [comment]
- [ ] Have a look at the Singularity documentation and see if you can put the cache locations in the same config place as the default binds

**Comment by ikirker** [comment]
Closing this. We now have Singularity installed and usable on all clusters, though you still can't build images on the cluster itself.
