### ISSUE TITLE
MAGMA (for CUDA)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#206]
IN:03176274

http://icl.cs.utk.edu/magma/software/
http://icl.cs.utk.edu/projectsfiles/magma/doxygen/installing.html

CUDA and MKL, needs building on a GPU node.

**Comment by owainkenwayucl** [comment]
In the intervening time they have released 1.11.0.

**Comment by owainkenwayucl** [comment]
I've installed this on Legion and Myriad, using GCC to build it but having the Intel Compiler modules loaded for MKL.
