### ISSUE TITLE
Seaborn package for Python3

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#208]
IN:03186804

> Seaborn is a library for making statistical graphics in Python. It is built on top of matplotlib and closely integrated with pandas data structures.

https://pypi.org/project/seaborn/

Appears to be available for python 2 and 3.

**Comment by owainkenwayucl** [comment]
(Using this as an excuse to do a full update of the packages in python3/recommended)

**Comment by owainkenwayucl** [comment]
User contacted.
