### ISSUE TITLE
Siesta 4.1 [IN03186548]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#209]
Update Siesta to version 4.1:

https://launchpad.net/siesta

**Comment by balston** [comment]
User has done own build. Their Makefile and arch.make file are attached.
- [Makefile.txt](https://github.com/UCL-RITS/rcps-buildscripts/files/2366794/Makefile.txt)
- 
[arch.make.txt](https://github.com/UCL-RITS/rcps-buildscripts/files/2366796/arch.make.txt)

**Comment by owainkenwayucl** [comment]
See #153

**Comment by heatherkellyucl** [comment]
Hmm, the 4.1 series is still in beta. Could do 4.0.2 release for the #153 issue.
