### ISSUE TITLE
Install request: Variant Effect Predictor (VEP)

### ISSUE THREAD

**Issue by skgttjo** [UCL-RITS/rcps-buildscripts#211]
Please may you install VEP on legion ?
https://www.ensembl.org/info/docs/tools/vep/index.html 

Many thanks

**Comment by heatherkellyucl** [comment]
We have a second request for this, IN:03332906

https://www.ensembl.org/info/docs/tools/vep/script/vep_download.html

It uses BioPerl. We have some of that installed already in `perl/5.22.0` so it may work using that as a prereq.

**Comment by owainkenwayucl** [comment]
This is now installed on Myriad (without plugins, reference data, users should set up a cache themselves as per the manual).

You will need to load the `perl/5.22.0` and `vep/95.0` module to use it.

Other systems are building as I type and should be available shortly.
