### ISSUE TITLE
Myriad requests: bgenie, bgenix, snptest

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#213]
IN:03233107

bgenie - https://jmarchini.org/bgenie/

bgenix - https://bitbucket.org/gavinband/bgen/wiki/bgenix

snptest (v2.5.2) - https://mathgen.stats.ox.ac.uk/genetics_software/snptest/snptest.html

(We already have `qctool/2/beta/ba5eaa44a62f` installed).

**Comment by owainkenwayucl** [comment]
So for snptest, the "stable" version 404s.

Guess we are going beta.

**Comment by owainkenwayucl** [comment]
SNPtest installed.

**Comment by owainkenwayucl** [comment]
Right, by bgenix they presumably mean bgen of which bgenix is part.

**Comment by owainkenwayucl** [comment]
Bgen 1.1.4 installed everywhere.

**Comment by owainkenwayucl** [comment]
Licensing for bgenie is more complicated so I've sent an email asking for a clarification.

**Comment by owainkenwayucl** [comment]
OK - I have written permission to install bgenie.

**Comment by owainkenwayucl** [comment]
OK, I can't get the bgenie form to submit.

**Comment by yayuanchen** [comment]
> IN:03233107
> 
> bgenie - https://jmarchini.org/bgenie/
> 
> bgenix - https://bitbucket.org/gavinband/bgen/wiki/bgenix
> 
> snptest (v2.5.2) - https://mathgen.stats.ox.ac.uk/genetics_software/snptest/snptest.html
> 
> (We already have `qctool/2/beta/ba5eaa44a62f` installed).



> IN:03233107
> 
> bgenie - https://jmarchini.org/bgenie/
> 
> bgenix - https://bitbucket.org/gavinband/bgen/wiki/bgenix
> 
> snptest (v2.5.2) - https://mathgen.stats.ox.ac.uk/genetics_software/snptest/snptest.html
> 
> (We already have `qctool/2/beta/ba5eaa44a62f` installed).

Hi!  I am trying to install BGENIE  from https://jmarchini.org/bgenie/,  when i click [Software] button at https://jmarchini.org/software/#bgenie to jump to the install pack, it showed that the file is not exist. Is something wrong there? Please let me know, Thank you very much!!

**Comment by heatherkellyucl** [comment]
@yayuanchen You will need to ask the maintainer of the software, which is not us. The link appears to be on Dropbox.
