### ISSUE TITLE
Boost/1_63_0 install dir and module root dir mismatch?

### ISSUE THREAD

**Issue by tcouch** [UCL-RITS/rcps-buildscripts#215]
I've just built Boost/1_63_0/gnu-4.9.2 on the rstudio server using the boost_1.63.0_install script, which puts boost here: /shared/ucl/apps/boost/1_63_0/gnu-4.9.2/

module load boost/1_63_0/gnu-4.9.2 sets these two env variables though:
BOOSTROOT=/shared/ucl/apps/boost/1_63_0/nompi/gnu-4.9.2
BOOST_ROOT=/shared/ucl/apps/boost/1_63_0/nompi/gnu-4.9.2

**Comment by balston** [comment]
Needs:
```
module unload compilers
module load compilers/gnu/4.9.2
MPI=no ./boost_1.63.0_install
```
for GNU non MPI version.
