### ISSUE TITLE
Install latest version of DFTB+ (18.2) [IN03250411]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#217]
Install DFTB+ 18.2 on Thomas and Grace from http://www.dftbplus.org

**Comment by ikirker** [comment]
Installed on Thomas, Grace, Myriad, Legion.

**Comment by ikirker** [comment]
NB: Testing threw up a warning that there's maybe one algorithm that isn't implemented in the MPI version. If this is something the requester wanted, it might be necessary to compile a separate serial version.

As is:
```
module purge
module load gcc-libs/4.9.2
module load compilers/intel/2018/update3
module load mpi/intel/2018/update3
module load python2/recommended
module load gerun
gerun dftb+
```

It can also use hybrid MPI/OpenMP, which could potentially cause problems.

**Comment by ikirker** [comment]
(Check user was informed)

**Comment by ikirker** [comment]
Have notified user, with apologies.
