### ISSUE TITLE
errors in blast+-2.2.30_install

### ISSUE THREAD

**Issue by TizianoGC** [UCL-RITS/rcps-buildscripts#22]
Blast+ in not installed due to two errors; the following line has a typo (VERSION) and does not point to $VERSION

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/ncbi-blast-$(VERSION)+-src.tar.gz

so it should be changed to 

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/${VERSION}/ncbi-blast-${VERSION}+-src.tar.gz

Also, "../configure" should be "./configure" (configure is in the current dir)

These fixes are available in the fork ICONIC-UCL/rcps-buildscripts

**Comment by heatherkellyucl** [comment]
Made changes. The LATEST directory naturally points to the latest version only, so shouldn't be used when choosing versions.
