### ISSUE TITLE
AFNI 18.2.19 

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#220]
IN:03275127
Request for an install of current AFNI version, containing 3dDegreecentrality.

Current version number is shown on main page https://afni.nimh.nih.gov/
https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/background_install/download_links.html#to-download-the-afni-source-code

**Comment by owainkenwayucl** [comment]
Doing a quick update of AFNI to current version.

**Comment by owainkenwayucl** [comment]
Installed, contacted user.
