### ISSUE TITLE
eddy_openmp for FSL

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#222]
IN:03268772

eddy is covered by the normal FSL license but is only distributed as binaries. I installed it alongside Myriad's FSL for testing. If it seems to be working correctly with both versions of FSL, it needs to be included in the buildscripts.

> I have put the 5.0.9 eddy_openmp binary alongside the other binaries for FSL 5.0.9 and 5.0.10 (as they don't provide one for 5.0.10). You will have eddy_openmp in your path when you load either FSL module on Myriad now. Can you test and see if it does what it is supposed to when used alongside the rest of FSL?

Binaries are in FSL's patches location, https://fsl.fmrib.ox.ac.uk/fsldownloads/patches/ (Note they have one for 5.0.9 and 5.0.11).

There are also CUDA versions: eddy_cuda7.5.

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy/UsersGuide
https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/eddy

**Comment by balston** [comment]
There doesn't appear to be a new version of eddy for FSL 6 at the moment but there is the following comment in the release notes:

> The version of eddy is the same as in 5.0.11. A new version of eddy will be released with FSL 6.0.1

**Comment by balston** [comment]
_eddy_openmp_ now installed with FSL 6.0.

**Comment by balston** [comment]
All done?
