### ISSUE TITLE
Intel 2019 Compilers

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#224]
We have issues with the 2018 compilers, some of which Intel claim may be resolved in 2019.

So we have to:

1) Install the 2019 compilers.
2) If they resolve our issues go through the whole testing and migrating users rigmarole all over again.

**Comment by heatherkellyucl** [comment]
2019 MKL has been requested in IN:03640950 (VASP issues).

> From what I have read these errors occur when matrices are too large for the Intel Maths Kernel Library (MKL) to handle. This issue has been resolved in more recent versions of the Intel MKL ie post MKL 2019.0.

**Comment by heatherkellyucl** [comment]
DiRAC are recommending users downgrade back to 2018 because of bugs (in MPI, not sure?) so we might want to reconsider this...

**Comment by heatherkellyucl** [comment]
> ## Known Issues and Limitations
> ### Intel® MPI Library 2019 Update 4
> 
>The buffered send may hang in some scenarios. Please use the debug or release_mt version of the library as a workaround in case of a hang during an MPI_Bsend/MPI_Ibsend call.
>
>Topology detection works improperly on SNC (sub-numa custer) enabled machines. Please setup I_MPI_HYDRA_TOPOLIB=ipl to overcome the problem.
> 
>To make the variables below work properly, please setup the I_MPI_HYDRA_TOPOLIB=ipl environment variable:
>I_MPI_PIN_DOMAIN=node
>I_MPI_PIN_DOMAIN=<domain_size>:scatter
>I_MPI_PIN_DOMAIN=<domain_size>:platform
> 
>The –genvexcl option or a combination of –genv and –genvall options may cause a crash. Please use the –genv option without –genvall or edit your run script to exclude variables listed for –genvexcl.
> 
> ### Intel® MPI Library 2019 Update 3
> 
>One of Allreduce algorithms may produce improper results or cause an application hang. If the problem can be solved with I_MPI_ADJUST_ALLREDUCE=0, please use the updated tuning configuration file.

**Comment by heatherkellyucl** [comment]
https://software.intel.com/en-us/articles/intel-math-kernel-library-2019-bug-fixes

Interesting one: `Fixed the problem that caused ScaLAPACK SVD routine to return incorrect array sizes.`

**Comment by balston** [comment]
The UCL wide Intel LM has been updated to the latest version.

**Comment by balston** [comment]
I've download Intel Parallel Studio 2019 update 4 installer and copied to:
- [ ] Grace;
- [ ]  Legion;
- [ ] Myriad;
- [ ] Thomas

in:
```
/shared/ucl/apps/intel/installers/parallel_studio_xe_2019_update4_cluster_edition.tgz
```

**Comment by owainkenwayucl** [comment]
Thanks Brian - I'm going to install these now.

**Comment by owainkenwayucl** [comment]
"The license server you provided does not have a valid license for this product."

**Comment by balston** [comment]
Linux installation guide:

[parallel-studio-xe-2019u4-install-guide-lin.pdf](https://github.com/UCL-RITS/rcps-buildscripts/files/3392388/parallel-studio-xe-2019u4-install-guide-lin.pdf)

**Comment by owainkenwayucl** [comment]
This version doesn't seem to let us do the trial license workaround.

**Comment by owainkenwayucl** [comment]
(unfortunately the document above is unhelpful)

**Comment by owainkenwayucl** [comment]
Installing interactively also fails.  Similarly these now fail for 2018.

**Comment by balston** [comment]
I've now tested the Linux and Mac versions of update 4 and while the Mac version works the Linux version fails even when completing the install with an evaluation license. 

I've emailed ISD Purchasing asking for an updated license file for the Linux version.

Also I've tried testing the Windows version of update 4 but the installer keeps hanging on my laptop. So i'm not sure if this has the same problem or not.

**Comment by balston** [comment]
The Windows installer has finally got past the point where it was hanging after appearing to be doing nothing for over an hour. It also fails to get a valid license during the install stage:
```
Activation rights do not allow this software to be installed. This could be due to expired subscription or outdated Intel® Software License Manager.
```
I will report this to Purchasing as well.

**Comment by balston** [comment]
We now have a set of new license files to apply to the UCL license server.

I will first test them in my test license server VM environment.

**Comment by balston** [comment]
Unfortunately these license files were all like:
```
SERVER lm-server2.ucl.ac.uk 0050568d2f30 28518
USE_SERVER
#
#SerialNumber=XXXXXXXXXXX
#
```
Robert is still sorting out getting full license files.

**Comment by balston** [comment]
It looks like Robert has now succeeded in getting the up-to-date license files so I'm going to try testing them in my VM  again.

**Comment by balston** [comment]
License files combined into one file and installed on my test server. LM restarted and I'm now testing with update 4 on each platform.

**Comment by balston** [comment]
Tested on:
- [ ] Linux;
- [ ] Mac;
- [ ] Windows.

**Comment by balston** [comment]
I cound't test the Windows version in my VM environment as the installer kept hanging.

I have now updated the live UCL license manager with the new combined license file and the Linux version of update 4 now installs and licenses correctly when compiling code.  The Mac and Windows versions are still being tested.

**Comment by owainkenwayucl** [comment]
Installed.

**Comment by owainkenwayucl** [comment]
The 2019 cluster studio includes the Intel Distribution for Python so I've added a module for the Python 3 (but not Python 2) installs of that.

**Comment by balston** [comment]
Both Mac and Windows installers are now working  as well and the installed compilers are now licensed correctly.

**Comment by owainkenwayucl** [comment]
Installed but MPI multinode jobs are not working, at least on Thomas.

First issue is that "tmi" has been deprecated in favour of "ofi", and one of the variables has been removed.

I've amended the module, but I'm still having problems running even basic jobs.

**Comment by owainkenwayucl** [comment]
One thing that occurs is I'm pretty sure we use a `tmi.conf` which I presume is also deprecated.

**Comment by owainkenwayucl** [comment]
Right - it looks like they've changed basically everything.

https://software.intel.com/en-us/articles/intel-mpi-library-2019-over-libfabric

**Comment by owainkenwayucl** [comment]
I've done a lot of digging and this is where we are:

1) We need to have a version of libfabric >= 1.7.0 on all MPI machines for Intel MPI to work.
2) There is a version of 1.5.0 installed in /usr/lib64.  This creates a libfabric.1.9.so despite being 1.5.0 because life is awful.
3) There is a version of 1.7.0 included in the MPI distribution as source. 
4) We can't compile it on Grace for Truescale because there is no psm.h header on Grace.

**Comment by owainkenwayucl** [comment]
I've added a warning to the Intel MPI module warning that it doesn't work on multinode jobs.

**Comment by owainkenwayucl** [comment]
On Thomas it gets further than Grace, probably because it has a version of the OPA drivers in the libfabric it's provided with but hangs as soon as there is MPI communication.

**Comment by heatherkellyucl** [comment]
I have submitted a 2-node test job on Thomas that sets `export I_MPI_DEBUG=5` to see what's going on.

**Comment by heatherkellyucl** [comment]
That didn't output much before hanging... But the libfabric still is too old.
```
[0] MPI startup(): libfabric version: 1.5.0

[0] MPI startup(): libfabric provider: psm2
```

**Comment by heatherkellyucl** [comment]
I ran one like this: 
`strace -f -o ${JOB_NAME}.trace.${JOB_ID} gerun -v ~/Scratch/pi_test/build/intel2019/mpi_pi`
This one got a signal 11 after ~1.5mins, which may be an strace artifact.

Have just included the verbose lines for fd 74 here.
```
[mpiexec@node-k98q-005] Launch arguments: /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/bin//h
ydra_bstrap_proxy --upstream-host node-k98q-005 --upstream-port 46495 --pgid 0 --launcher ssh --launcher-num
ber 0 --base-path /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/bin/ --tree-width 16 --tree-le
vel 1 --time-left -1 --collective-launch 1 --debug --proxy-id 0 --node-id 0 --subtree-size 1 --upstream-fd 7
 /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/bin//hydra_pmi_proxy --usize -1 --auto-cleanup 
1 --abort-signal 9 
[mpiexec@node-k98q-005] Launch arguments: /bin/ssh -q -x node-k98q-012 /shared/ucl/apps/intel/2019.Update4/i
mpi/2019.4.243/intel64/bin//hydra_bstrap_proxy --upstream-host node-k98q-005 --upstream-port 46495 --pgid 0 
--launcher ssh --launcher-number 0 --base-path /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/b
in/ --tree-width 16 --tree-level 1 --time-left -1 --collective-launch 1 --debug --proxy-id 1 --node-id 1 --s
ubtree-size 1 /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/bin//hydra_pmi_proxy --usize -1 --
auto-cleanup 1 --abort-signal 9
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=init pmi_version=1 pmi_subversion=1
[proxy:0:0@node-k98q-005] PMI response: cmd=response_to_init pmi_version=1 pmi_subversion=1 rc=0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_maxes
[proxy:0:0@node-k98q-005] PMI response: cmd=maxes kvsname_max=256 keylen_max=64 vallen_max=4096
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_appnum
[proxy:0:0@node-k98q-005] PMI response: cmd=appnum appnum=0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_my_kvsname
[proxy:0:0@node-k98q-005] PMI response: cmd=my_kvsname kvsname=kvs_18167_0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_my_kvsname
[proxy:0:0@node-k98q-005] PMI response: cmd=my_kvsname kvsname=kvs_18167_0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get kvsname=kvs_18167_0 key=PMI_process_mapping
[proxy:0:0@node-k98q-005] PMI response: cmd=get_result rc=0 msg=success value=(vector,(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1),(0,2,1))
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_my_kvsname
[proxy:0:0@node-k98q-005] PMI response: cmd=my_kvsname kvsname=kvs_18167_0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=barrier_in
[proxy:0:0@node-k98q-005] PMI response: cmd=barrier_out
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get kvsname=kvs_18167_0 key=sharedFilename[0]-0
[proxy:0:0@node-k98q-005] PMI response: cmd=get_result rc=0 msg=success value=/dev/shm/Intel_MPI_xpkeVL
[0] MPI startup(): libfabric version: 1.5.0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_my_kvsname
[proxy:0:0@node-k98q-005] PMI response: cmd=my_kvsname kvsname=kvs_18167_0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=put kvsname=kvs_18167_0 key=bc-44 value=mpi#02043402000000000000000000000000$
[proxy:0:0@node-k98q-005] PMI response: cmd=put_result rc=0 msg=success
[0] MPI startup(): libfabric provider: psm2
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get_my_kvsname
[proxy:0:0@node-k98q-005] PMI response: cmd=my_kvsname kvsname=kvs_18167_0
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=barrier_in
[proxy:0:1@node-k98q-012] PMI response: cmd=barrier_out
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get kvsname=kvs_18167_0 key=sharedFilename[0]-1
[proxy:0:0@node-k98q-005] PMI response: cmd=get_result rc=0 msg=success value=/dev/shm/Intel_MPI_8rkIqc
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get kvsname=kvs_18167_0 key=bc-44
[proxy:0:0@node-k98q-005] PMI response: cmd=get_result rc=0 msg=success value=mpi#02043402000000000000000000000000$
[proxy:0:0@node-k98q-005] pmi cmd from fd 74: cmd=get kvsname=kvs_18167_0 key=bc-45
[proxy:0:0@node-k98q-005] PMI response: cmd=get_result rc=0 msg=success value=mpi#02103702000000000000000000000000$
```
.e file says `could not open any host key` ?

**Comment by heatherkellyucl** [comment]
I have built a copy of the libfabric source that comes with Intel MPI 2019 in my home on Thomas and submitted a test job that should be using it.

**Comment by heatherkellyucl** [comment]
Intel MPI is still reporting it is using 1.5.0 and not the 1.7.0 install. You can `export I_MPI_OFI_LIBRARY_INTERNAL=1` to tell it to use its internal copy, but it doesn't seem to be working trying to get it to use a different system version.

**Comment by heatherkellyucl** [comment]
Looking at the install again, it did build its libfabric during that, in `/shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/libfabric/lib`.

Going to see what `export I_MPI_OFI_LIBRARY_INTERNAL=1` gets it to see.

**Comment by heatherkellyucl** [comment]
It is still outputting `[0] MPI startup(): libfabric version: 1.5.0`, I do not understand.

**Comment by heatherkellyucl** [comment]
Pretty sure we are missing some path additions in the modulefile. I set these
```
export I_MPI_DEBUG=1
export FI_LOG_LEVEL=debug
export I_MPI_OFI_LIBRARY_INTERNAL=1
export FI_PROVIDER_PATH="${I_MPI_ROOT}/intel64/libfabric/lib/prov"
```
in my last try, and was getting 
```
libfabric:core:core:ofi_ini_dir():406<warn> dlopen(/shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel
64/libfabric/lib/prov/libsockets-fi.so): /lib64/libfabric.so.1: version `FABRIC_1.2' not found (required by 
/shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/libfabric/lib/prov/libsockets-fi.so)
```
If you tried to run the internal version of `fi_info --env` to see the available environment variables you got the same error - the internal libfabric.so isn't in the library path.  So I have created a test copy of the MPI module that does this too:
```
# use internal libfabric
prepend-path PATH               $prefix/intel64/libfabric/bin
prepend-path LD_LIBRARY_PATH    $prefix/intel64/libfabric/lib
prepend-path LIBRARY_PATH       $prefix/intel64/libfabric/lib
setenv FI_PROVIDER_PATH         $prefix/intel64/libfabric/lib/prov
```
Going to see what this does.

**Comment by heatherkellyucl** [comment]
Working across two nodes and the module is fixed!
```
Calculating PI using 48 processes...
Proc 0 says hello, is going to calculate slice 0-20833332
Proc 1 says hello, is going to calculate slice 20833333-41666665
Proc 2 says hello, is going to calculate slice 41666666-62499999
Proc 3 says hello, is going to calculate slice 62500000-83333332
...
Proc 45 says hello, is going to calculate slice 937500000-958333332
Proc 46 says hello, is going to calculate slice 958333333-979166665
Proc 47 says hello, is going to calculate slice 979166666-999999999
The value of PI is 3.14159250579683
The time to calculate PI was 5.84324e+07 seconds
```
Need `psm.h` for Grace (PSM 1).

**Comment by heatherkellyucl** [comment]
William has found the rpm providing psm.h and will get it added to the list installed as part of the image.

**Comment by heatherkellyucl** [comment]
- [ ] I need to test whether the normal Intel compiler install will build libfabric with all found providers and no changes to the buildscript. (Once we have a psm.h on Grace).

**Comment by heatherkellyucl** [comment]
I was confused by the libfabric install layout that the Intel installer ends up with. It looks like this:
```
ls /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/libfabric/lib/
libfabric.so  libfabric.so.1  prov
ls /shared/ucl/apps/intel/2019.Update4/impi/2019.4.243/intel64/libfabric/lib/prov/
libpsmx2-fi.so  librxm-fi.so  libsockets-fi.so  libtcp-fi.so  libverbs-fi.so
```
> Each OFI provider is built as a separate dynamic library to ensure that the single libfabric library can be run on top of different network adapters.

Note there is no `libpsmx-fi.so` in there.

When you build from source normally you end up with a `lib` directory like this:
```
ls ~/libfabric_build/lib/
libfabric.a  libfabric.la  libfabric.so  libfabric.so.1  libfabric.so.1.10.1  pkgconfig
```
I found that to get something similar to the former you build libfabric like this, with explicit dynamic libraries:
```
./configure --prefix=/home/cceahke/libfabric_psm --enable-psm=dl --enable-rxm=dl --disable-rxd --disable-usnic --enable-sockets=dl --enable-tcp=dl --enable-verbs=dl --disable-mrail --disable-psm2
```
At the end of configure it outputs:
```
***
*** Built-in providers: perf rstream shm udp 
*** DSO providers:      rxm tcp verbs sockets psm 
***
```
Then you get this:
```
ls /home/cceahke/libfabric_psm/lib/
libfabric  libfabric.a  libfabric.la  libfabric.so  libfabric.so.1  libfabric.so.1.10.1  pkgconfig
ls /home/cceahke/libfabric_psm/lib/libfabric
libpsmx-fi.la  librxm-fi.la  libsockets-fi.la  libtcp-fi.la  libverbs-fi.la
libpsmx-fi.so  librxm-fi.so  libsockets-fi.so  libtcp-fi.so  libverbs-fi.so
```

I'm going to try using that one, as so far I have had no success trying to get the pi example running with the Intel MPI module and my local libfabric build with psm - it doesn't find any providers that it can use and falls through the list before exiting.

I do have a testmodule for Intel MPI that does not set any of the things that let it find the internal libfabric.

**Comment by heatherkellyucl** [comment]
Aha, it worked, but it is using sockets on Grace:
```[0] MPI startup(): libfabric version: 1.7.2a

[0] MPI startup(): libfabric provider: sockets

Calculating PI using 32 processes...
Proc 0 says hello, is going to calculate slice 0-31249999
Proc 2 says hello, is going to calculate slice 62500000-93749999
...
Proc 29 says hello, is going to calculate slice 906250000-937499999
Proc 31 says hello, is going to calculate slice 968750000-999999999
The value of PI is 3.14159255606406
The time to calculate PI was 5.84873e+07 seconds
```
There is a lot of FI log full of registering providers, getting warnings, and trying other options that is not very explicable (and is repeated for each core).
```
libfabric:psm:core:psmx_init_lib():97<info> PSM header version = (1, 16)
libfabric:psm:core:psmx_init_lib():99<info> PSM library version = (1, 16)
libfabric:ofi_rxm:core:fi_param_get_():272<info> variable use_srx=<not set>
libfabric:psm:core:psmx_getinfo():206<info> 
libfabric:psm:core:psmx_getinfo():238<info> hints->ep_attr->type=1, supported=0,2,3.
libfabric:core:core:fi_getinfo_():1002<warn> fi_getinfo: provider psm returned -61 (No data available)
libfabric:core:core:ofi_layering_ok():877<info> Need core provider, skipping ofi_rxm
libfabric:core:core:fi_getinfo_():980<info> Since psm can be used, verbs has been skipped. To use verbs, please, set FI_PROVIDER=verbs
libfabric:core:core:fi_getinfo_():980<info> Since psm can be used, UDP has been skipped. To use UDP, please, set FI_PROVIDER=UDP

libfabric:psm:core:psmx_getinfo():248<info> hints->caps: requested=FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_DIRECTED_RECV
libfabric:psm:core:psmx_getinfo():248<info> hints->caps: supported=FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_RMA_EVENT
libfabric:psm:core:psmx_getinfo():250<info> alternatively, hints->caps: requested=FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_DIRECTED_RECV
libfabric:psm:core:psmx_getinfo():250<info> alternatively, hints->caps: supported=FI_MSG, FI_RMA, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_RMA_EVENT, FI_DIRECTED_RECV

libfabric:core:core:fi_getinfo_():980<info> Since verbs can be used, psm has been skipped. To use psm, please, set FI_PROVIDER=psm
libfabric:core:core:fi_getinfo_():1002<warn> fi_getinfo: provider ofi_rxm returned -22 (Invalid argument)
libfabric:verbs:core:fi_ibv_check_hints():229<info> Unsupported capabilities
libfabric:verbs:core:fi_ibv_check_hints():230<info> Supported: FI_MSG, FI_RMA, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_LOCAL_COMM, FI_REMOTE_COMM
libfabric:verbs:core:fi_ibv_check_hints():230<info> Requested: FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_DIRECTED_RECV
libfabric:verbs:core:fi_ibv_check_hints():229<info> Unsupported capabilities
libfabric:verbs:core:fi_ibv_check_hints():230<info> Supported: FI_MSG, FI_RECV, FI_SEND, FI_LOCAL_COMM, FI_REMOTE_COMM
libfabric:verbs:core:fi_ibv_check_hints():230<info> Requested: FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_DIRECTED_RECV
libfabric:core:core:fi_getinfo_():1002<warn> fi_getinfo: provider verbs returned -61 (No data available)

libfabric:UDP:core:ofi_check_ep_type():629<info> Unsupported endpoint type
libfabric:UDP:core:ofi_check_ep_type():630<info> Supported: FI_EP_DGRAM
libfabric:UDP:core:ofi_check_ep_type():630<info> Requested: FI_EP_RDM

libfabric:sockets:core:fi_param_get_():272<info> variable iface=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable iface=<not set>
libfabric:sockets:core:sock_get_list_of_addr():599<info> available addr: : fi_sockaddr_in://10.32.1.209:0
libfabric:sockets:core:sock_get_list_of_addr():599<info> available addr: : fi_sockaddr_in://169.254.95.120:0
...
libfabric:sockets:core:sock_insert_loopback_addr():535<info> available addr: : fi_sockaddr_in://1.0.0.127:0
libfabric:sockets:core:sock_insert_loopback_addr():547<info> available addr: : fi_sockaddr_in6://[::1]:0
libfabric:sockets:core:sock_ep_getinfo():498<info> src addr: : fi_sockaddr_in://10.32.1.209:0
...

libfabric:sockets:core:fi_param_get_():272<info> variable pe_waittime=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable conn_timeout=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable max_conn_retry=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable def_conn_map_sz=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable def_av_sz=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable def_cq_sz=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable def_eq_sz=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable keepalive_enable=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable keepalive_time=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable keepalive_intvl=<not set>
libfabric:sockets:core:fi_param_get_():272<info> variable keepalive_probes=<not set>
libfabric:core:core:fi_fabric_():1207<info> Opened fabric: 10.32.0.0/18
libfabric:core:core:ofi_shm_map():123<warn> shm_open failed
libfabric:sockets:av:sock_av_open():565<warn> map failed

libfabric:psm:core:psmx_fini():677<info>
```

**Comment by heatherkellyucl** [comment]
So I think we need `--enable-psm=dl` and possibly `--disable-psm2` added to wherever the Intel installers configure their libfabric.

**Comment by heatherkellyucl** [comment]
Submitted a job to see if it says anything else if I set `export FI_PROVIDER=psm` again.

**Comment by heatherkellyucl** [comment]
Errors if you do that:
```
libfabric:core:core:fi_getinfo_():1002<warn> fi_getinfo: provider psm returned -61 (No data available)
Abort(1094799) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init: Other MPI error, error stack:
MPIR_Init_thread(666)......: 
MPID_Init(922).............: 
MPIDI_NM_mpi_init_hook(758): OFI addrinfo() failed (ofi_init.h:758:MPIDI_NM_mpi_init_hook:No data available)
```

I think the problem is here:
```
libfabric:psm:core:psmx_getinfo():248<info> hints->caps: requested=FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_DIRECTED_RECV
libfabric:psm:core:psmx_getinfo():248<info> hints->caps: supported=FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_RMA_EVENT
libfabric:psm:core:psmx_getinfo():250<info> alternatively, hints->caps: requested=FI_MSG, FI_RMA, FI_TAGGED, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_DIRECTED_RECV
libfabric:psm:core:psmx_getinfo():250<info> alternatively, hints->caps: supported=FI_MSG, FI_RMA, FI_ATOMIC, FI_READ, FI_WRITE, FI_RECV, FI_SEND, FI_REMOTE_READ, FI_REMOTE_WRITE, FI_MULTI_RECV, FI_TRIGGER, FI_RMA_EVENT, FI_DIRECTED_RECV
```
If you look at https://github.com/ofiwg/libfabric/wiki/Provider-Feature-Matrix-v1.7.0, `FI_DIRECTED_RECV` is not supported by psm. I don't know why it is being requested though...

**Comment by heatherkellyucl** [comment]
```
FI_LOG_LEVEL=debug fi_info -p psm -v
```
Handy command to see the info about a given provider.

**Comment by owainkenwayucl** [comment]
(note - I've been contacted by email by Intel in reference to my comments about this on Twitter)

**Comment by owainkenwayucl** [comment]
@heatherkellyucl on Grace are we setting the two environment variables here:

https://software.intel.com/en-us/articles/intel-mpi-library-2019-over-libfabric

Namely:

```
FI_PSM_TAGGED_RMA=0
FI_PSM_AM_MSG=1
```

I wonder if setting `FI_DIRECTED_RECV=0` might help?

**Comment by heatherkellyucl** [comment]
Yes, tried with and without those. Note that the PSM section has entirely disappeared in https://software.intel.com/en-us/mpi-developer-guide-linux-ofi-providers-support.

> Intel® MPI Library supports psm2, sockets, verbs, and RxM OFI* providers.

**Comment by heatherkellyucl** [comment]
`FI_PSM_DIRECTED_RECV=0` does nothing, but you'd expect that as PSM doesn't do `DIRECTED_RECV` anyway. The capabilities requested still include it.

**Comment by heatherkellyucl** [comment]
From #331 

> As an aside, last week @heatherkellyucl and I managed to work out what was up with MPI in Intel 2019.4 on Grace with verbs - the verbs libfabric provider relies on IPoIB for routing and due to the complicated IPoIB setup that system has it was selecting the wrong subnet. This is now resolved.

Had to set `FI_VERBS_IFACE ib0:1`in the modulefile for Grace. Otherwise it was sometimes working if all the nodes in use happened to be in the vlan that it picked first, and not working otherwise. (There are two that span parts of the cluster and one that covers all).

**Comment by heatherkellyucl** [comment]
Pairs of Intel compilers and MPI currently installed:
```
compilers/intel/2019/update4
mpi/intel/2019/update4/intel

compilers/intel/2019/update5
mpi/intel/2019/update5/intel

compilers/intel/2020/release
mpi/intel/2019/update6/intel
```

But also from #331, the Intel 2019.5 and 2020.0 compilers throw a floating point exception on compiling GROMACS' pull_util at optimisation levels above 2, bug at https://software.intel.com/en-us/forums/intel-c-compiler/topic/849759
