### ISSUE TITLE
SPSS

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#228]
IN:03233454

We have an install of SPSS purely for testing license servers: need to create a modulefile and to work out how to run it from the commandline inside jobs.

**Comment by balston** [comment]
We also need to install SPSS 25. Currently only SPSS 24 is installed.

**Comment by balston** [comment]
SPSS batch Jobs
--
Unfortunately the SPSS Server component that provides the statsisticsb command need to run SPSS Syntax files in batch jobs is not included in the UCL SPSS agreement. We are finding out how much adding SPSS server will cost.

In the meantime there is another possible way to run SPSS jobs - using the Production job facility. I'm investigating this next.

**Comment by balston** [comment]
SPSS production jobs: Trying:
```
 stats -nologo -production `pwd`/regression1.spj
```
Not working:
```
Exception in thread "Thread-15" java.lang.NullPointerException
        at com.spss.java_client.core.documents.production.ProductionManager.output(Unknown Source)
        at com.spss.java_client.core.documents.production.ProductionManager.run(Unknown Source)
```
