### ISSUE TITLE
HOOMD Installation [IN03408884]

### ISSUE THREAD

**Issue by ColinMoody** [UCL-RITS/rcps-buildscripts#230]
Hello,

May hoomd-blue please be installed onto Thomas? It is a molecular dynamics toolkit with several dependencies (CUDA, Numpy, etc.) that can be found here ;

http://glotzerlab.engin.umich.edu/hoomd-blue/

Many thanks,

Colin

**Comment by heatherkellyucl** [comment]
(It won't have CUDA as Thomas has no GPUs).

**Comment by ColinMoody** [comment]
I mispoke when listing some of the dependencies; I appreciate CUDA is for the GPU build only! I am under the impression from the website that hoomd also can work efficiently on CPU clusters and was hoping to have such a build made for Thomas.

**Comment by heatherkellyucl** [comment]
Yes, that's not a problem - I checked that CUDA was an optional dependency.
