### ISSUE TITLE
Update Rosetta to 2018 version IN:03388620

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#234]

**Comment by balston** [comment]
Rosetta is licensed software and downloads are behind a site login at:

https://www.rosettacommons.org/software/academic

Rob Silk and myself have details. I'm downloading version 2018.48 now.

**Comment by balston** [comment]
The latest 2018 version is now in:
```
/shared/ucl/apps/Rosetta/source/rosetta_src_2018.48.60516_bundle.tgz
```
on Legion, Grace and Myriad.

**Comment by balston** [comment]
I've updated the build script for the serial version to 2018 and I'm compiling Rosetta on Myriad now.

**Comment by balston** [comment]
Serial build didn't complete on Friday so restarted this morning. Serial build has now finished. Before I can run the serial tests in a job, I need to make a copy of the build directory in my Scratch:
```
(cd /shared/ucl/apps/Rosetta/; tar cvzf - rosetta_src_2018.48.60516_bundle) | tar xvzf -
```

**Comment by balston** [comment]
Job submitted for serial tests using this job script:
```
#!/bin/bash -l

# Batch script to run Rosetta 2018 serial tests in a job on Myriad 
# under SGE
#
# Rosetta Version 2018.48.60516

# 1. Force bash as the executing shell.
#$ -S /bin/bash

# 2. Request 1 hour of wallclock time (format hours:minutes:seconds).
#$ -l h_rt=1:0:0

# 3. Request 2 gigabyte of RAM per process.
#$ -l mem=2G

# 4. Request 15 gigabyte of TMPDIR space per node (default is 10 GB)
#$ -l tmpfs=15G

# 4a. Set the name of the job. You can change this if you wish.
#$ -N Rosetta_tests_serial1

# 5. Select 4 threads. 
#$ -pe smp 4

# 6. Set the working directory to somewhere in your scratch space.  This is
# a necessary step with the upgraded software stack as compute nodes cannot
# write to $HOME.
#
# NOTE: this directory must exist.
#
# Replace "<your_UCL_id>" with your UCL user ID :)
#$ -wd /home/ccaabaa/Scratch/Software/Rosetta/rosetta_src_2018.48.60516_bundle/main/tests/integration

# 7. Setup environment
module unload compilers
module unload mpi
module load compilers/gnu/4.9.2
module load python2/recommended

# 8. Run tests
echo Started `date`
echo ''
./integration.py -j4 -d ../../database
echo ''
echo Finished `date`
```
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 304403 0.00000 Rosetta_te ccaabaa      qw    12/10/2018 11:48:43                                    4
```

**Comment by balston** [comment]
OK this job failed to run the tests! Instead of copying my job script from the 2015 build, I need to read the documentation!

**Comment by balston** [comment]
The integration tests appear to be designed to run when a copy of the Rosetta repository is pulled and again after changes have been ma`de to the local copy. I'm using a download of a weekly release archive for building so this is probably why my attempt to run the tests was failing with git errors!

Instead to check my build, I've copied the demo directory and submitted test jobs on demos where expected results are available.

**Comment by balston** [comment]
Updating the MPI build script next.

**Comment by balston** [comment]
Starting MPI build on Myriad.

**Comment by balston** [comment]
The MPI build has not finished. Will need to continue tomorrow.

**Comment by balston** [comment]
Continuing the MPI build.

**Comment by balston** [comment]
The MPI build finally finished over lunch. Now submitting a test job.

**Comment by balston** [comment]
Test MPI job using 16 cores submitted:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 312939 2.97536 Rosetta_te ccaabaa      qw    12/12/2018 15:34:56                                   16
```

**Comment by balston** [comment]
Job fails with errors like:
```
mpi_msd.mpi.linuxgccrelease: error while loading shared libraries: libcppdb.so: cannot open shared object file: No such file or directory
```

**Comment by balston** [comment]
My test Rosetta MPI job is now running correctly on Myriad so I'm starting the builds on Grace. Serial one first ...

**Comment by balston** [comment]
Grace serial build has finished. Now staring MPI build ...

**Comment by balston** [comment]
Also starting Legion serial build ...

**Comment by balston** [comment]
Grace MPI build completed. Running a test job ...

Legion serial build finished but with an error at the end:
```
scons: done building targets.
/shared/ucl/apps/Rosetta/Rosetta-2018.48.60516-serial
mv: cannot move ârosetta_src_2018.48.60516_bundleâ to â/shared/ucl/apps/Rosetta/rosetta_src_2018.48.60516_bundleâ: File exists
```

**Comment by balston** [comment]
- Legion serial test job worked.

- Legion MPI build started.

- Grace MPI test job ran.

**Comment by balston** [comment]
Legion MPI build completed.

**Comment by balston** [comment]
Modules:
```
2018.48.60516
2018.48.60516-mpi
```
Deployed on:
- [ ] Aristotle;
- [ ] Legion;
- [ ] Grace;
- [ ] Myriad.

**Comment by balston** [comment]
I've emailed the requester.
