### ISSUE TITLE
Install request: Gulp 5.0 [IN03443262]

### ISSUE THREAD

**Issue by JaviFdezT** [UCL-RITS/rcps-buildscripts#240]
In the last versions, new changes and funtionalities have been added. Can anyone update this package or install the last version?

**Comment by balston** [comment]
Requester has now emailed rc-support. They need at least GULP 4.6 - latest version is 5.1 so we should go with this version:

https://nanochemistry.curtin.edu.au/gulp/

Need to be registered to download the source code.

**Comment by balston** [comment]
I've registered and the downloaded the 5.1 sources to:
```
/shared/ucl/apps/gulp/sources/gulp-5.1.tgz
```
on Thomas only at the moment as this is where we need to built GULP first.

**Comment by balston** [comment]
Updating the 4.5 build script for GULP 5.1 ...

**Comment by balston** [comment]
5.1 build script uploaded and pushed to Thomas.

**Comment by balston** [comment]
Ok this didn't work as I need to tell mkgulp the GULP builder to use the Intel compilers using the:
```
-c intel
```
flag. Adding this to the build script and then running it again.

**Comment by balston** [comment]
GULP has now compiled without errors. However according to the GULP 4.5 module file:
```
GULP is built with FoX and without plumed.
```
I need to update the 5.1 mkgulp builder to compile with the FoX code. I'll need a patch file to do this in the build script. So adding this ...

**Comment by balston** [comment]
I've added:
```
# modify mkgulp to build GULP with FoX
sed -i.orig -e '/UDEFS=/s/-DNOFOX//' mkgulp
```
to the build script so mkgulp includes FoX.

**Comment by balston** [comment]
Now running:
```
cd /shared/ucl/apps/build_scripts
./gulp-5.1_install
```
again ...

**Comment by balston** [comment]
OK this has failed with a number of compilation errors like:
```
mpif90  -O3  -I.. -I/usr/local/include/    -DFLUSH   -DMPI     -c ../mdprop.F90
../mdprop.F90(55): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [FOX_WXML]
  use gulp_cml_md,    only : gulp_cml_md_startstep, gulp_cml_md_endstep, &
------^
../mdprop.F90(125): error #6404: This name does not have a type, and must have an explicit type.   [LADIABATIC]
  lintsh = (nshell.ne.0.and..not.ladiabatic)
```

**Comment by balston** [comment]
Adding:
```
-e '/INC=/s/-I../-I.. -I.\/FoX-4.1.2\/objs\/finclude/' 
```
to the mkgulp sed command in the build script.

**Comment by balston** [comment]
Oops! I should have used:
```
-I..\/FoX-4.1.2\/objs\/finclude/'
```
I think.

**Comment by balston** [comment]
OK build of GULP 5.1 with FoX has finished with out errors. Now to run some tests ...

**Comment by balston** [comment]
I've successfully ran a couple of the supplied examples (example1 and example65) and the results look comparable. Will now upload the module file.

**Comment by balston** [comment]
Module file now on Thomas:
```
module load gulp/5.1.1/intel-2018
```
I've informed the requester and will wait for a response before installing on our other clusters.

**Comment by balston** [comment]
GULP 5.1.1 installed on:
- [ ] Legion;
- [ ] Grace;
- [ ] Michael;
- [ ] Myriad;
- [ ] Thomas.

**Comment by balston** [comment]
GULP 5.1.1 installed everywhere. Added to applications page on the Wiki.
