### ISSUE TITLE
Install request: XtalOpt [IN03448408]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#243]
http://xtalopt.github.io/xtalopt.html

User is trying to build this on Michael and getting the following errors:
```
[100%] Linking CXX executable ../../bin/xtalopt
/usr/lib64/libX11.so.6: undefined reference to `xcb_poll_for_reply64'
/usr/lib64/libX11.so.6: undefined reference to `xcb_wait_for_reply64'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/xtalopt] Error 1
make[1]: *** [src/xtalopt/CMakeFiles/xtalopt.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by balston** [comment]
Install release 12.0 the latest version.

**Comment by ikirker** [comment]
One possible set up for this is to run on a user's own machine and interact with the queue remotely. I'm not sure how this is accomplished yet.

**Comment by balston** [comment]
Trying a test build to see what is required to fix the X issue. Source code build dependencies are from the installation instructions here: http://xtalopt.github.io/install-linux.html):
- GNU compilers >= 4.8.4
- git, any version
- cmake (and optionally the ncurses GUI, ccmake) >= 3.0
- Qt >= 5.2.1
- Qwt >= 6.1.3 (compiled with Qt5)
- Eigen >= 3 

We have all these apart from Qwt. Will need to use the following modules:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load qt/5.4.2/gnu-4.9.2
module load eigen/3.2.5/gnu-4.9.2
```
Building Qwt first.

**Comment by balston** [comment]
Qwt is available here: https://qwt.sourceforge.io/ Downloaded:
```
wget https://sourceforge.net/projects/qwt/files/qwt/6.1.4/qwt-6.1.4.tar.bz2/download -O qwt-6.1.4.tar.bz
```

**Comment by balston** [comment]
Qwt is now installed in:
```
/shared/ucl/apps/qwt/6.1.4/gnu-4.9.2/qwt-6.1.4
```
using:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load qt/5.4.2/gnu-4.9.2
cd /shared/ucl/apps/build_scripts
./qwt-6.1.4_install
```
on Thomas and will sync to Michael overnight. The build script for Qwt is here:

https://github.com/UCL-RITS/rcps-buildscripts/blob/master/qwt-6.1.4_install

Now to construct a suitable module file for Qwt.

**Comment by balston** [comment]
Module file now pushed to Thomas and will sync overnight to Michael. So for building XtalOpt, we will now need to following modules:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load qt/5.4.2/gnu-4.9.2
module load eigen/3.2.5/gnu-4.9.2
module load qwt/6.1.4/gnu-4.9.2
```

**Comment by balston** [comment]
Trying a test build in my area using:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load qt/5.4.2/gnu-4.9.2
module load eigen/3.2.5/gnu-4.9.2
module load qwt/6.1.4/gnu-4.9.2
cd ~/Software/XtalOpt/XtalOpt-r12.0/
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ccaabaa/apps/XtalOpt/r12.0
```

**Comment by balston** [comment]
This didn't work. In fact QT 5 on our clusters is broken. For example:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load xorg-utils/X11R7.7
module load qt/5.4.2/gnu-4.9.2
```
Using one of the supplied examples:
```
cd /shared/ucl/apps/qt/5.4.2/gnu-4.9.2/examples/multimedia/spectrum
./spectrum
./spectrum: symbol lookup error: /lib64/libX11.so.6: undefined symbol: xcb_wait_for_reply64
```
All the QT GUI examples I tried fail in this way.

**Comment by balston** [comment]
The issue doesn't appear to depend on the local X server. Same problem from XQuartz on my MacBook and Xorg on Linux.

This needs to be sorted out before proceeding any further with XtalOpt.

**Comment by balston** [comment]
Qt 5.12.1 no installed and appears to work so back to building Qwt this time with Qt 5.12.1.

**Comment by balston** [comment]
Qwt build script updated to use Qt 5.12.1. Building with:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load xorg-utils/X11R7.7
module load qt/5.12.1/gnu-4.9.2
cd /shared/ucl/apps/build_scripts
./qwt-6.1.4_install

**Comment by balston** [comment]
Build has finished without errors!

**Comment by balston** [comment]
Module file now also updated to use Qt 5.12.1.

**Comment by balston** [comment]
Back to trying a test build of XtalOpt in my area but now using the following:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load xorg-utils/X11R7.7
module load qt/5.12.1/gnu-4.9.2
module load eigen/3.2.5/gnu-4.9.2
module load qwt/6.1.4/gnu-4.9.2

cd ~/Software/XtalOpt/XtalOpt-r12.0/
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/home/ccaabaa/apps/XtalOpt/r12.0
```

**Comment by balston** [comment]
I now get the following error:
```
-- SSH Enabled
-- Using libssh SSH interface
CMake Error at CMakeLists.txt:141 (message):
  libssh not found!


-- Configuring incomplete, errors occurred!
See also "/home/ccaabaa/Software/XtalOpt/XtalOpt-r12.0/build/CMakeFiles/CMakeOutput.log".
See also "/home/ccaabaa/Software/XtalOpt/XtalOpt-r12.0/build/CMakeFiles/CMakeError.log".
```

**Comment by balston** [comment]
libssh include headers may be missing!

**Comment by balston** [comment]
I've checked now and:
```
/usr/include/libssh2.h
```
etc exist so why was the test failing?

**Comment by balston** [comment]
It looks like XtalOpt may require the older libssh instead of libssh2. We don't have libssh on the clusters.

**Comment by balston** [comment]
I've done some further testing using a Linux VM where I could add packages and XtalOpt definitely requires:
```
libssh-devel
```
to be installed. It must be libssh and not libssh2!

**Comment by balston** [comment]
User doesn't need ssh:

> If you manage to go pass this point, please do not worry about SSH - it won’t be needed in our work, so you can safely disable it with
> ENABLE_SSH:BOOL=false
> in CMakeCache.txt
> 

Going to try this with the above build recipe from 15th March.

**Comment by balston** [comment]
Changed:
```
//Enable SSH. Only the local queue interface will be available
// if disabled.
ENABLE_SSH:BOOL=ON
```
to:
```
//Enable SSH. Only the local queue interface will be available
// if disabled.
ENABLE_SSH:BOOL=OFF
```

**Comment by balston** [comment]
This appears to have worked. So now I'm going to write a build script.

**Comment by balston** [comment]
First version of build script now being tested building XtalOpt on Thomas.

**Comment by balston** [comment]
Build script has worked and installed XtalOpt. Now for a module file.

**Comment by DrewNow** [comment]
That's great Brian!

Could you please share the build script or a module, once it's built on michael with me?

Many thanks,
Andrij

**Comment by balston** [comment]
Module file uploaded to Thomas.

All should sync to Michael for Monday.

**Comment by balston** [comment]
XtalOpt synced successfully to Michael.  I've informed the user.
