### ISSUE TITLE
ASCAT and Battenberg

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#246]
IN:03451186

https://github.com/cancerit/ascatNgs
https://github.com/cancerit/cgpBattenberg

Dependencies:
* cgpBigWig https://github.com/cancerit/cgpBigWig
* PCAP v2.0+ https://github.com/cancerit/PCAP-core
* cgpVcf v2.0+ https://github.com/cancerit/cgpVcf
* alleleCount v4.0.0+ https://github.com/cancerit/alleleCount
* RColorBrewer https://cran.r-project.org/web/packages/RColorBrewer/index.html

**Comment by heatherkellyucl** [comment]
Starting on this, getting all the newest versions.

**Comment by heatherkellyucl** [comment]
Going to see if this works with Python3.

**Comment by heatherkellyucl** [comment]
New install script is `cancerit-20190218-python3_install` and first attempt at build is underway.

**Comment by heatherkellyucl** [comment]
Looks like everything except cgpBattenberg installed no problem. cgpBattenberg needs R, and our R uses python2, curses.
```
Running setup in cgpBattenberg-3.3.0...
============== System information ====
+ lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo
+ uname -a
Linux login12.myriad.ucl.ac.uk 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
+ sw_vers
./setup.sh: line 70: sw_vers: command not found
+ system_profiler
./setup.sh: line 71: system_profiler: command not found
+ grep MemTotal /proc/meminfo
MemTotal:       197534132 kB
+ set +x

which: no cpanm in (/shared/ucl/apps/curl/7.47.1/gnu-4.9.2/bin:/shared/ucl/apps/htslib/1.7/bin:/shared/ucl/apps/perl/perlbrewroot/perls/perl-5.22.0/bin:/shared/ucl/apps/python/3.7.2/gnu-4.9.2/bin:/shared/ucl/apps/ecj/4.9/gnu-4.9.2:/shared/ucl/apps/gcc/4.9.2/bin:/opt/sge/bin:/opt/sge/bin/lx-amd64:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ccspapp/.local/bin:/home/ccspapp/bin)

Installing build prerequisite File::ShareDir...+ -v --mirror http://cpan.metacpan.org --notest -l /shared/ucl/apps/cancerit/20190218-python-3.7/gnu-4.9.2 File::ShareDir
./setup.sh: line 88: -v: command not found
```

**Comment by heatherkellyucl** [comment]
I'm doing a Battenberg install in my home against the new CancerIT versions of everything so I can get the build script correct. So far, the Perl install needs these adding:
```
File::ShareDir::Install
File::ShareDir
```
It is next not picking up that PCAP-core exists.

**Comment by heatherkellyucl** [comment]
cgpBattenberg deliberately unsets PERL5LIB so when testing it somewhere else you need to install it like this:
```
./setup.sh $INSTALL_PREFIX /location/to/lib/perl5
```
It ran its tests and succeeded.

**Comment by heatherkellyucl** [comment]
Our R module bundles currently load `python2/recommended` and the current cancerit module depends on R. I don't think this is strictly necessary, though R can certainly be used with it. 

If the R dependency to python2 can be removed it means I can keep this cancerit build as a Python 3 version and have it still be usable with R if desired.

**Comment by heatherkellyucl** [comment]
Have installed these for perl 5.22.0 on all clusters (Michael will sync) and updated perl install list.
```
File::ShareDir::Install
File::ShareDir
```

**Comment by heatherkellyucl** [comment]
Unfortunately, I think I'll have to do an install depending on R and python2 at the moment to get this done. cgpBattenberg gets complicated: it needs battenberg and ascat to be installed, which are R, and are in separate repos from cgpBattenberg and ascatNGS:

https://github.com/Wedge-Oxford/battenberg
https://github.com/Crick-CancerGenomics/ascat

cgpBattenberg's setupR.sh gets version 2.5.1 of ascat (though 2.5.2 is now out) and v2.2.8 of battenberg.

(AscatNGS says "The core ascat.R script is pulled from the primary ASCAT repository during installation. The linked version is currently v2.5.1" but it doesn't appear to keep ascat.R anywhere in the install directory. At present anyway, it might do when R is available).

**Comment by heatherkellyucl** [comment]
Started installing Python 2 version with R 3.5.1 basic requirements. `cancerit-20190218-python2_install` buildscript.

Will see if anything needs modifying for the R install parts, though I am giving it an R-libs directory.

**Comment by heatherkellyucl** [comment]
It is currently failing during a build of exonerate via BRASS - that didn't happen the first time round...

```
Set source_root_dir to /tmp/cancerit-build.KV8ioz1S2R/BRASS-6.2.0/distros/exonerate-2.2.0
----------------------------------------------------------------
checking for socklen_t... yes
checking for pkg-config... /bin/pkg-config
Using GLIB-2
Turning assertions off
Turning paranoid options off
Not using options for profiling with gprof
Not using options for analysis with gcov
Adding support for LARGE FILES (>2Gb) for a 32 bit system
Using COMPILED C4 MODELS
Installing UTILITIES
Using PTHREADS
----------------------------------------------------------------
configure: creating ./config.status
config.status: creating Makefile 
config.status: creating doc/Makefile
config.status: creating doc/man/Makefile
config.status: creating doc/man/man1/Makefile
config.status: creating src/Makefile
config.status: creating src/general/Makefile
config.status: creating src/sequence/Makefile
config.status: creating src/database/Makefile
config.status: creating src/struct/Makefile
config.status: creating src/comparison/Makefile
config.status: creating src/c4/Makefile
config.status: creating src/bsdp/Makefile
config.status: creating src/sdp/Makefile
config.status: creating src/hub/Makefile
config.status: creating src/model/Makefile
config.status: creating src/program/Makefile
config.status: creating src/util/Makefile
config.status: creating test/Makefile
config.status: creating test/util/Makefile
config.status: creating test/ipcress/Makefile
config.status: creating test/exonerate/Makefile
config.status: creating test/data/Makefile
config.status: creating test/data/cdna/Makefile
config.status: creating test/data/protein/Makefile
cd . && autoconf
/usr/bin/perl: symbol lookup error: /shared/ucl/apps/cancerit/20190218-python-2.7.12/gnu-4.9.2/lib/perl5/x86_64-linux-thread-multi/auto/List/Util/Util.so: undefined symbol: Perl_xs_handshake
make: *** [configure] Error 127  
```
Using `/usr/bin/perl` instead of `/usr/bin/env perl`. I had the `exonerate/2.2.0` module loaded, so it *should* have been using that...

**Comment by heatherkellyucl** [comment]
`./setup.sh  "$install_prefix" 2` for BRASS skips the exonerate build. (`1` skips all external dependencies).

**Comment by heatherkellyucl** [comment]
Everything has now installed. Made module file `cancerit/20190218-python-2.7.12/gnu-4.9.2` and module bundle `cancerit/20190218`.

Will ask user to test, as I wouldn't be surprised if *something* was missing...

**Comment by heatherkellyucl** [comment]
- [ ] this probably needs putting on the remains of Legion

**Comment by balston** [comment]
Need to add impute2 for Battenberg which isn't currently installed? See IN03948362 for details.

**Comment by balston** [comment]
Impute2 https://mathgen.stats.ox.ac.uk/impute/impute_v2.html#download is only available as binaries. Should be fairly straightforward to install ...

**Comment by balston** [comment]
Impute2 version 2.3.2 installed. Using the dynamic libs version which seems to work. Now to produce a module file ...

**Comment by balston** [comment]
Module installed on Myriad.To use:
```
module load impute2/2.3.2
```

**Comment by balston** [comment]
user informed.

Now install on the other clusters.
