### ISSUE TITLE
Investigate QP Issue with Intel MPI and Mellanox interconnect on Myriad

### ISSUE THREAD

**Issue by ikirker** [UCL-RITS/rcps-buildscripts#247]
Molpro, ANSYS, and StarCD (as well as potentially other packages) that attempt to use Intel MPI on Myriad fail with the following error:

```
libi40iw-i40iw_ucreate_qp: failed to create QP, unsupported QP type: 0x4
```

**Comment by ikirker** [comment]
This may be solvable by disabling specific fabric/interconnect attempts in environment variables (e.g. in the modulefile under cluster detection) or in a config file in the Intel MPI installation prefix.

**Comment by heatherkellyucl** [comment]
Also affected user in IN:03501845 

For Molpro specifically, the workaround would be installing the binary versions without MPI on Myriad if we cannot find what config to change.
