### ISSUE TITLE
Mothur: Install on Myriad [IN03489718] [IN03469661] [IN03503203]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#250]
https://www.mothur.org/ 

Linux version available.

Requested by Institute of Child Health.

**Comment by ikirker** [comment]
This doesn't use MPI, uses Boost and HDF5, and can be downloaded as binaries or source.

It's probably a good idea to just install the binaries if possible.

**Comment by ikirker** [comment]
Installed binaries as Mothur-1.41.3-bindist, on all clusters.
