### ISSUE TITLE
OpenMPI 2.1.5 or 3.1.3

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#252]
IN:03519993

User install requires either OpenMPI 2.1.5 or 3.1.3. Unless there are reasons to do otherwise, probably go for 3.1.3?

**Comment by heatherkellyucl** [comment]
3.1.4 is due imminently and fixes https://github.com/open-mpi/ompi/issues/6285 MPI-IO issues - asked if this will be suitable. (Providing it does get released soon).

**Comment by heatherkellyucl** [comment]
3.1.4 is released! (As is 4.0.1 if we want to try that too).

**Comment by hillary-b** [comment]
gcc build for 3.1.4 has begun on thomas

**Comment by heatherkellyucl** [comment]
GCC and Intel versions of 3.1.4 are built on Thomas and the modulefiles are updated.

Now build on
- [ ] Legion
- [ ] Grace
- [ ] Myriad

**Comment by heatherkellyucl** [comment]
They appear to be working after our pi tests.
Note they need to use `/shared/ucl/apps/openmpi/ucl-wrapper-omp3+/bin` instead of the older UCL wrapper for openmpi so that the options are set correctly for interactive single-node use.

Emailed requestor.
