### ISSUE TITLE
Qt: install a working version of Qt 5.x

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#255]
A number of apps including #243 require Qt 5. The current version we have installed is not working!

**Comment by balston** [comment]
Working on Thomas.

I'm using the binary installer for Qt 5.12.1 to start with (installing in /home/ccaabaa/Scratch/apps/qt/Qt5.12.1 for testing) to find out and install required prerequisites. 

So far I've installed:
- libxcb 1.13 - https://github.com/UCL-RITS/rcps-buildscripts/blob/master/qt-support-libxcb-1.13_install
- xkbcommon 0.8.4 - https://github.com/UCL-RITS/rcps-buildscripts/blob/master/qt-support-xkbcommon-0.8.4_install

Current error when running test is:
```
loaded library "/scratch/scratch/ccaabaa/apps/qt/Qt5.12.1/5.12.1/gcc_64/plugins/designer/libqwebengineview.so"
designer: symbol lookup error: /home/ccaabaa/Scratch/apps/qt/Qt5.12.1/5.12.1/gcc_64/lib/libQt5XcbQpa.so.5: undefined symbol: FT_Get_Font_Format
```
A google search suggests this is because:

> an old version of libfreetype.so.6 is lying around and is being used.

Now need to install an updated libfreetype ...

**Comment by balston** [comment]
I've now installed:
- FreeType 2.9.1 - https://github.com/UCL-RITS/rcps-buildscripts/blob/master/qt-support-freetype-2.9.1_install

**Comment by balston** [comment]
My Qt test installation using the binary GUI installer now appears to be working. I'm now going to attempt a build script to compiler Qt from source.

**Comment by balston** [comment]
Trying a build with:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load xorg-utils/X11R7.7
cd /shared/ucl/apps/build_scripts
./qt-5.12.1-install
```

**Comment by balston** [comment]
Build finished and looking at the make log there doesn't appear to have been any errors. I'm now running some Qt applications to test the build.

**Comment by balston** [comment]
The simple examples I've tried (a sample from /shared/ucl/apps/qt/5.12.1/gnu-4.9.2/examples) appear to work and the qt _designer_ application also is working. I'm now going to upload a suitable module file.

**Comment by balston** [comment]
Module file uploaded. You need to following modules to use Qt 5.12.1:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load xorg-utils/X11R7.7
module load qt/5.12.1/gnu-4.9.2
```

**Comment by balston** [comment]
Done on Thomas?

**Comment by balston** [comment]
Qt 5.12.1 has synced to Michael successfully.

**Comment by ikirker** [comment]
Appears to all be done, closing. If new problems are found, we can open a new issue.
