### ISSUE TITLE
VASP-VTST tools latest version for bugfix

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#256]
IN:03547520

> I would like to request an additional installation of VASP with the 
latest version of the VTST tools by Henkelman et al.
> 
> The reason is that I am running some Dimer calculations with the VTST 
tools in VASP and there seems to be a bug that causes restarted 
calculations to exhibit too high curvatures (way higher than the last 
iteration out of which we restart). Even though this corrects itself 
later in the calculation, it results in computational time being wasted 
in the initial iterations. More on this is described here:
> 
> http://theory.cm.utexas.edu/forum/viewtopic.php?f=2&t=2757&p=9660&hilit=MODECAR#p9660

**Comment by heatherkellyucl** [comment]
Code is in the same place as the existing buildscript, http://theory.cm.utexas.edu/code/vtstcode.tgz and http://theory.cm.utexas.edu/code/vtstscripts.tgz.

Checking if there are any preferences for VASP version or compiler version.

**Comment by heatherkellyucl** [comment]
sha256sum
```
c923a99fe4b4ed2c344088151ff967309d574d63f50ca236aa8fbcad71e8d064  vtstcode.tgz
58dc88c13195fc85091e2ff21a86cb4fca8d651de8780b06dd80828c8b326a2b  vtstscripts.tgz
```

**Comment by heatherkellyucl** [comment]
Installed on:
- [ ] Thomas (sync to Michael overnight)
- [ ] Grace
- [ ] Legion
- [ ] Myriad
- [ ] modulefile created

**Comment by heatherkellyucl** [comment]
Use:
```
module unload compilers mpi
module load compilers/intel/2017/update1
module load mpi/intel/2017/update1/intel
module load vasp/5.4.4-18apr2017-vtst-r178/intel-2017-update1
```
(You *can* run it with other versions of the Intel compiler and MPI modules loaded, but in some situations you can end up with MKL errors from bugs in 2018 then, so it is recommended to use these ones).

**Comment by balston** [comment]
Users have not said it isn't working so closing.
