### ISSUE TITLE
Star CCM+ 13.06.012

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#257]
IN:03548441

Request for Star CCM+ 13.06.012 on Legion. We have 13.02.011.

**Comment by ikirker** [comment]
Don't the relevant users have to provide us with the installation media for this?

**Comment by andreagrechlarosa** [comment]
Hi,

I was the person who requested this.  Happy to provide the installation file if you with me to.

Regards

Andrea

**Comment by balston** [comment]
We now have the installer archive for 13.06.012. I've copied it to Myriad, Grace and Legion in:
```
/home/ccaabaa/Software/STAR-CCM+/STAR-CCM+13.06.012_01_linux-x86_64.tar.gz
```

**Comment by balston** [comment]
Installing on Grace first. As ccspapp:
```
cd ~/Software/STAR-CCM+
 tar -xvf /shared/ucl/apps/STAR-CCM+/installers/STAR-CCM+13.06.012_01_linux-x86_64.tar.gz
cd starccm+_13.06.012
./STAR-CCM+13.06.012_01_linux-x86_64-2.12_gnu7.1.sh
```
This is a GUI (X) installer. Using the following settings:

1. Choose Installation Method: Use Custom (Advanced) as we don't need to
    install the license manager but do need to point to the Mech Eng one. - Next

1. Choose Install Type: Unselect license manager - Next

1. Choose STAR-CCM+ components: Make sure all are selected - Next

1. Select Install Location. Use: _/shared/ucl/apps/STAR-CCM+_ - Next

1. Select Additional Tasks: Unselect "Add application directory to your system
    path" as the module file will set this up - Next

1. Pre-Installation Summary: Check (needs about 8GB) - Install

**Comment by balston** [comment]
Change file ownership to a reserved application:
```
cd /shared/ucl/apps/STAR-CCM+/13.06.012
chgrp -R legstarc *
chmod -R o-rwx *
```
Now only members of the _legstarc_ group can access this version.

**Comment by balston** [comment]
Updating the module file but I will not upload it until I've run some test jobs.

**Comment by balston** [comment]
First test job submitted.

**Comment by balston** [comment]
Oh dear! I forgot to load the module in an interactive login node session first. Now doing it and re-submitting ...

**Comment by balston** [comment]
Test job now starts but fails with:
```
Using existing ~/Scratch/.star-13.06.012-ccaabaa
Using existing ~/Scratch/.star-13.06.012
Starting local server: /shared/ucl/apps/STAR-CCM+/13.06.012/STAR-CCM+13.06.012/star/bin/starccm+ -mpi openmpi -np 32 -machinefile /tmpdir/job/560936.undefined/machines -server -rsh ssh /home/ccaabaa/Scratch/STAR-CCM+_examples/13.06.012/airfoil_bl.sim
Error: Open MPI has returned an error : 
       /shared/ucl/apps/openmpi/1.8.4/intel-2015-update2/bin/mpirun: error while loading shared libraries: libirng.so: cannot open shared object file: No such file or directory
error: Design STAR-CCM+ simulation completed
Server process ended unexpectedly (return code 1)
```
Investigating ...

**Comment by balston** [comment]
After checking the previous install issue it looks like OpenMPI and Intel MPI didn't work last time and so I should be using the supplied IBM Platform MPI. I'm now going to submit my test job using this MPI.

**Comment by balston** [comment]
OK the short test job now works. I'm going to n ow submit a much longer one.

**Comment by balston** [comment]
Long test submitted using _Jet1.sim_:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 561221 2.98041 StarCCM+_P ccaabaa      qw    05/01/2019 16:28:56                                   32
```

**Comment by balston** [comment]
My long test job over 32 cores (2 nodes) has now been running for 18 hours and appears to be outputting results correctly.

**Comment by balston** [comment]
Star CCM+ 13.06.012 install completed on:
- [ ] Grace;
- [ ] Legion;
- [ ] Myriad.

**Comment by andreagrechlarosa** [comment]
Thank you very much.  This will be a great help.

Could you kindly send me the script I should use to run the software please?

Thanks

Andrea

**Comment by balston** [comment]
Grace installation completed. Now installing on the other clusters.

Job script used to run the tests:
```
#!/bin/bash -l

# Batch script to run a parallel STAR-CCM+ job on Grace OS upgrade
# software stack under SGE. 

# STAR-CCM+ Version 13.06.012 using default IBM Platform MPI

# Submit using a qsub command of the form:
#
#   qsub -v simFile=`pwd`/my_input_file run-starccm+.sh
#

# 1. Force bash as the executing shell.
#$ -S /bin/bash

# 2. Request 24 hour(s) of wallclock time (format hours:minutes:seconds).
#    Change this to suit your requirements.
#$ -l h_rt=24:0:0

# 3. Request 2 gigabyte of RAM. Change this to suit your requirements.
#$ -l mem=2G

# 4. Request 15 gigabyte of TMPDIR space (default is 10 GB). Change if needed.
#$ -l tmpfs=15G

# 5. Set the name of the job. You can change this if you wish.
#$ -N StarCCM+_PlatformMPI_Job1

# 6. Merge output and error files
#$ -j y

# 7. Request MPI environment with 32 processors. Change this to suit your requirements.
#$ -pe mpi 32

# 8. Request 1 license per core
#$ -l ccmpsuite=1

# 9. Run from the current working directory which must be in your Scratch area
#$ -cwd

# 10. Load modules needed for STAR-ccm+

module unload mpi
module load star-ccm+/13.06.012

# 11. Run the simulation using IBM Platform MPI

starccm+ -np $NSLOTS -machinefile $TMPDIR/machines -rsh ssh -batch $simFile
```

**Comment by balston** [comment]
Sorry didn't mean to close the issue as installation on Legion and Myriad not finished.

**Comment by balston** [comment]
Installation on Myriad was completed on 3rd May. Installation on Legion started ...

**Comment by balston** [comment]
installation finished and test jobs submitted.

**Comment by balston** [comment]
My test job on Legion was taking too long to queue so deleted and resubmitted as a smaller (16 core) and shorter job.

**Comment by balston** [comment]
Both my test jobs worked so installation on Legion OK. 

Now installed on all clusters where STAR-CCM+ is allowed to be installed.
