### ISSUE TITLE
Caffe: Add Python support [IN03573103]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#261]
Add Python support to the Caffe installations. Set:

WITH_PYTHON_LAYER := 1

in build scripts.

**Comment by owainkenwayucl** [comment]
CPU builds are done and percolating across the systems.  GPU builds on Myriad await a slot in the GPU queue.

**Comment by owainkenwayucl** [comment]
This is now built and deployed for the GPU versions as well.
