### ISSUE TITLE
Install new version of cctools

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#263]
IN:03584272

Parrot connector for cvmfs can't access files via a path that includes a symlink. A different symlink/RHEL 7 issue was fixed in 6.0.2 - possible this one is related?

https://github.com/cooperative-computing-lab/cctools/

Current release is 7.0.11

**Comment by owainkenwayucl** [comment]
Updated to 7.0.11 and contacted user.  We *may* need to update cvmfs as well so awaiting response.

**Comment by owainkenwayucl** [comment]
Right - it looks like this is *not* working:

```
[xxxxxxx@login13 ~]$ module load cctools/7.0.11/gnu-4.9.2
[xxxxxxx@login13 ~]$ parrot_run bash
[xxxxxxx@login13 ~]$ ls /cvmfs/atlas.cern.ch
2019/05/03 11:23:58.20 parrot_run[133510] <child:133667> notice: CVMFS 
requires an http proxy.  None has been configured!
2019/05/03 11:23:58.20 parrot_run[133510] <child:133667> notice: CVMFS 
requires an http proxy.  None has been configured!
2019/05/03 11:23:58.20 parrot_run[133510] <child:133667> notice: CVMFS 
requires an http proxy.  None has been configured!
ls: cannot access /cvmfs/atlas.cern.ch: No such file or directory
```

**Comment by owainkenwayucl** [comment]
OK, so in the module we set `$HTTP_PROXY=DIRECT;` which should be telling it to not use a proxy but it's ignoring the environment variable.

If you do:

```
$ parrot_run --proxy="DIRECT;" bash
```

It works fine.

**Comment by owainkenwayucl** [comment]
I did a quick search in the cctools repo and found this issue:

https://github.com/cooperative-computing-lab/cctools/pull/1853

It looks like for "some time" `HTTP_PROXY` was replaced by `PARROT_HTTP_PROXY`.

Setting the latter fixes the issue.
