### ISSUE TITLE
Build versions of HDF5 and OpenMPI with GNU 7.3.0 [IN03617372]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#268]
GNU 4.9.2 files to compile user's code which works on their laptop with GNU 7.x.

**Comment by ikirker** [comment]
Have built OpenMPI 3.1.4 with GCC 7.3.0, installed on all clusters.

**Comment by ikirker** [comment]
Relevant user code requires HDF5 C library (not C++), and can make use of HDF5's MPI IO support.

(You can't build the C++ bindings and the MPI support at the same time.)

**Comment by hillary-b** [comment]
HDF5 has now been installed on
- [ ] Grace (Installing)
- [ ] Myriad (Installing)
- [ ] Thomas (Installing)
- [ ] Michael (Installing)
- [ ] Legion (Installing)
