### ISSUE TITLE
Install request: sgplib and pyspglib

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#27]
On Legion and Grace. Spglib is a C library for finding and handling crystal symmetries.

http://spglib.sourceforge.net/

IN00865871

**Comment by utf** [comment]
Hi guys, any update on this?

**Comment by heatherkellyucl** [comment]
Looking at this next - do you want 1.7.4.x or 1.9.x as they've renamed the Python wrapper in the new version?

**Comment by utf** [comment]
Great! Version 1.7.4.x is probably best because it needs to interface with some legacy tools. Thanks.

**Comment by heatherkellyucl** [comment]
Tried a local install of pyspglib and it appears to be fine with python2 and 3 so can go in the shared list.

**Comment by heatherkellyucl** [comment]
Spglib built and installed on Legion and Grace. Python2 bundles updated, python3 bundles going.

**Comment by heatherkellyucl** [comment]
Spglib module available as `spglib/1.7.4/gnu-4.9.2` and pyspglib is in `python2/recommended` and `python3/recommended`.

**Comment by utf** [comment]
This is great, thanks!
