### ISSUE TITLE
Platypus(Commit 3e72641)

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#270]
This software is being requested for installation
IN:03647135

**Comment by owainkenwayucl** [comment]
I helped the user install this in their home directory so I can do this centrally.

**Comment by owainkenwayucl** [comment]
The package repo is here: https://github.com/andyrimmer/Platypus

**Comment by owainkenwayucl** [comment]
Installed and contacted user.
