### ISSUE TITLE
Install bamUtil(IN03699017)

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#276]
I have problems installing 'https://genome.sph.umich.edu/wiki/BamUtil#Building'. Is it possible you can help install it in Myriad?

**Comment by hillary-b** [comment]
Test installing must git clone libStatGen: https://genome.sph.umich.edu/wiki/C%2B%2B_Library:_libStatGen

**Comment by hillary-b** [comment]
Must edit `LIB_PATH_GENERAL` variable value in /home/cceahbu/bamUtil-1.0.14/Makefile.inc

Changed `../libStatGen` to `../libStatGen-1.0.14`

**Comment by hillary-b** [comment]
I tried installing 1.0.14 of BamUtil by installing libStatGen first, then BamUtil. Need to check if this has been installed correctly

**Comment by hillary-b** [comment]
User was emailed on 16/07/2019 to find out what issues they were coming across when installing BamUtil themselves. They have still not responded

**Comment by hillary-b** [comment]
After running `makeall` in the bamUtil directory running make install received this error: 
`cp ../bin/bam /usr/local/bin
cp: cannot create regular file ‘/usr/local/bin/bam’: Permission denied
make[1]: *** [install] Error 1
make[1]: Leaving directory `/scratch/home/cceahbu/bamUtil-1.0.14/src'
make: *** [src] Error 2`

Instead ran `make install INSTALLDIR=your_preferred_dir` which seemed to work. Received no errors when running `make test`

**Comment by balston** [comment]
Lets install centrally.

**Comment by hillary-b** [comment]
Started writing a buildscript. Will need to use sed or patch to edit Makefile.inc in bamUtil

**Comment by hillary-b** [comment]
Script has been built and tested install. All looks good so will start installing on the clusters:

- [ ] Myriad
- [ ] Grace
- [ ] Thomas
- [ ] Michael
- [ ] Legion

**Comment by hillary-b** [comment]
User has been informed
