### ISSUE TITLE
Install Request: CFD-ACE+ 2018

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#279]
IN:03714551, file link in IN:03714551

Newer version requested, binaries and instructions sent. Same license server, managed by Mark Iline.

**Comment by heatherkellyucl** [comment]
Have got the installer, putting it in ccspapp's Scratch on Grace.

**Comment by heatherkellyucl** [comment]
It has a GUI installer.

```
ssh -X ccspapp@grace.rc.ucl.ac.uk

cd /dev/shm
tar -xvf /shared/ucl/apps/pkg-store/ACE+Suite-2018.0_Linux-x64.tar
cd ACE2018r0_Linux/
mkdir -p /shared/ucl/apps/CFD-ACE+/2018.0
../INSTALL.SH 
```
You have to run `INSTALL.SH` with `ACE2018r0_Linux/` as the current working directory or it can't find things.
GUI comes up, fill in `/shared/ucl/apps/CFD-ACE+/2018.0` as install location. Currently going.

**Comment by heatherkellyucl** [comment]
`ccspap2` should be in the `lgcfdace` group tomorrow. (Need to check a parallel job works properly, and set the group correctly, currently `ccsp`).

**Comment by heatherkellyucl** [comment]
Group was set to `lgcfdace`.

- [ ] run test job
- [ ] install on Myriad too
- [ ] modulefile

**Comment by heatherkellyucl** [comment]
Have submitted a 32 core job on Grace as `ccspap2` based on `run-cfd-ace-parallel.sh` with a local test modulefile, using `3Dstepchannel_060414.DTF` from Brian.

**Comment by heatherkellyucl** [comment]
Doh.
```
  Request for Parallel failed for process =            1
  Request for Parallel failed for process =            1
  License Error: Unable to obtain license for feature: ACE_PARALLEL
  License Error: Unable to obtain license for feature: ACE
  License Error: Unable to obtain license for feature: PARALLEL
 Please check your license settings.
```

**Comment by heatherkellyucl** [comment]
```
/shared/ucl/apps/CFD-ACE+/2018.0/flexnet/Linux-lsb3_x86_64_2.27/lmutil lmstat -c 7789@ntsrv1.meng.ucl.ac.uk
lmutil - Copyright (c) 1989-2013 Flexera Software LLC. All Rights Reserved.
Flexible License Manager status on Thu 7/4/2019 15:01

License server status: 7789@ntsrv1
    License file(s) on ntsrv1: C:\licences\ACE\license.lic:

    ntsrv1: license server UP (MASTER) v11.11

Vendor daemon status (on ntsrv1):

   pam_lmd: The desired vendor daemon is down. (-97,121)
```

**Comment by heatherkellyucl** [comment]
I'm just checking if the same job with the existing install of CFD-ACE 2014 works.

**Comment by heatherkellyucl** [comment]
I've notified Mark via the ticket.

**Comment by heatherkellyucl** [comment]
License has expired, MechEng are looking into it.

**Comment by balston** [comment]
MechEng have moved the license manager to a different server so we need to update all our installations to point to the  new server.

**Comment by balston** [comment]
Need to update variable  PAM_LMD_LICENSE_FILE in the module files to point to the new host. Doing this for the existing 2014n installation.

**Comment by balston** [comment]
Module file for CFD-ACE 2014 updated and test job submitted on Grace.

**Comment by balston** [comment]
The CFD-ACE 2014 test job ran until it ran out of wallclock (after 24 hours) so it is licensing OK.

Will now update and test the new version with the local module.

**Comment by balston** [comment]
I've updated the test 2018 module and re-submitted the test job as _ccspap2_.

**Comment by balston** [comment]
OK test job ran for its full 12 hours wallclock time and reached time step 53. No license errors so we can assume CFD-ACE 2018 is working on Grace.

**Comment by balston** [comment]
I've added the test module to our module files repository and added it to Grace. I've now submitted a test job from my account using the live module file.

**Comment by balston** [comment]
My job using the live module has started running and has obtained its license so I'm going to inform the user that it is working on Grace.

**Comment by heatherkellyucl** [comment]
Installation on Myriad is proceeding.

**Comment by heatherkellyucl** [comment]
Finished on Myriad and group set.

**Comment by heatherkellyucl** [comment]
Submitted test job from ccspap2 on Myriad: this may be some time.

**Comment by heatherkellyucl** [comment]
Not happy on Myriad:

```
command line = /shared/ucl/apps/CFD-ACE+/2018.0/ACE+Suite/2018.0/Linux_x86_64_2.17/ACE_SOLVER/bin/CFD-SOLVER
 -model 3Dstepchannel_060414.DTF -num 32 -wd /lustre/scratch/scratch/ccspap2/test_cfd-ace/ACE_parallel_32_1405270 -hosts /tmpdir/job/1405270.undefined/machines -decomp -metis -sim 1 -platformmpi -job
node-h00a-009 failed remote execution test
node-h00a-009 failed remote execution test
node-h00a-009 failed remote execution test
...
node-h00a-009 failed remote execution test
Please make sure the authentication key generation has been done properly to enable
passwordless ssh. This is done to enable ssh for MPI communication.
```
That was the parallel launch command rather than the shared memory one, but it ought to degrade better. (All one node, so the only thing to ssh to is itself).

Module is setting `MPI_IC_ORDER upapl:tcp` only.

**Comment by heatherkellyucl** [comment]
Am trying adding `-rsh=ssh` to see if there is any difference.

Can also use `-local` to specify current working directory and current node only.

**Comment by heatherkellyucl** [comment]
Working now! Runline was
```
CFD-SOLVER -model $model -num $NSLOTS -wd `pwd` -hosts $TMPDIR/machines -rsh=ssh -decomp -metis -sim 1 -platformmpi -job
```

**Comment by heatherkellyucl** [comment]
I double-checked that still worked on Grace (yes) so that should be the line to use everywhere.
