### ISSUE TITLE
Install MOOSE [IN03726952]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#283]
https://mooseframework.inl.gov/old/wiki/ClusterInstructions/ClusterSetupMultiUser/

**Comment by heatherkellyucl** [comment]
MOOSE: Multiphysics Object Oriented Simulation Environment
An open source, parallel finite element framework.

Part of the install is building a version of PETSc.

The link above is only about setting up the environment for installing MOOSE and does not include the actual install step itself, see https://mooseframework.inl.gov/getting_started/installation/hpc_install_moose.html instead.

> MOOSE does not use traditional versioning, is under heavy development, and is being updated continuously. Therefore, it is important that you continue to update MOOSE as you use it to develop your application(s), we recommend weekly updates.

No. This is sounding like we may want to install the prereqs and the user maintains their own copy of MOOSE so they can pull down changes.
