### ISSUE TITLE
Install Colmap [IN03734612]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#285]

**Comment by heatherkellyucl** [comment]
https://colmap.github.io/
https://github.com/colmap/colmap

> COLMAP is a general-purpose Structure-from-Motion (SfM) and Multi-View Stereo (MVS) pipeline with a graphical and command-line interface. It offers a wide range of features for reconstruction of ordered and unordered image collections. The software is licensed under the new BSD license.

Looks like we'd need to build it from source - there are packaged versions for Debian and Ubuntu, but no binaries for RHEL/CentOS.

It comes with a python script that theoretically builds all its dependencies, assuming that CMake, Boost, Qt5, CUDA (optional), and CGAL (optional) are already installed on the system. Looks like it might want 1.6x version of Boost, from the example given at https://colmap.github.io/install.html#build-script.
