### ISSUE TITLE
Install Request: DFTb+ 19.1

### ISSUE THREAD

**Issue by lhargreaves95** [UCL-RITS/rcps-buildscripts#286]
Hello,

Please can the latest version of DFTB+ 19.1 be installed on Grace, Thomas and Myriad. 
A link to the source code can be found here: https://www.dftbplus.org/download/dftb-stable/

Thanks,

Laura

**Comment by owainkenwayucl** [comment]
Hi,

I've done this as part of #300 

Cheers,
Owain
