### ISSUE TITLE
Install Request: Tensorflow 1.14

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#287]
IN:03735925

Tensorflow 1.14 requested for eager execution and more new features for training.

`intel-tensorflow` is not yet released for this version.

**Comment by owainkenwayucl** [comment]
I've put the GPU and non-MKL versions on our services - still no sign of the MKL versions.

**Comment by owainkenwayucl** [comment]
I've built and deployed the MKL versions from source.

**Comment by owainkenwayucl** [comment]
I've deployed versions for Python 3.7 as well.  I've not bothered with the base CPU version for these, and probably won't bother going forward?

**Comment by heatherkellyucl** [comment]
There is a problem in that if you `module show tensorflow/1.14.0/gpu` with no python module loaded yourself it says the module loads `python/3.6.3`. You can't see it also works for 3.7.

**Comment by owainkenwayucl** [comment]
Unfortunately that's a problem with how modulefiles work.

For some reason past me made the tensorflow modules load python 3.6.3 rather than depend.  Which is odd.

Perhaps the right thing to do is default to 3.7...

**Comment by owainkenwayucl** [comment]
I've changed the module so that it defaults 3.7

**Comment by heatherkellyucl** [comment]
I mean it should say in the whatis that if you have python 3.6 loaded it will also work, so people can see.
