### ISSUE TITLE
Import Error: 'cannot import _nighresjava'

### ISSUE THREAD

**Issue by mubeenmeo344** [UCL-RITS/rcps-buildscripts#288]
Kindly....guide why this error is occuring..?
This errors occured on first line when I import nighres in python.

**Comment by heatherkellyucl** [comment]
This isn't an install request, so it is better to email rc-support@ucl.ac.uk. (Assuming this question is about running it on UCL's central clusters).

You should say what modules you have loaded. (Environment modules, not python packages).

**Comment by heatherkellyucl** [comment]
This works:
```
module load java/openjdk-11/11.0.1
module load python3/recommended
module load nighres/1.1.0b

python
Python 3.6.3 (default, Oct 10 2017, 15:11:55) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nighres
>>> 
```
If you only load `python/3.6.3` and not one of the python bundles, then typing `python` does not give you the python3 you just loaded, instead you get the system python 2.7.5. You'd need to type `python3` in that case, and can then import nighres successfully.

**Comment by balston** [comment]
User has not responded on here or rc-support so closing.
