### ISSUE TITLE
Install Request: XMDS 2.2.3 [IN03742253]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#289]
New python 2.7 package with extern module is needed in order to install xmds 2.2.3
Error `ImportError: No module named extern` displayed when test install is ran

**Comment by balston** [comment]
Note added from user:

> I just realized that is not a problem of the version, but of the installation. I've tried to compile the examples that can be obtained from the XMDS website. Only the codes which integrate functions of continuous variables compile. If instead it is a function of discrete variables does not compile. My code does not compile for this reason.
> 
> 
> As an example, the following is the message I receive when I try to compile the example "integer_dimensions.xmds" which can be found here http://www.xmds.org/worked_examples.html#integerdimensionexample :
> 
> 
> -------------------------------------BEGIN------------------------------------------
> 
> [ucapcll@login13 xmds_folder]$ xmds2 integer_dimensions.xmds
> xmds2 version 2.2.2 "XMDS2 is a game of two halves" (r2966)
> Copyright 2000-2014 Graham Dennis, Joseph Hope, Mattias Johnsson
> and the xmds team
> Generating source code...
> Traceback (most recent call last):
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds/bin/xmds2", line 6, in <module>
> exec(compile(open(__file__).read(), __file__, 'exec'))
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/bin/xmds2", line 4, in <module>
> sys.exit(parser2.main())
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/parser2.py", line 373, in main
> template.implementationsForFunctionName('preflight')
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_ScriptElement.py", line 326, in implementationsForFunctionName
> childFunctionOutput = child.implementationsForFunctionName(functionName, *args, **KWs)
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_ScriptElement.py", line 326, in implementationsForFunctionName
> childFunctionOutput = child.implementationsForFunctionName(functionName, *args, **KWs)
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_ScriptElement.py", line 326, in implementationsForFunctionName
> childFunctionOutput = child.implementationsForFunctionName(functionName, *args, **KWs)
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_ScriptElement.py", line 319, in implementationsForFunctionName
> functionOutput = function(*args, **KWs)
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/CallOnceGuards.py", line 98, in wrapper
> return f(self, *args, **KWs)
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_UserCodeBlock.py", line 312, in preflight
> super(_UserLoopCodeBlock, self).preflight()
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_UserCodeBlock.py", line 75, in preflight
> self.transformCodeString()
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_UserCodeBlock.py", line 300, in transformCodeString
> self.fixupNonlocallyAccessedComponents()
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/_UserCodeBlock.py", line 195, in fixupNonlocallyAccessedComponents
> for componentName, vector, nonlocalAccessDict, codeSlice in reversed(CodeParser.nonlocalDimensionAccessForVectors(vectorsToFix, self)):
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/CodeParser.py", line 125, in nonlocalDimensionAccessForVectors
> result = nonlocalDimensionAccessForComponents(componentNameToVectorMap.keys(), codeBlock)
> File "/shared/ucl/apps/xmds/2.2.2/gnu-4.9.2/xmds-2.2.2/xpdeint/CodeParser.py", line 156, in nonlocalDimensionAccessForComponents
> accessDict[key] = (' '.join(value[0].asList()), value.slice.start)
> KeyError: 0
> 
> -------------------------------------END------------------------------------------
> 
> 

Need to make sure that 2.2.3 works with this type of example!

**Comment by heatherkellyucl** [comment]
This was a bug that was patched at some point in XMDS: https://sourceforge.net/p/xmds/mailman/xmds-devel/?viewmonth=201701 and https://sourceforge.net/p/xmds/code/2973. Was caused by newer versions of pyparsing altering their `asDict()` layout.
