### ISSUE TITLE
ArcGIS: Upgrade UCL license manager for ArcGIS 10.7

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#290]
The ArcGIS UCL license manager needs to be updated to a later version of the FlexNet software so it will license ArcGIS 10.7 clients. Currently attempting to install/use 10.7 give errors like:

![LM-error](https://user-images.githubusercontent.com/4246274/61534671-23f23380-aa28-11e9-9ad8-83c23c1c0b04.png)

**Comment by balston** [comment]
I've downloaded the latest version of the ArcGIS license manager software for Linux:
```
ArcGIS_License_Manager_Linux_2019_0_169356.tar.gz
```
and copied it to my test license server environment for installation and testing.

**Comment by balston** [comment]
The LM installation and using manual is here:

https://desktop.arcgis.com/en/license-manager/latest/license-manager-installation-and-startup.htm

**Comment by balston** [comment]
Need to make sure these are installed on the server:
```
RHEL Server 6

    cairo.i686
    fuse-libs.i686
    gtk2.i686
    libdrm.i686
    libgcc.i686
    libidn.i686
    libstdc++.i686
    libSM.i686
    libX11.i686
    libXau.i686
    libxcb.i686
    libXdamage.i686
    libXext.i686
    libXfixes.i686
    libXrender.i686
    libXtst.i686
    mesa-libGL.i686
    mesa-libGLU.i686
    polkit.i686 : An authorization framework
    polkit.x86_64 : An authorization framework
    redhat-lsb.i686
```

**Comment by balston** [comment]
Most of the above RPMs are not currently installed on the UCL license server so will need these added before proceeding with installing the new license manager software.

**Comment by balston** [comment]
I've created RemedyForce ticket IN03748498 and assigned it to ISD.IS Hybrid Infrastructure Services.

**Comment by balston** [comment]
I've updated my test license server environment with the additional RPMs. Will now to a trial installation of the new LM.

**Comment by balston** [comment]
Starting the test install:
```
cd ~ccsplma/ArcGIS
tar -xvf ArcGIS_License_Manager_Linux_2019_0_169356.tar.gz
cd LicenseManager_Linux
./Setup
```
This is a GUI installer:

1. ArcGIS License Manager Setup -> Next

1. Master Agreement: Accept License Manager agreement -> Next

1. Select Installation Directory: Use /usr/local/ArcGIS/2019 -> Next

1. Pre-Installation Summary: -> Install

1. The FNP Service will not install successfully at this point so will need to be fixed later.

1. Install Complete: Don't launch the License Server Administrator -> Done.

**Comment by balston** [comment]
IN03748498 has been done so the Live License Server has now had the extra RPMs installed.

**Comment by balston** [comment]
Looking at the FNP Service install script to see if it really needs root access to run. Unfortunately it looks like root is required.

**Comment by GalaxyMergirl** [comment]
Root to run a licence server! Wow... thank you so much for all your hard work on this, though!

**Comment by balston** [comment]
Now trying to install the FNP service on my test VM. As root:
```
cd /usr/local/ArcGIS/2019/arcgis/licensemanager/licensingservice
./install_fnp.sh
```
This produces:
```
 Checking for active FNP Licensing Service Daemon...
FNP Licensing Service Daemon checks complete

Checking for SELinux
*** WARNING: Running with SELINUX enabled can affect the operation of the FlexNet Licensing Service
***          Refer to the FlexNet Publisher Documentation for further details
SELinux checks complete

Checking LSB compatibility...
LSB compatibility checks complete

Installing licensing service from ./FNPLicensingService/FNPLicensingService to /usr/local/share/FNP/service/11.16.2

Checking system for trusted storage area...
Configuring for Linux, Trusted Storage path /usr/local/share/macrovision/storage...
/usr/local/share/macrovision/storage already exists...
Setting permissions on /usr/local/share/macrovision/storage...
Permissions set...


Checking system for Replicated Anchor area...
Configuring Replicated Anchor area...
Creating Replicated Anchor area...
Setting permissions on Replicated Anchor area...
Replicated Anchor area permissions set...
Configuring Temporary area...
Creating Temporary area...
Setting permissions on Temporary area...
Temporary area permissions set...
Setting FUSE configuration
ERROR: FlexNetFs mount-point inaccessible because of /dev/shm file permissions
Licensing Service daemon termination failed


Starting FNPLicensingService daemon owner by brian
Licensing Service daemon activated

Checking FNPLicensingService is running
Configuration completed successfully.
```
Need to check the error...

**Comment by balston** [comment]
I'm not sure about this error as when I look in /dev/shm I get:
```
ls -l /dev/shm
```
```
total 377
dr-xr-xr-x. 3 brian brian     1024 Aug 14 15:13 FlexNetFs.90995
-r--------. 1 gdm   gdm   67108904 Mar 20 14:44 pulse-shm-1041716336
-r--------. 1 brian brian 67108904 Mar 26 17:00 pulse-shm-2042623893
-r--------. 1 brian brian 67108904 Jul 23 11:11 pulse-shm-2411556810
-r--------. 1 brian brian 67108904 Mar 20 14:45 pulse-shm-3103578065
-r--------. 1 brian brian 67108904 Mar 20 14:45 pulse-shm-356573855
-r--------. 1 brian brian 67108904 Mar 20 14:45 pulse-shm-3814078073
```
I may see if I can just start the LM running.

**Comment by balston** [comment]
According to the ArcGIS LM documentation the LM can be started as any user (so we should be able to use _ccsplma_ as normal) using the following command:
```
/usr/local/share/FNP/service/11.16.2/FNPLicensingService -r 2>&1 > /var/log/lm_FNP.log
```

**Comment by balston** [comment]
First created /var/log/lm_FNP.log as follows as _root_:
```
cd /var/log
touch lm_FNP.log
chown ccsplma:ccsplm lm_FNP.log
```
and then as _ccsplma_:
```
/usr/local/share/FNP/service/11.16.2/FNPLicensingService -r 2>&1 > /var/log/lm_FNP.log
```
The log files shows:
```
Licensing Service daemon activated
```

**Comment by balston** [comment]
Done the following using Change Request from last time as a guide:

- The service.txt file in /usr/local/ArcGIS/2019/arcgis/licensemanager/bin needs
to be modified to support passage though departmental firewalls as follows:
```
cd ~/ArcGIS
cp /usr/local/ArcGIS/2019/arcgis/licensemanager/bin/service.txt .
```
Change first line from:
```
        SERVER this_host ANY 27000
```
to:
```
	SERVER this_host ANY 27004
```
Change second line from:
```
        VENDOR ARCGIS
```
to:
```
	VENDOR ARCGIS PORT=27050
```
```
cp service.txt /usr/local/ArcGIS/2019/arcgis/licensemanager/bin
```
- Install options file to change licence borrow timeout and location of
log file.
```
cp options.cfg /usr/local/ArcGIS/arcgis/license10.5/bin/
```
- The options file contains:
```
MAX_BORROW_TIMEOUT 180
BORROW_ENABLED TRUE
ACTIVATION_ENABLED TRUE
AUDIT_LOG_PATH /usr/local/ArcGIS/2019/arcgis/licensemanager/ESRIAudit.log
LMGRD_LOG_FILE /var/log/lm_arcgis_2019.log
```
I now have a ESRI provisioning file for two licenses to apply to the test server.

**Comment by balston** [comment]
Using the two license ESRI provisioning file to add the license to the LM. The process is similar to the that used with the previous version of the LM so as _ccspapp_:
```
cd /usr/local/ArcGIS/2019/arcgis/licensemanager
./SoftwareAuthorizationLS -S -VER 10.7 -LIF  ~/ArcGIS/ArcGISDesktopAdvanced_ConcurrentUse_790059.prvs
```

**Comment by balston** [comment]
We will need to use a second provisioning file to add the license for ESRI City Engine.

**Comment by balston** [comment]
I've updated the LM start, stop and check scripts from the previous versions and installed them:
```
cd /usr/local/ArcGIS
cp ~/ArcGIS/start-arc-2019 .
cp ~/ArcGIS/stop-arc-2019 .
cp ~/ArcGIS/check-arcgis-2019 .
```

**Comment by balston** [comment]
Trying to start the LM with:
```
./start-arc-2019
```

**Comment by balston** [comment]
Looks like it is running! 

I will now try and run ArcGIS from my Windows 10 VM using the new LM.

**Comment by balston** [comment]
My Windows 10 VM is not seeing the License Manager at the moment. I'm getting the error:
```
"10.211.55.4" does not have a valid License Manager ...
```
However when I check on the license server system there are two licenses available.

**Comment by balston** [comment]
I had forgotten to open the following ports on my test server:
```
-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 27004 -j ACCEPT
-A RH-Firewall-1-INPUT -m state --state NEW -m tcp -p tcp --dport 27050 -j ACCEPT
```

**Comment by balston** [comment]
ArcMAP 10.5 now licenses correctly. Will now download and install the latest 10.7 ArcGIS and test...

**Comment by balston** [comment]
ArcGIS Desktop 10.7.1 installed on my test Windows VM. ArcMAP 10.7.1 also licenses correctly.

**Comment by balston** [comment]
Next steps: 
- update the boot-script.sh and install in _/etc/rc.d/init.d_. As _root_:
```
cd /etc/rc.d/init.d
cp /home/ccsplma/ArcGIS/boot-script.sh arcgis2019lm
chmod -c 700 arcgis2019lm
chown ccsplma:ccsplm arcgis2019lm
/sbin/chkconfig --add arcgis2019lm
```
- make sure FNP service is started at boot time using recommended crontab method. Adding the following to ccsplma's crontab:
```
@reboot /usr/local/share/FNP/service/11.16.2/FNPLicensingService -r 2>&1 > /var/log/lm_FNP.log
```
Re-booting my server VM to test ...

**Comment by balston** [comment]
After re-boot I'm getting the following error:
```
12:03:11 (ARCGIS) Activation error (-208,61027:13) Trusted storage could not be saved. 
```
Looking on ESRI's web site for a solution.

**Comment by balston** [comment]
I tried stopping the license manager, waiting for the TCP ports to clear, and then restarting it. The LM  started up without the error and two license are again available. Started ArcMAP on Windows without error.

Not sure what this means!

**Comment by balston** [comment]
Provisioning files for the live server. In fact four not two are needed:

1) ArcGIS Desktop with 1000 seats

ArcGISDesktopAdvanced_ConcurrentUse_791030_Aug-2019.prvs

2) ArcGIS City Engine with 500 seats

EsriCityEngineAdvanced_ConcurrentUse_791032_Aug-2019.prvs

3) ArcGIS Pro with 1000 seats

ArcGISProAdvanced_ConcurrentUse_791034_Aug-2019.prvs

4) ArcGIS Server Advanced

ArcGISGISServerAdvanced_ArcGISServer_791037_Aug-2019.prvc

**Comment by balston** [comment]
I've now written up the installation details to go in the Change Request to update the ArcGIS LM on the live UCL wide license server. Hopefully to be installed about the middle of next week.

**Comment by balston** [comment]
Change Request CR00005334 raised to install new LM on UCL live license server on Wednesday morning pending approval by UCL Change Management.

**Comment by balston** [comment]
Change request has been approved.

**Comment by balston** [comment]
The license manager has been updated and restarted. All looking good so far.

I'm going to do a 10.7.1 install on my laptop to confirm that the new version of ArcGIS is now supported by the LM.

**Comment by balston** [comment]
My 10.7.1 install is working and I've successfully run ArcMap!

Emailed IT Managers.
