### ISSUE TITLE
Install Request: NetLogo

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#291]
IN:03745533

https://ccl.northwestern.edu/netlogo/download.shtml
https://github.com/NetLogo/NetLogo/releases
Is GPL

How to run without GUI: http://ccl.northwestern.edu/netlogo/docs/faq.html#can-i-run-netlogo-from-the-command-line-without-the-gui

**Comment by owainkenwayucl** [comment]
As our local logo enthusiast I'll take this one.

I think I want to do a source build as the binaries have a random JRE included and the license of that is unclear in the new Oracle license land.

It looks like I need to do a JavaFX install for the OpenJDK8s.

**Comment by owainkenwayucl** [comment]
(the bundled JRE appears to be Oracle 7 which should be so old it's not affected by the license issue)

**Comment by owainkenwayucl** [comment]
https://github.com/NetLogo/NetLogo/issues/1767

**Comment by owainkenwayucl** [comment]
Right - it *builds* on an ancient "old license" version of 1.8.

**Comment by owainkenwayucl** [comment]
Looking at the provided binaries, this will be a problem anyway:

```
[ccspapp@login12 NetLogo 6.1.0]$ ldd NetLogo
./NetLogo: /shared/ucl/apps/gcc/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./NetLogo)
	linux-vdso.so.1 =>  (0x00007ffc573c4000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2af97bd000)
	libstdc++.so.6 => /shared/ucl/apps/gcc/4.9.2/lib64/libstdc++.so.6 (0x00007f2af94b2000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2af91b0000)
	libgcc_s.so.1 => /shared/ucl/apps/gcc/4.9.2/lib64/libgcc_s.so.1 (0x00007f2af8f99000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2af8bd5000)
	/lib64/ld-linux-x86-64.so.2 (0x000055c1966f6000)
````

**Comment by owainkenwayucl** [comment]
OK, playing about we can nuke all the 64 bit elf binaries + the runtime in lieu of using a shell script to launch based on `netlogo-headless.sh` and our install of AdoptOpenJDK.

This seems to work and I've successfully run a few examples in the GUI on Myriad.

**Comment by owainkenwayucl** [comment]
Deployed everywhere.

**Comment by owainkenwayucl** [comment]
User contacted.

**Comment by owainkenwayucl** [comment]
The user has not responded but I've verfied fairly comprehensively that this is working.
