### ISSUE TITLE
Install Request: BoltzTraP

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#292]
IN:03750239

(Not BoltzTraP2 which is Python).

https://www.imc.tuwien.ac.at/forschungsbereich_theoretische_chemie/forschungsgruppen/prof_dr_gkh_madsen_theoretical_materials_chemistry/boltztrap/
Instructions here for Intel and how to test with one of the examples: https://www.mail-archive.com/wien@zeus.theochem.tuwien.ac.at/msg11850.html

Appears to work for GNU with no changes.
1) wget https://owncloud.tuwien.ac.at/index.php/s/s2d55LYlZnioa3s/download
2) tar xvf download
3) cd boltztrap-1.2.5
4) cd src
5) module unload compilers mpi
module load compilers/gnu/4.9.2
module load openblas/0.2.14/gnu-4.9.2
6) make

**Comment by owainkenwayucl** [comment]
Right.  I'll try this with Intel 2018 and if it fails fall back to GFortran.

**Comment by owainkenwayucl** [comment]
Of course I'm getting numerical inconsistencies with the Intel compiler because it is the Intel compier.

**Comment by owainkenwayucl** [comment]
Versions compiled with GNU Fortran produce no output (just timing output):

```
[ccspapp@login13 CoSb3]$ ../../src/x_trans BoltzTraP
 ================ BoltzTraP vs 1.2.5 =============
37.500u 14.103s 0:41.31 124.9%  0+0k 0+31216io 0pf+0w
```

Compiled with ifort 2018:
```
[ccspapp@login13 CoSb3]$ ../../src/x_trans BoltzTraP
 ================ BoltzTraP vs 1.2.5 =============
 CoSb3                                                                          
  XXXXXXXX
   1.09124078584050       7.469009471863329E-002  5.000000000000000E-004 npoints
        2034
Doping level number     1 n =  0.100E+21 carriers/cm3
  Doping corresponds to   3.691981999400772E-002  excess holes per unit cell
Doping level number     2 n = -0.100E+21 carriers/cm3
  Doping corresponds to  -3.691981999400772E-002  excess electrons per unit cell
72.488u 13.693s 0:36.55 235.7%  0+0k 0+31216io 0pf+0w
```

**Comment by owainkenwayucl** [comment]
Deployed -fp-model precise intel version.

**Comment by owainkenwayucl** [comment]
User notified.
