### ISSUE TITLE
Quantum Espresso: Add thermo_pw.x to 6.1 or 6.3 [IN03755912]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#293]

**Comment by owainkenwayucl** [comment]
This appears to be this: https://dalcorso.github.io/thermo_pw/thermo_pw_help.html

**Comment by owainkenwayucl** [comment]
I looks to me like we want this to be a separate install with thermo_pw in it?

**Comment by owainkenwayucl** [comment]
Gonna take a look at this - first to check to see if 6.3 builds by itself.

**Comment by owainkenwayucl** [comment]
Test builds pass tests but somehow `thermo_pw.x` breaks `make install` (it doesn't copy anything).

Made my scripts do manual install and am installing on Kathleen as test.

**Comment by owainkenwayucl** [comment]
Deploying 6.3 + 1.0.9 and 6.5 + 1.2.1 on everything.

**Comment by owainkenwayucl** [comment]
Done.

**Comment by owainkenwayucl** [comment]
User contacted.
