### ISSUE TITLE
Install Request: Python dependencies [IN03768177]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#296]
List of all dependencies required:
- [x] python 3.7.3 
- [x] pytorch 1.1.0
- [x] pillow-simd 5.3.0.post1
- [x] pandas 0.24.2
- [x] scipy 1.2.1
- [x] numpy 1.16.2
- [x] scikit-learn 0.20.3

**Comment by owainkenwayucl** [comment]
OK, most of this stuff is under the python 37 bundle.  I should update that to 3.7.4 before we roll it out anyway.

**Comment by owainkenwayucl** [comment]
I've installed python 3.7.4

**Comment by owainkenwayucl** [comment]
OK, if I bump the version number of the packages built by the python37 script I can build a new version without breaking the existing one, then roll out the modules.  I've bumped it to 4.0.1 and made a note in the script.

**Comment by owainkenwayucl** [comment]
OK, the Python 3.7 bundle is now using 3.7.4.

**Comment by owainkenwayucl** [comment]
Looks like pillow simd probably gets in the way of pillow so I'll install that in its own thing.

**Comment by spoonerf** [comment]
I'm not sure if this will be useful to you but I had some issues installing pillow simd for use on this project and found that this worked:

pip3 install -U --force-reinstall pillow-simd --global-option="build_ext" --global-option="--disable-zlib" --global-option="--disable-jpeg"

**Comment by owainkenwayucl** [comment]
@spoonerf do you need 5.3.0.post1 or is 6.0.0.post0 OK?

**Comment by owainkenwayucl** [comment]
(I've installed 6.0.0.post0)

**Comment by owainkenwayucl** [comment]
I've installed PyTorch 1.2.0 for both cpu and gpu.

**Comment by spoonerf** [comment]
> @spoonerf do you need 5.3.0.post1 or is 6.0.0.post0 OK?

Hi Owain, I can't check right now but will let you know tomorrow - thanks for installing eveything!!

**Comment by spoonerf** [comment]
> > @spoonerf do you need 5.3.0.post1 or is 6.0.0.post0 OK?
> 
> Hi Owain, I can't check right now but will let you know tomorrow - thanks for installing eveything!!

Hi Owain,  All checked and 6.0.0.post0 works great - thanks again!

**Comment by owainkenwayucl** [comment]
No problem - good luck with your research!

**Comment by heatherkellyucl** [comment]
Problem: the pytorch buildscript pip installs the `typing` backport package when that has been in the standard library since 3.5 - this causes a conflict.

Error:
```
  File "/shared/ucl/apps/pytorch/1.2.0/python3.7.4/cpu/lib/python3.7/site-packages/typing.py", line 1005, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
```
Buildscript does:
```
pip3 install future numpy pyyaml setuptools six typing
```
Requirements should be of the form `'typing; python_version < '3.5'` so they don't require it for newer pythons.
https://github.com/python/typing/issues/573#issuecomment-405986724

**Comment by owainkenwayucl** [comment]
Well that's annoying.  I blame the pytorch installation instructions.

**Comment by owainkenwayucl** [comment]
(fixing now)

**Comment by owainkenwayucl** [comment]
This should be sorted now.

**Comment by spoonerf** [comment]
Looks like it's working perfectly now, thank you!

**Comment by owainkenwayucl** [comment]
@spoonerf : just a quick note - due to how I've installed the packages, if you want to use pillow-simd with pytorch, you should load the pytorch module first, and then pillow-simd.

This will cause pillow-simd to override the pillow module in pytorch:

```
Thomas [login03] ~ ☻ ➤ module load pytorch/1.2.0/cpu
Thomas [login03] ~ ☻ ➤ python3
Python 3.7.4 (default, Aug 22 2019, 10:19:22) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> print(PIL.__version__)
6.1.0
>>> 
Thomas [login03] ~ ☻ ➤ module load pillow-simd
Thomas [login03] ~ ☻ ➤ python3
Python 3.7.4 (default, Aug 22 2019, 10:19:22) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> print(PIL.__version__)
6.0.0.post0
>>> 
```
