### ISSUE TITLE
Install Request: Matlab 2019b [IN03770477]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#297]

**Comment by balston** [comment]
I suggest waiting for R2019b which should be released in September.

**Comment by balston** [comment]
Matlab R2019b was released to UCL on the 18th September. We can now proceed with installing R2019b.

**Comment by balston** [comment]
I've downloaded the three platform network installers for R2019b and copied them to Myriad in:
```
~ccaabaa/Software/R2019b/
```

**Comment by balston** [comment]
NOTE: Before installing or using the R2019b versions we need to update the UCL license manager with a new license file that supports R2019b.

**Comment by balston** [comment]
The UCL Matlab License Manager has now been updated to support R2019b so installation can proceed.

**Comment by balston** [comment]
Downloading the full (ie huge) Linux install files to:
```
~ccaabaa/Scratch/Software/Matlab/R2019b_Linux
```
on Myriad. It may take some time ...

**Comment by balston** [comment]
That was quicker than usual all 13+ GB downloaded in 10 minutes!

Next step is to run a silent install from the _ccspapp_ account. However need to configure an installer file first.

**Comment by balston** [comment]
Running the silent installer as follows:
```
cd ~ccaabaa/Scratch/Software/Matlab/R2019b_Linux
./install -inputFile /home/ccaabaa/Scratch/Software/Matlab/R2019b_Linux/install_myriad.txt
```

**Comment by balston** [comment]
The installer has finished without errors.

**Comment by balston** [comment]
Re-running to install the Parallel Compute Server:
```
./install -inputFile /home/ccaabaa/Scratch/Software/Matlab/R2019b_Linux/install_myriad_PCS.txt
```

**Comment by balston** [comment]
Finished again without errors. The  MATLAB Parallel Server is the new name for the Distributed Computing Server. It may need different configuration from the DCS so will need to check:
```
(Oct 11, 2019 15:24:30) Installing Product: MATLAB Parallel Server
(Oct 11, 2019 15:25:12) Notes:
Your installation may require additional configuration steps.

1. After this installation is complete, you should continue with your configuration of the MATLAB Parallel Server as outlined in the instructions obtained from www.mathworks.com/distconfig.
(Oct 11, 2019 15:25:12) Exiting with status 0
(Oct 11, 2019 15:25:13) End - Successful.
Finished
```

**Comment by balston** [comment]
Module file updated. Now to run some tests on Myriad using the following module commands:
```
module load xorg-utils/X11R7.7
module load matlab/full/r2019b/9.7
```

**Comment by balston** [comment]
Three example jobs submitted:
- [ ] Simple multi-threaded job;
- [ ] Job using the NAG toolbox for Matlab;
- [ ] Example GPU job.

**Comment by balston** [comment]
OK I forgot an important step needed to make the NAG toolbox available - modify:
```
/shared/ucl/apps/Matlab/R2019b/full/toolbox/local/matlabrc.m
```
to add the path to the NAG toolbox.

**Comment by balston** [comment]
```
cd /shared/ucl/apps/Matlab/R2019b/full/toolbox/local
cp matlabrc.m matlabrc.m_15102019
chmod u+w matlabrc.m
cp ~ccaabaa/Software/Matlab/matlabrc.m .
```

**Comment by balston** [comment]
Basic Matlab R2019b working on:
- [ ] Aristotle;
- [ ] Myriad;
- [ ] Legion.

**Comment by balston** [comment]
I'm informing the requester in case they want to submit simple Matlab jobs.

Next I will repeat the installation on Legion and Aristotle. And then will sort out the remote job submission stuff.

**Comment by balston** [comment]
Installer files have been copied from Myriad to Legion. I'm now running the two install commands on Legion.

**Comment by balston** [comment]
Finished running:
```
cd ~ccaabaa/Scratch/Software/Matlab/R2019b_Linux
./install -inputFile /home/ccaabaa/Scratch/Software/Matlab/R2019b_Linux/install_legion.txt
./install -inputFile /home/ccaabaa/Scratch/Software/Matlab/R2019b_Linux/install_legion_PCS.txt
```
on Legion. No errors so going to test.

**Comment by balston** [comment]
I've also started working on the remote job submission stuff. The initial download of Grid Engine support package has been installed on:
```
C:\ProgramData\MATLAB\SupportPackages\R2019b\parallel\gidengine
```
on a clean install of R2019b on my Windows Laptop.

**Comment by balston** [comment]
Tests on Legion successful.

**Comment by balston** [comment]
I've made a first attempt at the remote job submission scripts for Myriad and I'm now testing them.

**Comment by balston** [comment]
My tests on Friday didn't work. I think this was because I had forgotten to make Matlab reference the correct MPI implementation. I'm now fixing this and will then try the test again.

**Comment by balston** [comment]
Need to run:
```
cd /shared/ucl/apps/Matlab/toolbox_local/Legion/
mkdir R2019b
cd R2019b
cp ~ccaabaa/Software/Matlab/mpiLibConf.m .
```

**Comment by balston** [comment]
Validation still not working ...

**Comment by balston** [comment]
I've found that the _/shared/ucl/apps/Matlab/toolbox_local/Legion/R2019b_ directory was missing from the Matlab search path. Adding it in and them will try the validation again.

**Comment by balston** [comment]
Four of the five validation tests are now working (was only 2 before). The test that is failing is the interactive "Parallel pool test".

**Comment by balston** [comment]
I've submitted a real test job from my Windows laptop and this has worked successfully. I will now upload the support files and profile creation script to our Wiki and then test from a different system (MacBook Pro).

**Comment by balston** [comment]
I've now tested job submission successfully from my MacBook Pro.

**Comment by balston** [comment]
Installing R2019b on:
- [ ] Grace;
- [ ] Kathleen.

**Comment by balston** [comment]
Also need 2018b on:
- [ ] Kathleen.

**Comment by balston** [comment]
Used my old iMac for testing job submission from R2018b to Kathleen. Placed updated support files for R2018b on Kathleen in my Dropbox/Software/Matlab folder.

**Comment by balston** [comment]
Kathleen support files sent to IN04043149.
