### ISSUE TITLE
Install Request: Vesta [IN03797683]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#301]
http://jp-minerals.org/vesta/en/download.html

**Comment by ikirker** [comment]
Hmmm... This comes as a compiled binary, but I'm not convinced the binary package is working correctly.

![Screenshot 2019-09-03 at 15 33 29](https://user-images.githubusercontent.com/479061/64182516-41585100-ce60-11e9-976c-2f462bc1ba44.png)

**Comment by ikirker** [comment]
Plus it's unusably slow.

**Comment by ikirker** [comment]
Okay, perhaps it was just that one cube file that was broken -- a new one with just some water and the electron density seems to render properly. It's still very slow, but there's not a lot we can do about that.

**Comment by ikirker** [comment]
Installed everywhere.

**Comment by ikirker** [comment]
Contacted requester.
