### ISSUE TITLE
Install Request: OpenFoam 7 [IN03817417]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#307]
https://openfoam.org/release/7/

**Comment by hillary-b** [comment]
Creating buildscript

**Comment by hillary-b** [comment]
Development of build script has resumed

**Comment by hillary-b** [comment]
Working on setting up correct environment in the buildscript. Still getting errors

**Comment by hillary-b** [comment]
Allwmake error: The OpenFOAM environment is not set.
    Check the OpenFOAM entries in your dot-files and source them.
    If in doubt, please read:
       http://openfoam.org/download/source/setting-environment

**Comment by owainkenwayucl** [comment]
Yeah - that does look like the problem I was running into.

You could try sourcing the file source `$HOME/OpenFOAM/OpenFOAM-dev/etc/bashrc` (changing the location to wherever the build is happening) before that step?

**Comment by hillary-b** [comment]
patching file bashrc
Hunk #1 FAILED at 42.
Hunk #2 FAILED at 63.
Hunk #3 FAILED at 81.
3 out of 3 hunks FAILED -- saving rejects to file bashrc.rej
