### ISSUE TITLE
Install Request: Gromacs 2018 with Plumed 2.5

### ISSUE THREAD

**Issue by aaronrfinney** [UCL-RITS/rcps-buildscripts#308]
Application: Gromacs 2018 (or even 2019) with Plumed 2.5

Cluster: Myriad

Description: A bug fix in Plumed 2.5 which sets the correct number of threads for Plumed. Previous versions of Plumed ran on a single thread even in multi-threaded jobs. The most recent version of Gromacs/Plumed on Myriad suffers with this problem. I did a local build of Plumed 2.5.1 and Gromacs 2018.6 and this gives much better performance as Plumed runs correctly!

License: open source

Ticket number: IN:03918994

**Comment by owainkenwayucl** [comment]
Since I've just done 2.5.2 on NAMD I might as well do this.

**Comment by owainkenwayucl** [comment]
Doing 2019.3 since we have that and plumed 2.5.2 doesn't support our version of 2018.

**Comment by owainkenwayucl** [comment]
Deployed, user contacted.

**Comment by aaronrfinney** [comment]
Cheers Owain.
