### ISSUE TITLE
Install Request: ORCA 4.1

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#309]
IN:03924239

Main page: ~~https://www.its.hku.hk/services/research/hpc/software/orca~~ (IK Edit: that appears to be the support page for ORCA on HKU's own docs pages. ORCA is not affiliated with HKU as far as I am aware, and the forum site appears to be the actual main site.)
User guide: https://cec.mpg.de/fileadmin/media/Forschung/ORCA/orca_manual_4_0_1.pdf
Forum: https://orcaforum.kofo.mpg.de/app.php/portal

Once registered for their forums there is a license questions sticky:

> 3) Computer centers at academic institutions with only academic users
>
> You can, of course, install ORCA. However, we ask that all of the academic computer center users are registered individually and have agreed to the EULA individually.
> To this end, our download page will, starting tomorrow 21.3.2017, send a confirmation e-mail that makes it easier for the computer center to check that a given user really is a registered ORCA user before providing access to it.

So we will need a central restricted group and give access based on those confirmation emails. (Once groups are working again).

**Comment by ikirker** [comment]
Adding `legorca`:

```
$ addgroup ccspapp legorca
Before split: ccspapp : ccsp legcryst legg03 legtmole legvasp legg09 legcesm lgdlp408 legstarc leggatk legcpmd legg16 legadf legcomsl legabq lgmolpro

ccspapp:
        Existing groups:        ccsp legcryst legg03 legtmole legvasp legg09 legcesm lgdlp408 legstarc leggatk legcpmd legg16 legadf legcomsl legabq lgmolpro
        New groups:             legorca

        Primary group: ccsp

Checking group [legorca] ...
        ** WARNING this is a new group - make sure you mean this!

register: ccspapp - request submitted

```

**Comment by hillary-b** [comment]
New request from IN04066431

**Comment by balston** [comment]
New request from IN04330921

**Comment by balston** [comment]
IN04330921 wants it on Kathleen.

**Comment by ikirker** [comment]
Installed everywhere (except Legion and Grace, which are still down).

**Comment by ikirker** [comment]
Needs a note in the wiki about conditions for being added to `legorca` access group.

**Comment by heatherkellyucl** [comment]
Done in Sept.
