### ISSUE TITLE
Install request: Hammock 1.0.4

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#31]
IN00937227

http://www.recamo.cz/en/software/hammock-cluster-peptides/

This program works in combination with clustal-omega, hmmer and HHsuite. (Comes with compiled versions, but strongly recommends you to build your own).

**Comment by heatherkellyucl** [comment]
The pre-built version works fine, but is a 7z file so I need to install p7zip.

**Comment by heatherkellyucl** [comment]
Module is `p7zip/15.09/gnu-4.9.2`

**Comment by heatherkellyucl** [comment]
Built HHSuite, but some of the scripts that come with it require you to give it the location of PSIPRED

http://bioinf.cs.ucl.ac.uk/software_downloads/
http://bioinfadmin.cs.ucl.ac.uk/downloads/psipred/

Not sure installing PSIPRED centrally is the best idea, as you also need to edit its runpsired script and tell it where the database and data files you are using are. Seems more geared to individual user installs.

**Comment by ikirker** [comment]
Calling a limiter on additional dependencies on this: if people need additional dependencies we can advise on installing them in home directories.

**Comment by ikirker** [comment]
(And check what's already installed and close this.)

**Comment by heatherkellyucl** [comment]
Modules we have are:

* `clustal-omega/1.2.1`
* `hmmer/3.1b2`
* `hhsuite/3.0-beta.1/gnu-4.9.2`

I just made sure hhsuite (without PSIPRED) was built on Grace as well, as it wasn't before.

Need to install Hammock itself.

**Comment by heatherkellyucl** [comment]
It looks like Hammock doesn't work with the HHSuite 3.0 module (at least not with the options it is passing). It does work with the external clustal-omega and hmmer and the hhsuite-2.0.16 that comes with Hammock, so I'll do a module that uses those. 

Output - that first tmp directory doesn't exist (and appears to be the original src directory).
```
HH clustering...
While running hhsearch for cluster 60 [hhsearch stderr]: - 16:35:54.565 ERROR: In /dev/shm/tmp.T0Ztrmz7Ix/hhsuite-3.0-beta.1/src/hhdatabase.cpp:35: FFindexDatabase:
While running hhsearch for cluster 60 [hhsearch stderr]: 
While running hhsearch for cluster 60 [hhsearch stderr]: - 16:35:54.565 ERROR:  could not open file '/dev/shm/Hammock_temp_1464017750245/hhsearchOut/60.pal_cs219.ffdata'
```

.log file
```
2016-05-23 16:32:34.812:        HH clustering...
2016-05-23 16:32:34.820:        Error. Run with --help for a brief description of command line parameters. Trace: 

2016-05-23 16:32:34.822:        java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.io.IOException: java.io.FileNotFoundException: /dev/shm/Hammock_temp_1464017549596/hhsearchOut/130.res (No such file or directory)
```

**Comment by heatherkellyucl** [comment]
There's also a problem that you need to specify Hammock's tempDirectory in the settings.prop file. (I was using /dev/shm above). You don't appear to be able to use environment variables in there, or ~. That means you can't tell it to use $TMPDIR or the user's Scratch. It uses /tmp by default which will fill it up. 

This is looking increasingly like the whole of Hammock may need to remain as a user install. I can make an easy-install script for it instead.

**Comment by heatherkellyucl** [comment]
I was thinking of giving an option on the wiki page to write to `/tmp` on the node and include a line in the example jobscript clearing that up at the end, as you might theoretically get two jobs trying to create the temp directory at exactly the same time, and you'd also have unnecessary writing to Scratch if you don't want to keep the temp files. But that isn't going to work if there is more than one job running on the same node, as you don't know which temp directory belongs to which job (and the cleaning up wouldn't happen if the job failed, either). So Scratch it is.

**Comment by heatherkellyucl** [comment]
User install script and associated modulefile are done.

- [ ] write wiki page

**Comment by heatherkellyucl** [comment]
Wiki page includes a working example script using the provided musi.fa.
