### ISSUE TITLE
Install Request: STAR 2.7.2d

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#310]
IN:03925503

Updated version with better functionality. We currently have 2.5.2a.

https://github.com/alexdobin/STAR

**Comment by balston** [comment]
Latest version is 2.7.3a so installing this one.

**Comment by balston** [comment]
Updating build script ...

**Comment by balston** [comment]
Build script updated now running as ccspapp:
```
cd /shared/ucl/apps/build_scripts/./star-2.7.3a_install
```

**Comment by balston** [comment]
Module updated:
```
module load star/2.7.3a
```

**Comment by balston** [comment]
Requester informed.

Now installing everywhere:
- [ ] Aristotle;
- [ ] Grace;
- [ ] Kathleen;
- [ ] Legion;
- [ ] Michael;
- [ ] Myriad;
- [ ] Thomas.

**Comment by balston** [comment]
Waiting for Aristotle sync to be fixed - out of disk space again!

**Comment by balston** [comment]
All done.
