### ISSUE TITLE
Installing OPTIMET on Myriad [Ref:IN:04020201]

### ISSUE THREAD

**Issue by sekulicivan7** [UCL-RITS/rcps-buildscripts#319]
I am trying to install the in-house developed software OPTIMET (developed by prof. Panoiu's group here at UCL) in my Scratch folder at Myriad, following the instructions given at

https://github.com/OPTIMET/OPTIMET
. It is important that the MPI option is enabled (ON) when installing, so I run the following command:

cmake -DCMAKE_BUILD_TYPE=Release -Ddompi=ON -Ddotesting=OFF -Ddobenchmarks=OFF ..

However, I get the error which is attached. Could you please help me with the installation?

Thanks in advance,

Ivan Sekulic
[CMakeOutput.log](https://github.com/UCL-RITS/rcps-buildscripts/files/3932812/CMakeOutput.log)

**Comment by owainkenwayucl** [comment]
Hmm.  When I run the cmake line above I get an error about HDF5 - doing some testing and will get back to you.

**Comment by owainkenwayucl** [comment]
Ugh.  Now it wants f2c.

**Comment by owainkenwayucl** [comment]
Right.  Got past the cmake stage.

Now the issue is that at compile time it's messing up the MKL link line so Scalapack can't find symbols from BLACS.

**Comment by owainkenwayucl** [comment]
I've opened a ticket here because I think this is somewhat beyond my C++ knowledge: https://github.com/OPTIMET/OPTIMET/issues/104

**Comment by owainkenwayucl** [comment]
I've had some success building this with GCC.  This requires that you build your own Scalapack + BLACS which is somewhat more annoying than it should be but I've managed to do a test build in ccspapp's home directory.

I think the correct thing here is to do a Scalapack for GCC 4.9.2 + OpenMPI 3.1.4 module and then use that to build a module for Optimet.

**Comment by owainkenwayucl** [comment]
Deployed.

```
module load compilers/gnu/4.9.2 mpi/openmpi/3.1.4/gnu-4.9.2 hdf/5-1.10.5/gnu-4.9.2 gsl/1.16/gnu-4.9.2 openblas/0.3.7-serial/gnu-4.9.2 scalapack/2.0.2/gnu-4.9.2/openblas-0.3.7 optimet/1.0.1
```

**Comment by owainkenwayucl** [comment]
User notified.

**Comment by owainkenwayucl** [comment]
Based on work I've done elsewhere, (https://github.com/owainkenwayucl/OptiMate) to make OPTIMET generally more buildable for developers on UCL resources, I've updated the build scripts and am deploying with Belo compiled in on all UCL resources.
