### ISSUE TITLE
Install Request: Nonmem 7.3 [IN04026001]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#321]
Latest compilers required

**Comment by balston** [comment]
I did the original build back in 2015 and there is no build script so I had better take on doing this. Note original issue here:

https://github.com/UCL-RITS/research-computing/issues/376

**Comment by balston** [comment]
Before starting this we need to update the NONMEM license files as the current license expires on 14th Jan! UCL has paid for the renewal and new license files were emailed to us on 1st Jan.

**Comment by balston** [comment]
This turned out to be a slightly different problem: What modules are needed to build the latest PsN and have a working NONMEM. They are:
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load perl/5.22.0
module load atlas/3.10.2/gnu-4.9.2
module load mpi/intel/2015/update3/gnu-4.9.2
module load nonmem/7.3.0/gnu-4.9.2
```
PsN then builds correctly.
