### ISSUE TITLE
Install Request: CASTEP 19.1.1 [IN04060787]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#323]

**Comment by ikirker** [comment]
We've already arranged for our group to be licensed for this (last week), and I've got access to the CASTEP Bitbucket Mercurial repo -- the 19.1.1 source release is already downloaded and in `/shared/ucl/apps/pkg-store`, group-restricted.

I still have to check whether there's still a pseudopotential bundle to go with it, and if so, where that is available from now.

I've been looking at the options around building it and there are still some unanswered questions about libxc and Grimme D3 libraries, but a basic build without these should be possible and deployable.

**Comment by ikirker** [comment]
Mailed DJ about PSPs.

**Comment by ikirker** [comment]
Ah, apparently the recommended approach now is to primarily use the on-the-fly PSP generator.

And on libxc:

> For libxc - I would recommend avoiding use of this. My understanding is that the interface is partial at best and a rather outdated version is included.

So, a vanilla build with no PSP library and no libxc should cover most use cases, I think.

**Comment by ikirker** [comment]
Install script prepared. Running on all systems now. It takes a while.

**Comment by ikirker** [comment]
Done. Notified requester.
