### ISSUE TITLE
STAR-CCM+: Install latest version - 14.06.013 [IN04058274]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#325]
I have the installer archive in my _~/Scratch/Software/STAR-CCM+_ directory on Grace.

**Comment by balston** [comment]
Firstly give execute permission to the following:
```
~ccaabaa/Scratch/Software/STAR-CCM+/starccm+_14.06.013/STAR-CCM+14.06.013_01_linux-x86_64-2.12_gnu7.1-r8.sh
~/ccaabaa/Scratch/Software/STAR-CCM+/starccm+_14.06.013/Disk1/InstData/VM/STARCCMPLUS.bin
```

Running the installer on Grace as _ccspapp_:
```
cd ~ccaabaa/Scratch/Software/STAR-CCM+/starccm+_14.06.013
./STAR-CCM+14.06.013_01_linux-x86_64-2.12_gnu7.1-r8.sh
```

**Comment by balston** [comment]
Using #257 as a guide for the installation parameters:

1.  Accept License Agreement > Next

1. Choose Installation Method: Use Custom (Advanced) as we don't need to install the license manager but do need to point to the Mech Eng one > Next

1. Choose Install Type: Unselect FlexNet license manager > Next

1. Choose Simcenter STAR-CCM+ components: Make sure all are selected apart from Simcenter Job Manager > Next

1. Select Installation Location: use _/shared/ucl/apps/STAR-CCM+_ > Next

1. Select Additional Tasks: Unselect "Add application directory to your system
path" as the module file will set this up > Next

1. Product Excellence Program: Unselect > Next

1. Pre-Installation Summary: > Install

**Comment by balston** [comment]
Installer finished without errors.

**Comment by balston** [comment]
Now to run some tests to see if it works!

**Comment by balston** [comment]
My first test using the Jet1.sim with OpenMPI has run for its full 1hour wallclock time. It appears to have been successful until it ran out of time.

Will now try the same simulation using Intel MPI instead.

**Comment by balston** [comment]
The Intel MPI version has worked as well. Now installing Module file ...

**Comment by balston** [comment]
Module file updated. Submitted a big 24 hour wallclock time test.

**Comment by balston** [comment]
Changed permissions on installation directory so only members of the legstarc group can access.

**Comment by balston** [comment]
I've informed the requester of the Grace installation.

**Comment by balston** [comment]
Will now install on:
- [ ] Kathleen;
- [ ] Myriad.

**Comment by balston** [comment]
OK 24 hour run of the Intel MPI version has failed with:
```
Minimum Temperature limited to 100 on 1226 cells in Region 1
         25956   3.720524e-03   7.748417e-03   7.270153e-03   4.393885e-03   8.431416e-06   3.021453e-02   2.141828e-06   3.763254e+02 
Reversed flow on  33 faces on outlet
A request for memory failed. This is typically due to insufficient virtual memory.
Processor: 7
   Recoverability: Non-recoverable
```
repeated until:
```
   ServerStack: [
libStarNeo.so: NonRecoverableError::createInitializerProperties(Properties const&), 
libStarNeo.so: NonRecoverableError::NonRecoverableError(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, Properties const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), 
libStarNeo.so: Controller::executeCommand(Command&, Properties const&, Properties&), 
libStarNeo.so: Controller::executeCommand(Properties const&, Properties&), 
libStarMachine.so: CommandController::SlaveCommandLoop::start(), 
libStarMachine.so: CommandController::processCommands(), 
libStarMachine.so: Machine::main(int, char**)]
   ServerState: exiting
   error: Exception (bad_alloc)

	at star.base.neo.NeoClient.updateProxyServerState(NeoClient.java:586)
	at star.base.neo.ClientNotifyHandler.execute(ClientNotifyHandler.java:187)
	at star.base.neo.ClientNotifyHandler.run(ClientNotifyHandler.java:446)
	at java.base/java.lang.Thread.run(Thread.java:834)

Design STAR-CCM+ simulation completed
Server process exited with code : 32
```
The same 24 test using OpenMPI is still running. I will also try the test using IBM Platform MPI.

**Comment by balston** [comment]
Both the OpenMPI and IBM Platform MPI versions of the test job ran for the whole 24 hours. It looks like Intel MPI isn't working correctly with STAR-CCM+ and shouldn't be used.

**Comment by balston** [comment]
I've removed the Intel MPI example job script and added the IBM Platform MPI one. So:
```
/shared/ucl/apps/STAR-CCM+
```
now has:
```
run-starccm+_OpenMPI.sh
run-starccm+_PlatformMPI.sh
```

**Comment by balston** [comment]
Now onto the Myriad and Kathleen installs.

**Comment by balston** [comment]
The installer files have now ben copied to both Kathleen and Myriad.

**Comment by balston** [comment]
Finally completed testing of the Kathleen install. Now testing the Myriad one.

**Comment by balston** [comment]
I've also informed the requester that the Kathleen and Myriad installations are now done.

**Comment by heatherkellyucl** [comment]
Done Feb 2020.
