### ISSUE TITLE
Install Request: CMG [IN04073313]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#327]
Retrieved CMG installers and working on build script

**Comment by hillary-b** [comment]
Tested buildscript, seems to be working fine.

**Comment by hillary-b** [comment]
Installers copied to `/shared/ucl/apps/CMG/installers` on Myriad

**Comment by hillary-b** [comment]
Attempted to install on Myriad but received this error :

**Comment by hillary-b** [comment]
Copied installers to `/shared/ucl/apps/CMG/installers` on Myriad

**Comment by hillary-b** [comment]
Installed CMG 2019.101 on Myriad

**Comment by hillary-b** [comment]
User has been informed

**Comment by heatherkellyucl** [comment]
Done Feb 2020.
