### ISSUE TITLE
Install Request: GROMACS 2020

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#331]
Application: GROMACS 2020

Link: http://manual.gromacs.org/documentation/2020/download.html

Cluster: All

License: open source, GPL-licensed.

Looks from my testing like this is non-trivial to build because it depends on having a newer g++/libstdc++ even when building with the Intel compiler:

```none
Length: 28928068 (28M) (unauthoritative)

100%[======================================>] 28,928,068  27.9MB/s   in 1.0s

2020-02-28 10:29:32 (27.9 MB/s) - ‘gromacs-2020.tar.gz’ saved [28928068]

gromacs-2020.tar.gz: OK
Building and installing full, serial, single precision GROMACS with gmx view
-- The C compiler identification is Intel 18.0.3.20180410
-- The CXX compiler identification is Intel 18.0.3.20180410
-- Check for working C compiler: /shared/ucl/apps/intel/2018.Update3/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc
-- Check for working C compiler: /shared/ucl/apps/intel/2018.Update3/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /shared/ucl/apps/intel/2018.Update3/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc
-- Check for working CXX compiler: /shared/ucl/apps/intel/2018.Update3/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test USING_LIBSTDCXX
-- Performing Test USING_LIBSTDCXX - Success
CMake Error at cmake/FindLibStdCpp.cmake:119 (message):
  Found g++ at /shared/ucl/apps/gcc/4.9.2/bin/g++.  Its version is 4.9.2.
  GROMACS requires at least version 5.1.  Please specify a different g++
  using GMX_GPLUSPLUS_PATH, PATH or CMAKE_PREFIX_PATH.
Call Stack (most recent call first):
  CMakeLists.txt:69 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/gromacs-build.IwD3pb9EmM/gromacs-2020/build/CMakeFiles/CMakeOutput.log".
[ccspapp@login01.kathleen /shared/ucl/apps/build_scripts]$ 
```

**Comment by owainkenwayucl** [comment]
Building with GCC 7.3 providing the backing libraries to the Intel compiler would fix this except of course the Intel compiler doesn't support GCC>6 until 2019.  Doing a test build with the (broken on all non-OPA clusters) version of Intel 2019 to see if it at least compiles while we get updated 2019 Intel compilers/MPI.

**Comment by owainkenwayucl** [comment]
Right - that seems to build so I guess I need to sort out the newer compilers.

Also need to make some sort of policy decision about where `gcc-libs/7.3.0` lives in the modules tree as this becomes more of a problem - thoughts @ikirker?

**Comment by owainkenwayucl** [comment]
Right.  The Intel 2019.5 and 2020.0 compilers throw a floating point exception on compiling pull_util which I've reported to Intel if it ever makes it out of moderation here: https://software.intel.com/en-us/forums/intel-c-compiler/topic/849759

The GROMACS developers have released 2020.1 which includes a workaround which drops the optimisation level of that file.  Testing now.

**Comment by owainkenwayucl** [comment]
The workaround works and I've put module files in `beta-modules`.

We need to decide how to present stuff that depends on `gcc-libs/7.3.0` in future as this is going to become more and more of a problem.

Need to do the GPU build on Myriad...

**Comment by owainkenwayucl** [comment]
As an aside, last week @heatherkellyucl and I managed to work out what was up with MPI in Intel 2019.4 on Grace with verbs - the verbs libfabric provider relies on IPoIB for routing and due to the complicated IPoIB setup that system has it was selecting the wrong subnet.  This is now resolved.

**Comment by hillary-b** [comment]
New request from user in ticket IN04324634

**Comment by owainkenwayucl** [comment]
Right - now the summer chaos is over, picking this up again.

**Comment by owainkenwayucl** [comment]
It looks like I successfully did the 2020.1 cuda build in March on Myriad.

Doing updated builds with 2020.4.  We still need to sort out the presentation side.

**Comment by owainkenwayucl** [comment]
I've done 2020.4 builds but I've not yet done th AVX512 override build for Michael because I honestly can't remember how.  Need to look at my notes.

**Comment by owainkenwayucl** [comment]
AVX512 build done.

Users can load this version of gromacs by doing:

```shell
module purge
module load beta-modules
module load rcps-core-beta/gnu-7.3.0
module load compilers/intel/2020/release 
module load mpi/intel/2019/update6/intel 
module load gromacs/2020.4/intel-2020
```

**Comment by owainkenwayucl** [comment]
It looks like the user was contacted a couple of months ago telling them that 2020.1 was available so I'm closing this ticket.
