### ISSUE TITLE
Install Request: MATLAB toolbox SamSrf_v5.84

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#333]
IN: 04108036

SamSrf_v5.84 (attached to ticket).

> This is a Matlab toolbox that is used for analysis fMRI data for the purpose of population receptive field mapping. More details and newer versions can be found here (however, I’ll need the v5.84 for my analyses): https://osf.io/2rgsm/

License: GNU General Public License (GPL) 2.0

**Comment by balston** [comment]
Build script done for the older version.

**Comment by balston** [comment]
I've run the build script which is very simple and the toolbox is installed. Now to produce a module file that links it with the latest SPM 12 and Matlab R2019b.

**Comment by balston** [comment]
Module file installed. Module command needed are:
```
module unload compilers gcc-libs
module load beta-modules
module load gcc-libs/7.3.0
module load compilers/gnu/7.3.0
module load xorg-utils/X11R7.7
module load matlab/full/r2019b/9.7
module load spm/12/jan2020/matlab.r2019b
module load samsrf/5.84/matlab.r2019b
```

**Comment by balston** [comment]
I've not been able to test if SamSrf works so over to the user ...

**Comment by balston** [comment]
Completed apart from testing on Myriad. User informed and asked to test.

**Comment by balston** [comment]
No response from user assuming done.
