### ISSUE TITLE
Install request: Octopus 5.0.1

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#34]
IN00980150

http://www.tddft.org/programs/octopus/wiki/index.php/Octopus_5.0.1

**Comment by owainkenwayucl** [comment]
Unfortunately, Octopus 5.0.1 seg faults in one of the tests (test 32, finite_systems_2d/08-gdlib.test).

I'm currently looking into it.

**Comment by owainkenwayucl** [comment]
I appear to have resolved the seg faulting issue in my test build by building with gfortran rather than the Intel compilers.  I'm currently doing proper builds on both Grace and Legion and will update this issue when these are complete.

**Comment by owainkenwayucl** [comment]
Both platforms now have serial and mpi builds of Octopus 5.0.1 with the GNU toolchain.
