### ISSUE TITLE
Install Request: MRtrix, Dipy, Freesurfer & FSL [IN04208279]

### ISSUE THREAD

**Issue by hillary-b** [UCL-RITS/rcps-buildscripts#342]
- MRtrix (https://mrtrix.readthedocs.io/en/latest/installation/hpc_clusters_install.html)

- Dipy (https://dipy.org/documentation/1.1.1./installation/#osx)

- Freesurfer (https://surfer.nmr.mgh.harvard.edu/fswiki/DownloadAndInstall)

- FSL (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/FslInstallation)

**Comment by lmlacerda** [comment]
Hi @hillary-b, I have been able to use MRtrix, Freesurfer and FSL in myriad. From what I could see Dipy is still not there and I would further request AMICO (https://github.com/daducci/AMICO). Thank you very much RITS team!
