### ISSUE TITLE
Install Request: GDAL with Python bindings

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#347]
IN:04245124

We previously didn't install them because of compatibility/install issues, but it looks like it should be working better with GDAL 3. 

https://trac.osgeo.org/gdal/wiki/GdalOgrInPython

This should hopefully work.
```
./configure --with-python
```
or you can do a `setup.py` install.

Current release is 3.1.0

**Comment by balston** [comment]
It looks like the correct Python has been selected during the build. Will need to ensure that PYTHONPATH is set correctly.

**Comment by balston** [comment]
I've uploaded an updated module file into beta_modules:
```
---------------------- /shared/ucl/apps/modulefiles/beta -----------------------
gdal/3.0.4/gnu-9.2.0 gdal/3.1.3/gnu-9.2.0
```

**Comment by balston** [comment]
Now running some tests ...

**Comment by balston** [comment]
Using the following modules:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/9.2.0
module load compilers/gnu/9.2.0
module load python3/recommended
module load perl/5.22.0
module load sqlite/3.31.1/gnu-9.2.0
module load hdf/5-1.10.5/gnu-9.2.0
module load netcdf/4.7.4/gnu-9.2.0
module load proj.4/7.0.0/gnu-9.2.0
module load gdal/3.1.3/gnu-9.2.0
```

**Comment by balston** [comment]
Running:
```
gdalinfo --version
```
produces:
```
GDAL 3.1.3, released 2020/09/01
```
So far so good!

**Comment by balston** [comment]
Tested a Python GDAL example and it appears to work. Informing user.

**Comment by balston** [comment]
User informed.

**Comment by balston** [comment]
GDAL + Python is working on Myriad.
