### ISSUE TITLE
Install Request: ChimeraX [IN04246362]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#349]
https://www.cgl.ucsf.edu/chimerax/download.html

Build on Kathleen first.

**Comment by ikirker** [comment]
This has some pretty bad dependencies.

```
rpm -if /shared/ucl/apps/pkg-store/ucsf-chimerax-1.0-1.el7.x86_64.rpm 
error: Failed dependencies:
	fftw-libs-single is needed by ucsf-chimerax-1.0-1.el7.x86_64
	gstreamer1-plugins-base is needed by ucsf-chimerax-1.0-1.el7.x86_64
	libxkbcommon-x11 is needed by ucsf-chimerax-1.0-1.el7.x86_64
	openjpeg2 is needed by ucsf-chimerax-1.0-1.el7.x86_64
	pulseaudio-libs-glib2 is needed by ucsf-chimerax-1.0-1.el7.x86_64
	xcb-util-keysyms is needed by ucsf-chimerax-1.0-1.el7.x86_64
```

**Comment by ikirker** [comment]
Because it's a graphical app that *seems* to only have one key executable as the point of execution, though, it might work well as a container?

**Comment by ikirker** [comment]
Downloaded `ucsf-chimerax-1.0-1.el7.x86_64.rpm` and put in `/shared/ucl/apps/pkg-store` because the website can't be `wget`-ed from, but for a container, the generic tar might make more sense, with a lighter distribution. ("Minimal" CentOS images are *gigantic*.)
