### ISSUE TITLE
Install request: CERNLIB

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#35]
CERNLIB on Legion for use with GNU 4.9.2 and NAG Mark 24.

Was on Old Legion.

IN01032834

**Comment by heatherkellyucl** [comment]
We installed a CERNLIB built from source and some parts of it are segfaulting (`cernlib/2006/gnu-4.9.2`).

We also installed a binary CERNLIB from RPM which needs testing: `cernlib/2006-35`

**Comment by balston** [comment]
The binary version of CERNLIB was still segfaulting when used with NAG. After some messing around, we think that CERNLIB is incompatible with NAG Mark 24. Installing the older Mark 22 of the NAG Library appears to solve the problem.

So to use CERNLIB and NAG together use the following set of modules:
```
module unload compilers/intel/2015/update2
module unload mpi/intel/2015/update3/intel
module load compilers/gnu/4.9.2
module load nag/fortran/mark22/gnu-4.9.2
module load cernlib/2006-35
```

**Comment by heatherkellyucl** [comment]
User has confirmed that this is working with NAG Mark 22.
