### ISSUE TITLE
Install Request: SALOME 9.5

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#354]
IN:04301771

> SALOME is an open-source software that provides a generic Pre- and Post-Processing platform for numerical simulation. It is based on an open and flexible architecture made of reusable components.

Requested for generating OpenFOAM meshes.

https://www.salome-platform.org/downloads/current-version
http://files.salome-platform.org/Salome/Salome9.5.0/src9.5.0.tar.gz

License: LGPL

**Comment by ikirker** [comment]
Yiiiiiiikes, this is a mess. I guess I shouldn't be surprised, if it works with OpenFOAM.
