### ISSUE TITLE
Install Request: STATA-MP Version 16 on Myriad

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#355]
This is for a COVID19 project. Direct email to @owainkenwayucl and @balston from Feifei Bu,  (f.bu AT ucl.ac.uk)

We already have a license for this version.

**Comment by balston** [comment]
STATA 16 has been installed on Myriad in:
```
/shared/ucl/apps/StataMP/stata16
```
It needs a quick test and then an update.

**Comment by balston** [comment]
STATA is not starting up:
```
stata-mp: error while loading shared libraries: libpng16.so.16: cannot open shared object file: No such file or directory
```
All STATA launchers (xstata, stata, stata-mp etc)  are giving the same error. Investigating ...

**Comment by balston** [comment]
A google search shows that this is a known error with STATA on modern Linux distributions. Further searching found this work around: https://github.com/kylebarron/stata-png-fix Not ideal as all users would need to run it to build replacement libraries. However it should be possible to incorporate the method into our STATA build script which is what I'm going to do.

**Comment by balston** [comment]
I've updated the build script to include the libpng fix. Trying it out now ...

**Comment by balston** [comment]
This has resolved the libpng issue but the follow errors now occur on launch:
```
stata: /lib64/libtinfo.so.5: no version information available (required by stata)
stata: /shared/ucl/apps/gcc/4.9.2/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by stata)
stata: /shared/ucl/apps/gcc/4.9.2/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by stata)
```

**Comment by balston** [comment]
Looks like _gcc-libs/9.2.0_ will be needed.

**Comment by balston** [comment]
I'm now updating the module file from STATA 15 for 16.

**Comment by balston** [comment]
Slight change in plan now needs the following modules:
```
module -f unload gcc-libs
module load beta-modules
module load gcc-libs/9.2.0
module load libpng/1.6.37/gnu-9.2.0
module load stata/16
```

**Comment by balston** [comment]
Trying a test job ...

**Comment by balston** [comment]
My test job has worked!

**Comment by balston** [comment]
Internal STATA update run to bring STATA to Version 16.1 Revision 13th Aug 2020.

**Comment by balston** [comment]
If re-run my test job to confirm that it still works after the update and placed a copy in:
```
/shared/ucl/apps/StataMP/share/run-stata16-mp.sh
```

**Comment by balston** [comment]
User emailed.

**Comment by heatherkellyucl** [comment]
Done in Aug.
