### ISSUE TITLE
Install Request: Dakota 6.12 on Young

### ISSUE THREAD

**Issue by blebon** [UCL-RITS/rcps-buildscripts#356]
Application: Dakota 6.12

Link: https://dakota.sandia.gov/downloads

Cluster: Young

Description: required to facilitate parametric analysis, design exploration, model calibration, and uncertainty quantification.

License: open source, GNU LGPL.

**Comment by ikirker** [comment]
Installed on all working clusters. (Not Legion and Grace.)

**Comment by heatherkellyucl** [comment]
Done in Sept.
