### ISSUE TITLE
Install Request: Update sac on Aristotle to latest version

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#368]
I got this by personal email from the course tutor so no RF ticket yet.

Latest version is available here:

http://ds.iris.edu/ds/nodes/dmc/forms/sac/

**Comment by balston** [comment]
Alex has provided the source code which has been copied to:
```
/shared/ucl/apps/sac/sources/sac-102.0.tar.gz
```
on Myriad.  Next step will be to update the  _sac-101.6a_r2016b_install_ build script for the new version.

**Comment by balston** [comment]
Now producing _sac-102.0_r2019b_install_ build script - attempting to use Matlab R2019b (the latest version we currently have installed).

**Comment by balston** [comment]
Build script run on Myriad. No apparent errors. Uploading new module file now.

**Comment by balston** [comment]
To use this version the following modules need to be loaded:
```
module load xorg-utils/X11R7.7
module load matlab/full/r2019b/9.7
module load sac/102.0
```

**Comment by balston** [comment]
Informing user and getting them to test before migrating to Aristotle.

**Comment by balston** [comment]
email sent to Alex.

**Comment by balston** [comment]
Alex is getting the following error during testing:
```
SAC> event time 2019-05-14 +1d mag 7 cmt
Error 77: Problem with the SSL CA cert (path? access rights?)                                          
SAC> 
```

**Comment by balston** [comment]
I've tried the same command from my account and I'm getting the same error. Investigating ...

**Comment by balston** [comment]
The following has worked for me. Adding the Curl module:
```
module load curl/7.47.1/gnu-4.9.2
```
before running SAC.

**Comment by balston** [comment]
Alex has also tested SAC successfully with the Curl module loaded. Adding it to the module as a dependency. So modules needed are now:
```
module load xorg-utils/X11R7.7
module load matlab/full/r2019b/9.7
module load curl/7.47.1/gnu-4.9.2
module load sac/102.0
```

**Comment by balston** [comment]
Module updated.

**Comment by balston** [comment]
Installed on Aristotle02.

**Comment by balston** [comment]
Not completed because Aristole is rsyncing from the old Legion transfer node. Neet to build there if possible to make SAC stick on Aristotle.

**Comment by balston** [comment]
SAC 102 now built on the Legion Transfer node. It should now rsync across tonight.

**Comment by balston** [comment]
SAC 102 now on Aristotle:
```
[ccaabaa@aristotle02 ~]$ module avail sac

------------------ /shared/ucl/apps/modulefiles/applications -------------------
sac/101.6a sac/102.0
[ccaabaa@aristotle02 ~]$ module load xorg-utils/X11R7.7
[ccaabaa@aristotle02 ~]$ module load matlab/full/r2019b/9.7

~/.matlab is a symbolic link pointing to /home/ccaabaa/Scratch/.matlab

Matlab setup complete type matlab to start Matlab.

[ccaabaa@aristotle02 ~]$ module load curl/7.47.1/gnu-4.9.2
[ccaabaa@aristotle02 ~]$ module load sac/102.0
[ccaabaa@aristotle02 ~]$ cd Software/SAC
[ccaabaa@aristotle02 SAC]$ ls
sac-102.0.tar.gz
[ccaabaa@aristotle02 SAC]$ sac
 SEISMIC ANALYSIS CODE [10/14/2020 (Version 102.0)]
 Copyright 1995 Regents of the University of California

SAC> event time 2019-05-14 +1d mag 7 cmt
Origin              Lat.   Lon.    Depth  Mag.     Agency EventID
2019-05-14T12:58:39  -4.03  152.52  22.10 7.60 MW  GCMT/- GCMT gcmt:11037207
SAC>
```

**Comment by balston** [comment]
Alex has reported issues with missing functionality in our version of SAC 102 compared to the developer's version. I used the same configure options as the previous version. May need extra options or there are missing dependencies. Investigating ...

**Comment by balston** [comment]
Results from the developer are:

![image](https://user-images.githubusercontent.com/4246274/97019275-0b849900-1548-11eb-8427-4792818d9f8a.png)

Checking what we get on Myriad ...

**Comment by balston** [comment]
I'm getting:

```
 sac
 SEISMIC ANALYSIS CODE [10/09/2020 (Version 102.0)]
 Copyright 1995 Regents of the University of California

SAC> data sta DOOR cha BHZ time 1994-06-09T00:33:45 1h read
Data Center: IRISDMC,http://ds.iris.edu
               SourceID                Start sample             End sample         Gap
XFDSN:XE_DOOR__B_H_Z     1994-06-09T00:33:45.012000 1994-06-09T01:33:44.912000  ==
Working on file: XE.DOOR..BHZ.M.1994.160.003345.sac [ OK ]
SAC>
```
OK so far ...

**Comment by balston** [comment]
And:
```
SAC> metadata gcmt:369471
Working on file: XE.DOOR..BHZ.M.1994.160.003345.sac [ OK ]
SAC>
```
still OK  ...

**Comment by balston** [comment]
This is where it goes wrong:
```
SAC> read XE.DOOR..BHZ.M.1994.160.003345.sac
 ERROR 1301: No data files read in.
SAC>
```

**Comment by balston** [comment]
See:

https://ds.iris.edu/message-center/thread/2796/#m-4390

for a possible reason for the error.

**Comment by balston** [comment]
SAC has now been built with the GNU 10.2.0 compilers to see if the bug is fixed. The following modules are needed to access  the new build:
```
module -f unload compilers mpi gcc-libs
module load  beta-modules
module load  gcc-libs/10.2.0
module load  compilers/gnu/10.2.0
module load  xorg-utils/X11R7.7
module load  matlab/full/r2019b/9.7
module load  curl/7.47.1/gnu-4.9.2
module load  sac/102.0-test/gnu-10.2.0
```
Note: only on Myriad at the moment.

**Comment by heatherkellyucl** [comment]
For future reference, the ticket about the SAC bug is IN:04978905.
