### ISSUE TITLE
Install request: sklearn for Python3

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#37]
IN01106911

Can use pip3, is called scikit-learn

http://scikit-learn.org/stable/index.html

**Comment by owainkenwayucl** [comment]
Looks like there is a verison 2 and a version 3 version so I'll add it to both.

**Comment by owainkenwayucl** [comment]
Right - it's installed into the python3/recommended bundles on both Legion and Grace.

Doing Python 2 now.

**Comment by owainkenwayucl** [comment]
It's now done on both platfroms, on both versions of python.
