### ISSUE TITLE
STAR-CCM+: Version 13.06.0112 is not on Kathleen [IN:04379173]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#370]
This is the primary version being used my Mech Eng. so needs installing even though we have version 14.x already there.

**Comment by balston** [comment]
I'm trying to locate the installer for V 13.06.x as it is not currently anywhere on Kathleen.

**Comment by balston** [comment]
Found a copy on Myriad and I'm copying it over in to:
```
~ccaabaa/Software/STAR-CCM+/STAR-CCM+13.06.012_01_linux-x86_64.tar.gz

```

**Comment by balston** [comment]
No build script as presumably a GUI only installer. I will follow the installation details from the old install issue here:

https://github.com/UCL-RITS/rcps-buildscripts/issues/257

**Comment by balston** [comment]
Installer appears to have completed without fatal errors. I will now try running a test job.

**Comment by balston** [comment]
Test job submitted:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
  89219 2.69811 StarCCM+_J ccaabaa      qw    10/15/2020 14:01:54                                   80
```

**Comment by balston** [comment]
I've also changed the permissions on this version to disable access to anyone not in the _legstarc_ group.

**Comment by balston** [comment]
My test job has failed because I don't have access to the directory. I should be in the right group I think.

**Comment by balston** [comment]
I have set the permissions wrong. I managed to remove group read access to most of the install tree! Fixing now ...

**Comment by balston** [comment]
Permissions fixed I think. I've re-submitted my test job.
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
  89479 2.68966 StarCCM+_J ccaabaa      qw    10/15/2020 17:00:46                                   80
```

**Comment by balston** [comment]
Still not working:
```
Using existing ~/Scratch/.star-13.06.012-ccaabaa
Using existing ~/Scratch/.star-13.06.012
buildOptions.json not found! This suggests you are using an improper/out-of-date build.
sed: can't read /shared/ucl/apps/STAR-CCM+/13.06.012/STAR-CCM+13.06.012/star/config/Makeflags.version: No such file or directory
sed: can't read /shared/ucl/apps/STAR-CCM+/13.06.012/STAR-CCM+13.06.012/star/config/Makeflags.version: No such file or directory
sed: can't read /shared/ucl/apps/STAR-CCM+/13.06.012/STAR-CCM+13.06.012/star/config/Makeflags.version: No such file or directory
sed: can't read /shared/ucl/apps/STAR-CCM+/13.06.012/STAR-CCM+13.06.012/star/config/Makeflags.version: No such file or directory
Error: Java SDK is not installed at /shared/ucl/apps/STAR-CCM+/13.06.012/jdk/linux-x86_64/jdk
       Refer to user documentation for more details
```
The file:
```
/shared/ucl/apps/STAR-CCM+/13.06.012/STAR-CCM+13.06.012/star/config/Makeflags.version
```
doesn't exist. Maybe the installation didn't work. Investigating ...

**Comment by balston** [comment]
The above file is there on the Myriad installation of 13.06.012 so I'm going to delete my first attempt and re-install from scratch.

**Comment by balston** [comment]
The second attempt at the installation has completed. This time the file exists!

I will now set correct group ownership and permissions.

**Comment by balston** [comment]
Test job re-submitted:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
  90567 2.79245 StarCCM+_J ccaabaa      qw    10/16/2020 18:30:43                                   80

```

**Comment by balston** [comment]
My test job worked this time. Unless I hear otherwise, I'm assuming STAR-CCM+ 13.06.012 is now successfully on Kathleen.

**Comment by balston** [comment]
I have informed the user as well!

**Comment by heatherkellyucl** [comment]
Done in Oct.
