### ISSUE TITLE
Install Request: Stacks [IN04401344]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#373]
Requested for Myriad.

https://catchenlab.life.illinois.edu/stacks/

Installation details:

https://catchenlab.life.illinois.edu/stacks/manual/#install

**Comment by heatherkellyucl** [comment]
License: GNU GPL v3

Test install looks simple, using GNU compiler as that is what they mention.

- [ ] Myriad
- [ ] modulefile

**Comment by ikirker** [comment]
Dang, now I have to revert my half-hour old commit.

**Comment by heatherkellyucl** [comment]
Reported working!
