### ISSUE TITLE
Install Request: CDO and NCView

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#375]
IN:04420055

Ncview: a netCDF visual browser
http://meteora.ucsd.edu/~pierce/ncview_home_page.html
License: GNU GPL v1

CDO: Climate Data Operators
https://code.mpimet.mpg.de/projects/cdo/
License: GNU GPL v2

**Comment by oscarbrousse** [comment]
Hi, would it be possible to have these installed soon?
