### ISSUE TITLE
[IN:04423017] DL_MONTE 2.0

### ISSUE THREAD

**Issue by ikirker** [UCL-RITS/rcps-buildscripts#377]
Original message:
> I am writing in regard to a software that I need to use for my research project. I cannot seem to find it on the available application list and was wondering if I am missing anything.
> 
> The software name is DL_MONTE 2.0 and I will be primarily using it on Myriad.
> 
> Please let me know if I missed anything, otherwise would it be feasible to install it? (It’s an open source software).
> 
> Thank you and best wishes,

Software is here: <https://gitlab.com/dl_monte/dl_monte-releases/-/blob/master/dl_monte_release_v2.07.tar.gz>
(Tarball direct download is here: <https://gitlab.com/dl_monte/dl_monte-releases/-/raw/master/dl_monte_release_v2.07.tar.gz>)

Released under 3-clause BSD licence.

Compile information here: <https://dl_monte.gitlab.io/dl_monte_manual/compile.html>

Would benefit from being compiled with Intel compiler, but seems to have some issue where it needs CPP-style preproc directives but `ifort` only passes files through the preprocessor if they have the `.F90` extension, and the Fortran source files have the `.f90` extension. Rename all source files? 🙁 

****Edit:**** Ah, I'd just missed the way you specify which compiler settings you want it to use. Though you still do have to fix the Intel compiler options to replace the deprecated `-openmp` with `-fopenmp` (if you're building the OpenMP version, which I did).

**Comment by ikirker** [comment]
Done, informed requestor.

**Comment by heatherkellyucl** [comment]
Done in Nov.
