### ISSUE TITLE
[IN:04438666]Install Request: R package BradleyTerry2

### ISSUE THREAD

**Issue by tcouch** [UCL-RITS/rcps-buildscripts#378]
Application: BradleyTerry2

Link: https://cran.r-project.org/web/packages/BradleyTerry2/index.html 

Cluster: Myriad (for rstudio.data-science.ucl.ac.uk)

Description: Required for teaching POLS0013 on the RStudio data science platform.

License: open source, GPL-licensed.

Ticket number: IN:04438666

**Comment by tcouch** [comment]
Although students have reported problems installing this package in their own libraries, I've managed to install it without any problems so I think this should be a case of just adding it to the list of packages to be installed.

**Comment by balston** [comment]
Added to Myriad R 4.0.2 plus three additional dependencies. From the _R-4.0.2_single_package_install_ log:
```
install.packages ("BradleyTerry2", lib=mainLib, repos=repros, );
also installing the dependencies profileModel, brglm, qvcalc
```
Added to:
```
./files/R_UCL/R_packages_UCL_5_3.6.3.R
```
in build scripts for future builds.

**Comment by balston** [comment]
Will transfer to RStudio service at next _/shared/ucl/apps_ sync.
