### ISSUE TITLE
Install request: WebLogo 3

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#38]
IN01157939

Requires Python 2.7 with numpy, also ghostscript and pdf2svg.

http://weblogo.threeplusone.com/manual.html
https://github.com/WebLogo/weblogo

**Comment by heatherkellyucl** [comment]
(Is in pypi)

**Comment by owainkenwayucl** [comment]
Right - we already have ghostscript.

**Comment by owainkenwayucl** [comment]
I'll skip pdf2svg if I can, because it needs half of GNOME.

**Comment by owainkenwayucl** [comment]
This is now done on Legion - just waitng for Grace to finish.

**Comment by owainkenwayucl** [comment]
And done on Grace.
