### ISSUE TITLE
Install Request: VASP 6.1.1

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#381]
IN:04445252 

6.1.2 is also out.

Questions: are we licensed for 6.x? Should we be?

https://www.vasp.at/post/new-release-vasp-610/

> VASP users who have a valid VASP.5 license from the VASP Software GmbH or the University of Vienna are entitled to upgrade to VASP.6. Because of withholding taxes and other surcharges the upgrade fee varies between 1.500,- Euro and about 2.000,- Euro net of VAT for six academic users. It requires the signing of a new license agreement between the VASP Software GmbH and the licensee. The new license agreement will replace the license agreement between the University of Vienna and the licensee.
>
>Due to many open requests, we will not be able to process upgrade requests before the end of March/April. Please also note that the terms of the new license agreement are not negotiable. Should requests for a modified license agreement be made, we will defer or reject the request for an upgrade.

It also has an empty variable rm -r issue on MacOS and BSD and can delete things from user homes... https://www.vasp.at/post/bugfix-in-testsuite-vasp6/

**Comment by heatherkellyucl** [comment]
Emailed IT Purchasing about the above, IN:04446745.

**Comment by owainkenwayucl** [comment]
Just a note, I've signed the license so we just need to sort out team membership etc which is apparently blocked by a portal bug.

**Comment by owainkenwayucl** [comment]
I'm doing test builds now so I'm hoping to push this out in the next week or so once I've got it working properly.

**Comment by owainkenwayucl** [comment]
A base build of 6.1.2 has been deployed.

**Comment by owainkenwayucl** [comment]
Users updated.
