### ISSUE TITLE
Install Request: Yambo 4.5

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#382]
IN:04452550

> Yambo doesn't stand for anything like "Yet Another Many-Body cOde", for instance. 
Unless you really want it to. 

The version we have installed (4.1.4) is only compatible with Quantum Espresso up to 6.1, and we have newer versions than that. 

https://github.com/yambo-code/yambo

License: GPL 2.0

**Comment by ikirker** [comment]
Is there a reason this wasn't built alongside QE 6.5 using the `make yambo` option?

**Comment by heatherkellyucl** [comment]
Probably because no one knew about it - old yambo was a standalone.

**Comment by aim137** [comment]
Here is the [link](https://github.com/yambo-code/yambo) to the git repo of Yambo 5.0.1.

Please see below my configure flags for Young - this works straight away with with the default modules. It will download and compile the following external libraries: iotk, netcdf, hdf5 and libXC.

[config_compile_yambo.txt](https://github.com/UCL-RITS/rcps-buildscripts/files/6221709/config_compile_yambo.txt)

Could you please install it?

Thanks in advance,
Ignacio Martin Alliati.
Queen's University Belfast

PS. Although I initially opened this request, I don't need it anymore as I use my own developer branch. However, several colleagues in my group need it.

**Comment by mmistry4** [comment]
- [x] Myriad
- [x] Kathleen
- [ ] Young
- [ ] Michael
- [ ] Thomas
