### ISSUE TITLE
Install Request: Chemshell with GAMESS-UK

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#389]
IN: 04482274 

We only have a GAMESS-US module at present and not GAMESS-UK. We will need to get Robert Silk to fill in another license form for the Site License (citing clusters and hardware types) since we did have one in 2017, but they expire after 3 years.

http://www.cfs.dl.ac.uk
http://www.cfs.dl.ac.uk/licences/site_licence.pdf

(Old attempt at installing GAMESS-UK: https://github.com/UCL-RITS/research-computing/issues/1444 didn't work with any of the Intel compilers we had at the time).

**Comment by heatherkellyucl** [comment]
IN:04504412 is the request in with IT Purchasing. Filled in all the machine architecture for them on the PDF.

**Comment by heatherkellyucl** [comment]
Got back email from Purchasing that it needs to be signed by head of dept and not them. IN:04504412 is waiting for Donna to sign the license (I sent it to her on 13 Jan).

**Comment by mmistry4** [comment]
Sent them an email on 26/04/2021 and havent had a response so am closing the issue as the ticket was.
