### ISSUE TITLE
Install Request: MICA pipeline

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#390]
IN:04479112

https://micapipe.readthedocs.io/en/latest/pages/02.whatyouneed/index.html
https://github.com/MICA-MNI/micapipe

> This pipeline is developed by the MICA-lab (https://mica-mni.github.io) at the McConnell Brain Imaging Center of the Montreal Neurological Institute. Our main goal is to provide a robust framework to process multimodal MRI data for multiscale connectomics. micapipe utilizes a set of known software dependencies and different brain atlases.
>
> The pipelines integrates T1 weighted images, resting state fMRI and Diffusion weighted images.

License: GPL-3.0

Has no release versions and is under active development. We will need to label by github commit...

The dependencies listed at https://github.com/MICA-MNI/micapipe#dependencies are newer than the ones on readthedocs.

Requirements:
- [ ] dcm2niix v1.0.20190902
- [x] Freesurfer 6.0.0 (https://surfer.nmr.mgh.harvard.edu/)
- [x] FSL 6.0 (https://fsl.fmrib.ox.ac.uk/fsl/fslwiki)
- [ ] AFNI 20.2.06 (https://afni.nimh.nih.gov/download)
- [ ] MRtrix3 3.0.1 (https://www.mrtrix.org) (sadly we have 3.0.0 RC3).
- [ ] ANTs 2.3.4 (https://github.com/ANTsX/ANTs)
- [ ] workbench 1.3.2
- [ ] ENIGMA toolbox (https://github.com/MICA-MNI/ENIGMA)

Optional software:
FIX (FMRIB’s ICA-based Xnoiseifier) v1.06

Not sure if these two are optional or not:
R 3.6.3
python 3.7.6

> The FIX package (FMRIB's ICA-based Xnoiseifier) requires FSL, R and one of MATLAB Runtime Component, full MATLAB or Octave. We recommend the use of the MATLAB Runtime Component. Additionally, it requires the following R libraries: 'kernlab','ROCR','class','party','e1071','randomForest'

**Comment by mmistry4** [comment]
Developers are working on a Docker image so the work is seemingly unrequired.

**Comment by mmistry4** [comment]
Ma
