### ISSUE TITLE
Install Request: rename 

### ISSUE THREAD

**Issue by Davidwei7** [UCL-RITS/rcps-buildscripts#391]
Application: rename

Link: https://linuxize.com/post/rename-command-in-linux/

Cluster: Myriad

Description: does batch processing the names as working with 100 files to change every names individually is impossible 

License: open source

Special versions or variants: no

**Comment by ikirker** [comment]
Done. Requires Perl environmonet module to be loaded (because it's a Perl module):

This is the older C version we already had installed as part of the system image, which has different syntax and isn't the version you wanted:
```
$ which rename
/usr/bin/rename
```

This is the Perl version the article talks about:
```
$ module load perl
$ which rename
/shared/ucl/apps/perl/perlbrewroot/perls/perl-5.22.0/bin/rename
```
