### ISSUE TITLE
[IN:04484233] Install CellRanger 5

### ISSUE THREAD

**Issue by ikirker** [UCL-RITS/rcps-buildscripts#392]
Application: CellRanger 5

Package: software is available in `/shared/ucl/apps/pkg-store/cellranger-5.0.0.tar.gz`
Link: <https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/installation>

(Software is available for no cost but you have to jump through a licence hoop and use an expiring token to download it.)

Cluster: Myriad

Description, from [10x's relevant website](https://support.10xgenomics.com/single-cell-gene-expression/software/overview/welcome): 
> Our set of analysis pipelines that perform sample demultiplexing, barcode processing, and single cell 3' gene counting. 

License: proprietary.

I think this attempts to submit jobs automatically, but I'm not sure. They have this installation step where they want you to run the script and send them back the data which includes a bunch of path and scheduler stuff, so I'm guessing they'll try to walk us through the setup of that. 🤷‍♀️

**Comment by ikirker** [comment]
> This is now installed.
> 
> To set up your shell environment to run Cell Ranger, you'll need to run:
> ```
> module load cellranger/5.0.1
> ```
> or just:
> ```
> module load cellranger
> ```
> which will give you version 5.0.1 at the moment.
> 
> Some features (mkfastq I think) require bcl2fastq2, which you'll then also need to load the module for, like this:
> ```
>     module load gcc-libs
>     module load bcl2fastq2
> ```
> (`bcl2fastq2` itself needs a `gcc-libs` module loaded to run, that's why that's there first.)
> 
> Cluster mode is set up, you'll want to use the instructions on the 10x website to get the options right for running that, from here: <https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/cluster-mode>
> 
> This and the other modes are explained here: <https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/choosing-how-to-run>
> 
> As an example, for testing I used:
> ```
>    cellranger testrun --id=tiny --jobmode=sge --mempercore=8 --maxjobs=1000 --jobinterval=500
> ```
> 
> Alternatively, you can use the job submission mode, with a script like:
>
> ```
>#!/bin/bash -l
>#$ -l h_rt=24:00:00
>#$ -l mem=180G
>#$ -pe smp 36
>#$ -cwd
>
>module load cellranger
>cellranger --jobmode=local --localcores=36 --localmem=178G
>```

**Comment by heatherkellyucl** [comment]
(Been a month since the requestor was told the reference data exists in `UCLRC_CELLRANGER_REFS_DIR=/shared/ucl/apps/cellranger/references`)
