### ISSUE TITLE
Install Request: Intel Compilers, MPI and Tools 2021.1 (oneAPI base and HPC toolkits) [IN04546193]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#403]
Update to the latest Intel Parallel Studio version - now Intel oneAPI toolkits. Need at least Base and HPC toolkits.

https://software.intel.com/content/www/us/en/develop/tools/oneapi/all-toolkits.html

**Comment by balston** [comment]
The recent update to the UCL Intel License Manager #394 should support 2021.1 if needed.

**Comment by ikirker** [comment]
As mentioned previously, I don't think these versions will require any licence managers.

**Comment by ikirker** [comment]
Confirmed: I installed these in my home directory, without any environment variables or files telling them where the licence manager should be, and they work fine. I'll work out how to script the installs.

**Comment by ikirker** [comment]
```
command bash l_BaseKit_p_2021.1.0.2659_offline.sh \
    -a \
    --eula=accept \
    --install-dir="$install_prefix" \
    --cli \
    --components=all \
    --action=install \
    --intel-sw-improvement-program-consent=no \
    --silent \
    --log-dir="$build_dir"
command bash l_HPCKit_p_2021.1.0.2684_offline.sh \
    -a \
    --eula=accept \
    --install-dir="$install_prefix" \
    --cli \
    --components=all \
    --action=install \
    --intel-sw-improvement-program-consent=no \
    --silent \
    --log-dir="$build_dir"
    ```
    
    (As usual, the modules are a bit complicated, though.)
