### ISSUE TITLE
Install Request: CFD-ACE 2018 on Kathleen [IN04539041]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#405]
Mechanical Eng. have asked us to install CFD-ACE on Kathleen (it is already on Myriad).

It is licensed from the Mech. Eng. license server.

I have the installer and license details but haven't uploaded them to Kathleen yet.

**Comment by balston** [comment]
The CFD-ACE installer has now been copied onto Kathleen so I'm changing this issue to in progress.

**Comment by balston** [comment]
There isn't a build script for CFD-ACE as it is a GUI installer but the previous issue #279 can be used as a guide.

**Comment by balston** [comment]
Starting install as _ccspapp_:
```
mkdir -p /shared/ucl/apps/CFD-ACE+/2018.0
cd ~ccspapp/Scratch/Software/CFD-ace/2018r0/ACE2018r0_Linux
../INSTALL.SH
```

**Comment by balston** [comment]
Using:
```
/shared/ucl/apps/CFD-ACE+/2018.0
```
for the installation directory.

**Comment by balston** [comment]
installing ...

**Comment by balston** [comment]
Installer has completed without errors.

**Comment by balston** [comment]
Need to set up group ownership to the _lgcfdace_ reserved application group to stop unauthorised users accessing the software. This is going to be a bit complicated as _ccspapp_ is not in this group and the _ccspap2_ account, which is, no longer works.

**Comment by balston** [comment]
Re-doing the installation using an account that is in the _lgcfdace_ group. Hopefully this will allow the group ownership to be fixed using:
```
cd /shared/ucl/apps/CFD-ACE+
chgrp -R lgcfdace 2018.0
```

**Comment by balston** [comment]
IO think the permissions are now restricted to the reserved app group. I'm going to try running a test job.

**Comment by balston** [comment]
Test job submitted:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 128298 2.51515 ACE_parall ccaabaa      qw    02/12/2021 16:55:24                                   80
```

**Comment by balston** [comment]
I need to update the module file as it errors with:
```
**** error: CFD-ACE is only available on Grace and Myriad.
```
I will fix on Monday and re-run the test job.

**Comment by balston** [comment]
I've fixed the module files so CFD-ACE can run on Kathleen but I cannot run the:
```
./update_modules
```
command on Kathleen as _ccspapp_. Probably due to last weekend's uid/gid changes.

**Comment by heatherkellyucl** [comment]
The uid/gid changes are still going, but they got as far as changing the modules directory and commands, so I have run `update_modules` on Kathleen.

**Comment by balston** [comment]
Re-running test job now modules are updated:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 147877 2.01294 ACE_parall ccaabaa      qw    03/16/2021 13:31:00                                   80
```

**Comment by balston** [comment]
I made a stupid error - I forgot to give it a model to solve! Re-submitted:
```
job-ID  prior   name       user         state submit/start at     queue                          slots ja-task-ID
-----------------------------------------------------------------------------------------------------------------
 147907 2.01167 ACE_parall ccaabaa      qw    03/16/2021 15:08:02                                   80
```

**Comment by balston** [comment]
Job failed with a license error. From the job log:
```
  ===============================================================
     CFD-ACE-SOLVER Run Platform Information :
  ===============================================================
     Run Date           : 03/16/2021 17:36:12
     Run OS             : Linux
     Run OS Release     : 3.10.0-1127.el7.x86_64
     Run OS Version     : #1 SMP Tue Feb 18 16:39:12 EST 2020
     Run Machine        : node-c11b-025
  ===============================================================
  ===============================================================
 
    This simulation is running in double precision parallel mode on   80 processors
 
  C-N : theta beta =  0.6000E+00 0.6667E+00
  Request for Parallel failed for process =           75
  Request for Parallel failed for process =           75
  License Error: Unable to obtain license for feature: ACE_PARALLEL
  License Error: Unable to obtain license for feature: PARALLEL
 Please check your license settings.
 
  Error Exit from CFD-ACE-SOLVER
```
Investigating ...

**Comment by balston** [comment]
Querying the Mech Eng license server this may be because they don't have enough licenses:
```
Users of CFD_PARALLEL:  (Total of 80 licenses issued;  Total of 6 licenses in use)

  "CFD_PARALLEL" v2021.0, vendor: pam_lmd, expiry: 9-oct-2021
  floating license
```
I did this check from a compute node so Kathleen compute nodes can see the Mech Eng license manager for CFD-ACE.

**Comment by balston** [comment]
Department emailed.

**Comment by balston** [comment]
User has reported CFD-ACE is working for the 64 core size of jobs they are running.

**Comment by balston** [comment]
All done closing issue.
