### ISSUE TITLE
Build BLAS libraries with gcc 10

### ISSUE THREAD

**Issue by dbretherton** [UCL-RITS/rcps-buildscripts#408]
Child of https://github.com/UCL-RITS/RCAS-Team/issues/4

**Comment by balston** [comment]
I need this for R 4.0.4 so I'm happy to run with this one. Will build on Myriad first.

**Comment by balston** [comment]
Latest version is OpenBLAS 0.3.13 so building this version. Will need the following modules during the build:
```
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
```
updating build script ...

**Comment by balston** [comment]
Build script ready. As _ccspapp_ running:
```
./openblas-v0.3.13-gnu1020_install 2>&1 | tee ~/Software/OpenBLAS/openblas-v0.3.13-gnu1020_install.log-03022021
```

**Comment by balston** [comment]
It looks like the build has completed all three versions without errors. I'm going to test using some code from the user manual to confirm.

**Comment by balston** [comment]
I've copied the generated module files from the install to my _~/lib/modulesfiles_ directory so I can test using for example:
```
module use --append ~/lib/modulefiles/libraries
module -f unload compilers mpi
module load beta-modules
module load  gcc-libs/10.2.0
module load  compilers/gnu/10.2.0
module load openblas/0.3.13-serial/gnu-10.2.0
```

**Comment by balston** [comment]
Successfully ran two examples using:
```
gcc -o test_cblas_dgemm test_cblas_dgemm.c -I $OPENBLASROOT/include/  -L $OPENBLASROOT/lib -lopenblas -lpthread -lgfortran
./test_cblas_dgemm
```
and:
```
gcc -o time_dgemm time_dgemm.c $OPENBLASROOT/lib/libopenblas.a
 ./time_dgemm <m> <n> <k>
```
using the serial version. Will run the tests using the threaded and openmp versions as well.

**Comment by balston** [comment]
The module files for the native threads and OpenMP versions were slightly wrong. They didn't set the OPENBLASROOT environment variable. Now fixed in my copies. Re running examples for these versions which I'm submitting as jobs.

**Comment by balston** [comment]
Tests of the other version work so ready to install everywhere:
 - [ ] Aristotle;
 - [ ] Kathleen;
 - [ ] Michael;
 - [ ] Myriad;
 - [ ] RStudio servers;
 - [ ] Thomas (for sync to Michael)

**Comment by balston** [comment]
Basically need to do the following on all clusters as _ccspapp_:
```
cd /shared/ucl/apps/build_scripts
git pull
./openblas-v0.3.13-gnu1020_install 2>&1 | tee ~/Software/OpenBLAS/openblas-v0.3.13-gnu1020_install.log-<date>
```
and if the build works:
```
cd ..
./update_modules
```

**Comment by balston** [comment]
I've removed the compilers prerequisite from the new OpenBLAS modules so they now just have:
```
conflict openblas
conflict atlas
prereq gcc-libs/10.2.0
```
in them. I've re-run the _update_modules_ script on each cluster.

**Comment by balston** [comment]
I'm trying to get a sync of Myriad _/shared/ucl/apps_  to RStudio organised.
