### ISSUE TITLE
Build OpenMPI with gcc 10

### ISSUE THREAD

**Issue by dbretherton** [UCL-RITS/rcps-buildscripts#409]
Child of https://github.com/UCL-RITS/RCAS-Team/issues/4

**Comment by themkots** [comment]
(Whoever grabs this task to complete it, may give me an invit in Calendar, so I can shadow in a shared screen telecon, and see the building / testing / deploying stages as being done ... (the invit will show up in Slack as 'in meeting' so people would know availability...
so this issue will have several comments during that, such as the ones that @balston put in resp. issue https://github.com/UCL-RITS/rcps-buildscripts/issues/408)

**Comment by heatherkellyucl** [comment]
UCX has a dependency on the compiler being used so we decided to go ahead and build the prereqs as well.

What we did so far (installs only on Myriad at present):

Binutils - built newest with gcc-10
- Checked for newest version on website.
- Made `binutils-2.36.1_install` in local copy of rcps-buildscripts repo, copied from the current binutils install script. 
- Update version, module requirements and checksum ("manifest" in the buildscript). 
- Push changes.
- Pull changes in `/shared/ucl/apps/build_scripts` as `ccspapp`.
- Run install script  as `ccspapp`. (No tests available for this and fairly straightforward copy of an existing build so did not do a test install as myself first).
- Check autogenerated modulefile contents and correct if necessary (no corrections needed for this one).
- Add new modulefile to local copy of rcps-modulefile repo as `beta/binutils/2.36.1/gnu-10.2.0`. Module tree to be updated once these are no longer beta-modules.
- Push changes.
- Run `./update_modules` as `ccspapp` in `/shared/ucl/apps` to get the new module. The install is now available to everyone (who has beta-modules loaded).

The above should be repeated on all clusters so modulefiles are up to date everywhere:
- [ ] Myriad
- [ ] Kathleen
- [ ] Thomas (only for now as still in use)
- [ ] Michael (currently still rsynced from Thomas so done automatically)
- [ ] Young

UCX - built newest with gcc-10
- `ucx-1.9.0_install` made with changes from existing ucx module.
- Steps as above.
- Build on Myriad was completing when we finished the call.

To do:
- [ ] Myriad
- [ ] Kathleen
- [ ] Thomas (only for now as still in use)
- [ ] Michael (currently still rsynced from Thomas so done automatically)
- [ ] Young
- [ ] check modulefile 
- [ ] deploy modulefile everywhere

Then OpenMPI can be built and tested. This will be done by my user, since there is testing to do first. The install script will be run as me: 
```
cd /shared/ucl/apps/build_scripts
INSTALL_PREFIX=/home/cceahke/openmpi4 ./openmpi-4.1.0-gcc102_install
```

The automatic module will be modified in place in `~/openmpi4/.uclrc_modules/mpi/openmpi/4.1.0/gnu-10.2.0` and can be loaded from there in test scripts.
```
module load ~/openmpi4/.uclrc_modules/mpi/openmpi/4.1.0/gnu-10.2.0
```
 I will test using `c_mpi_pi` from https://github.com/UCL-RITS/pi_examples which is a basic Monte Carlo pi calculation that uses MPI. It builds with a simple `make` command. This will be submitted as a job.

**Comment by themkots** [comment]
!! Nice writeup ! I will go through all steps as seen you doing it and consulting my notes, in my test/sandbox space in each cluster, and I will make sure not to do anything as ccspapp for this (buildscripts + modules) collection. Thanks @heatherkellyucl !

**Comment by heatherkellyucl** [comment]
The Kathleen installs are delayed as still waiting for ccspapp chowns to complete - they are proceeding slowly.

**Comment by heatherkellyucl** [comment]
Testing my Myriad local install of OpenMPI using `c_mpi_pi`. Jobscript is like this:

```
#!/bin/bash -l

#$ -l h_rt=0:10:0
#$ -l mem=1G
#$ -pe mpi 36

#$ -N pi_36_ompi-4.1.0
#$ -cwd

module unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load numactl/2.0.12
module load binutils/2.36.1/gnu-10.2.0
module load ucx/1.9.0/gnu-10.2.0
module load /home/cceahke/openmpi4/.uclrc_modules/mpi/openmpi/4.1.0/gnu-10.2.0

gerun ./mpi_pi
```

My local test modulefile is like this:
```
#%Module -*- tcl -*-
## module_made (v2)
proc ModulesHelp { } {
  puts stderr {Adds openmpi 4.1.0 to your environment. The Open MPI Project is an open source Message Passing Interface implementation.}
}
module-whatis {Adds openmpi 4.1.0 to your environment. The Open MPI Project is an open source Message Passing Interface implementation.}

conflict openmpi
conflict mpi
prereq beta-modules
prereq gcc-libs/10.2.0
prereq compilers/gnu/10.2.0
prereq numactl/2.0.12
prereq binutils/2.36.1/gnu-10.2.0
prereq ucx/1.9.0/gnu-10.2.0

set prefix /home/cceahke/openmpi4

setenv MPI_HOME /home/cceahke/openmpi4
setenv MPI_RUN /home/cceahke/openmpi4/bin/mpirun
setenv GERUN_LAUNCHER openmpi-sge

prepend-path CMAKE_PREFIX_PATH $prefix
prepend-path PATH $prefix/bin
prepend-path PATH /shared/ucl/apps/openmpi/ucl-wrapper-omp3+/bin
prepend-path CPATH $prefix/include
prepend-path INCLUDE_PATH $prefix/include
prepend-path LIBRARY_PATH $prefix/lib
prepend-path LD_RUN_PATH $prefix/lib
prepend-path LD_LIBRARY_PATH $prefix/lib
prepend-path PKG_CONFIG_PATH $prefix/lib/pkgconfig
prepend-path MAN_PATH $prefix/share/man
```

Note that `prepend-path PATH /shared/ucl/apps/openmpi/ucl-wrapper-omp3+/bin` has to come after the `prepend-path PATH $prefix/bin` for our mpirun wrapper to be used.

**Comment by heatherkellyucl** [comment]
Testing my Myriad local install of OpenMPI using `c_mpi_pi`. Jobscript is like this:

```
#!/bin/bash -l

#$ -l h_rt=0:10:0
#$ -l mem=1G
#$ -pe mpi 36

#$ -N pi_36_ompi-4.1.0
#$ -cwd

module unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load numactl/2.0.12
module load binutils/2.36.1/gnu-10.2.0
module load ucx/1.9.0/gnu-10.2.0
module load /home/cceahke/openmpi4/.uclrc_modules/mpi/openmpi/4.1.0/gnu-10.2.0

gerun ./mpi_pi
```

My local test modulefile is like this:
```
#%Module -*- tcl -*-
## module_made (v2)

lappend auto_path /shared/ucl/apps/modulelibs/UsefulModuleFunctions
package require modulefunctions 1.0

proc ModulesHelp { } {
  puts stderr {Adds openmpi 4.1.0 to your environment. The Open MPI Project is an open source Message Passing Interface implementation.}
}
module-whatis {Adds openmpi 4.1.0 to your environment. The Open MPI Project is an open source Message Passing Interface implementation.}

conflict mpi
prereq beta-modules
prereq gcc-libs/10.2.0
prereq compilers/gnu/10.2.0

# Myriad requires UCX
if [modulefunctions::isCluster Myriad] {
    prereq numactl/2.0.12
    prereq binutils/2.36.1/gnu-10.2.0
    prereq ucx/1.9.0/gnu-10.2.0
}

set prefix /home/cceahke/openmpi4

setenv MPI_HOME /home/cceahke/openmpi4
setenv MPI_RUN /home/cceahke/openmpi4/bin/mpirun
setenv GERUN_LAUNCHER openmpi-sge

prepend-path CMAKE_PREFIX_PATH $prefix
prepend-path PATH $prefix/bin

# Myriad requires UCX
if { [modulefunctions::isCluster Myriad] } {
    prepend-path PATH              /shared/ucl/apps/openmpi/ucl-wrapper-ompi3+-ucx/bin
} else {
    prepend-path PATH              /shared/ucl/apps/openmpi/ucl-wrapper-omp3+/bin
}

prepend-path CPATH $prefix/include
prepend-path INCLUDE_PATH $prefix/include
prepend-path LIBRARY_PATH $prefix/lib
prepend-path LD_RUN_PATH $prefix/lib
prepend-path LD_LIBRARY_PATH $prefix/lib
prepend-path PKG_CONFIG_PATH $prefix/lib/pkgconfig
prepend-path MAN_PATH $prefix/share/man
```

Note that `prepend-path PATH /shared/ucl/apps/openmpi/ucl-wrapper-omp3+-ucx/bin` has to come after the `prepend-path PATH $prefix/bin` for our mpirun wrapper to be used.

**Comment by heatherkellyucl** [comment]
MPI jobs ran successfully. I also ran a quick 72-core run on the segment of the cluster where Economics can submit multi-node jobs and that also worked.

**Comment by heatherkellyucl** [comment]
### OpenMPI installs

The prereqs are now up to date everywhere so this can be installed.

- [ ] Myriad
- [ ] Kathleen
- [ ] test with c_mpi_pi on Kathleen
- [ ] Thomas (only for now as still in use)
- [ ] Michael (currently still rsynced from Thomas so done automatically)
- [ ] Young
- [ ] check modulefile
- [ ] deploy modulefile everywhere

**Comment by heatherkellyucl** [comment]
80-core c_mpi_pi test submitted on Kathleen.

**Comment by heatherkellyucl** [comment]
On Kathleen, test job failed because the two nodes picked different pmls for the ofi btl (the fabric being ofi is correct):
```
[node-c11a-018:60967] [[25793,1],1] selected pml cm, but peer [[25793,1],0] on node-c11a-018 selected pml ob1
[node-c11a-018][[25793,1],12][btl_ofi_component.c:238:mca_btl_ofi_exit] BTL OFI will now abort.
```
That is unusual and doesn't happen with 4.0.3...

Might need to make a new `/shared/ucl/apps/openmpi/ucl-wrapper-omp3+/bin` - currently on OmniPath machines it doesn't specify anything:

```
#!/bin/bash

# This wrapper "fixes" the OpenMPI mpirun on the single node job nodes.
# It does this by using the SGE variable $NHOSTS to determine if this
# is a multi-node job or not an enabling/disabling infinipath support.

# Patched to use vader rather than sm for OpenMPI 3+

# Owain Kenway, UCL, 1/5/2018

MPI_LAUNCHER=$MPI_RUN

# If the job is running on one node only, disable Infiniband (no need
# for it and it breaks on the single-node job nodes).
if [[ "$NHOSTS" == "1" ]]
then
  $MPI_LAUNCHER -mca pml ob1 -mca btl tcp,vader,self "$@"

# If the job is running interactively, disable Infiniband (i.e. login
# nodes). 
elif [[ "$NHOSTS" == "" ]]
then
  $MPI_LAUNCHER -mca pml ob1 -mca btl tcp,vader,self "$@"

# Otherwise, business as usual (Infiniband).
else 
  $MPI_LAUNCHER "$@"
fi
```

**Comment by heatherkellyucl** [comment]
Hmm, I submitted the same thing again just in case and got lots of
```
node-c11a-010.26963hfp_gen1_context_open: hfi_userinit_internal: failed, trying again (1/3)
node-c11a-010.26963hfi_userinit_internal: assign_context command failed: Device or resource busy
node-c11a-010.26963hfp_gen1_context_open: hfi_userinit_internal: failed, trying again (2/3)
node-c11a-010.26963hfi_userinit_internal: assign_context command failed: Device or resource busy
node-c11a-010.26963hfp_gen1_context_open: hfi_userinit_internal: failed, trying again (3/3)
node-c11a-010.26963hfi_userinit_internal: assign_context command failed: Device or resource busy
```
and then it went ahead and calculated pi.

I also have submitted one that sets `export OMPI_MCA_pml=cm` in the script. That very much failed.
```
node-c11a-031.6811PSM2 can't open hfi unit: -1 (err=23)
node-c11a-042.19957PSM2 can't open hfi unit: -1 (err=23)
[node-c11a-031:06786] PML cm cannot be selected
[node-c11a-031:06752] PMIX ERROR: UNREACHABLE in file server/pmix_server.c at line 2198
```

**Comment by heatherkellyucl** [comment]
On Kathleen, these are the `ompi_info` differences when that is run as part of the job.

4.0.3
```
         MCA btl: tcp (MCA v2.1.0, API v3.1.0, Component v4.0.3)
         MCA btl: self (MCA v2.1.0, API v3.1.0, Component v4.0.3)
         MCA btl: usnic (MCA v2.1.0, API v3.1.0, Component v4.0.3)
         MCA btl: vader (MCA v2.1.0, API v3.1.0, Component v4.0.3)

         MCA mtl: psm2 (MCA v2.1.0, API v2.0.0, Component v4.0.3)
         MCA mtl: ofi (MCA v2.1.0, API v2.0.0, Component v4.0.3)

         MCA pml: v (MCA v2.1.0, API v2.0.0, Component v4.0.3)
         MCA pml: ob1 (MCA v2.1.0, API v2.0.0, Component v4.0.3)
         MCA pml: monitoring (MCA v2.1.0, API v2.0.0, Component v4.0.3)
         MCA pml: cm (MCA v2.1.0, API v2.0.0, Component v4.0.3)
```

4.1.0
```
         MCA btl: ofi (MCA v2.1.0, API v3.1.0, Component v4.1.0)
         MCA btl: self (MCA v2.1.0, API v3.1.0, Component v4.1.0)
         MCA btl: usnic (MCA v2.1.0, API v3.1.0, Component v4.1.0)
         MCA btl: tcp (MCA v2.1.0, API v3.1.0, Component v4.1.0)
         MCA btl: vader (MCA v2.1.0, API v3.1.0, Component v4.1.0)

         MCA mtl: ofi (MCA v2.1.0, API v2.0.0, Component v4.1.0)

         MCA pml: v (MCA v2.1.0, API v2.0.0, Component v4.1.0)
         MCA pml: ob1 (MCA v2.1.0, API v2.0.0, Component v4.1.0)
         MCA pml: cm (MCA v2.1.0, API v2.0.0, Component v4.1.0)
         MCA pml: monitoring (MCA v2.1.0, API v2.0.0, Component v4.1.0)
```

We have lost the `mtl: psm2` and gained a `btl: ofi`.

**Comment by heatherkellyucl** [comment]
Submitted one with more verbose info to see what it is actually choosing in both cases:
```
gerun -mca mpi_show_mca_params --mca btl_base_verbose 10 --mca mtl_base_verbose 10 ./mpi_pi
```

**Comment by heatherkellyucl** [comment]
I am pretty sure we ought to still be using `psm2` for OmniPath for some components here, see https://www.open-mpi.org/faq/?category=running#mpi-ofi-support and the entry just below.

Might need to try this combination:
```
--mca pml cm --mca mtl ofi --mca mtl_ofi_provider_include psm2
```

> Currently, Open MPI supports PSM2 MTL and OFI MTL (using PSM2 OFI provider) components which can be used to communicate with Intel Omni-Path (OPA) software stack.

I am wondering if it needs to be told explicitly to build psm2 support now.

**Comment by heatherkellyucl** [comment]
In the config.log of a new build (on Young):
```
configure:332840: WARNING: PSM2 needs to be version 11.2.173 or later. Disabling MTL.
configure:333446: checking if MCA component mtl:psm2 can compile
configure:333448: result: no
```

**Comment by heatherkellyucl** [comment]
Going to build the newest 4.0.x instead, since that doesn't have the requirement for a newer libpsm2 than we currently have in the image.

- [ ] Myriad
- [ ] test on Myriad
- [ ] Kathleen
- [ ] test on Kathleen
- [ ] Young
- [ ] Thomas
- [ ] Michael (synced from Thomas)
- [ ] modulefile

**Comment by heatherkellyucl** [comment]
Working on Myriad (one- and two-node), Kathleen job is still in the queue so I'll try on one of the other clusters.

**Comment by heatherkellyucl** [comment]
Works across two nodes on Thomas.

**Comment by heatherkellyucl** [comment]
Done, module is in beta-modules as `mpi/openmpi/4.0.5/gnu-10.2.0`.

**Comment by dbretherton** [comment]
Thanks for sorting this out, Heather.  I wondered if the new module should be in beta-modules, though, or only in beta-modules.  I Could/should we put the new gcc 10 builds in the main list of modules, expecting people to discover them and start using them?

**Comment by heatherkellyucl** [comment]
It has to be in beta-modules for the moment as that is where the gcc-libs and compiler are. The plan was to move all of those modules out of beta-modules when we are ready to create the `default-modules-2021` for people to try. (And if we are switching to EasyBuild/Spack, we won't be using these exact modules anyway, probably).
