### ISSUE TITLE
Install request: VinaLC

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#41]
IN01261049

A parallelised version of AutoDock Vina, molecular docking.

Licensed under Apache License 2.0.

http://mvirdb1.llnl.gov/static_catsid/vina/

Requires boost, mentions boost-mpi as a possibility but says that it currently uses MPI directly.
> Beside the standard installation, you can also turn on the Boost MPI binding. Currently the program uses MPI library directly instead of Boost MPI

**Comment by owainkenwayucl** [comment]
I've installed VinaLC on both resources, using the GNU toolchain (it refused to build with Intel).
