### ISSUE TITLE
Install Request: ATLAS Ancient DNA Analysis [IN04576811]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#415]
ATLAS (Analysis Tools for Low-coverage and Ancient Samples):

https://bitbucket.org/wegmannlab/atlas/wiki/Home

Installation instructions here:

https://bitbucket.org/wegmannlab/atlas/wiki/Installing%20and%20Running%20ATLAS

Only looks suitable for Myriad (no MPI as far as I can tell).

**Comment by balston** [comment]
I will attempt to build Atlas next week. It doesn't appear too complicated from a first look at the documentation. It needs the following C++ library installed first:

http://arma.sourceforge.net/

**Comment by balston** [comment]
First need to build the Armadillo C++ library. Latest stable version is 10.3.0 so start with that version. Dependencies from the README file are:
- modern C++ (at least the C++11) so no GNU 4.9.2;
- OpenBLAS (already have this for GNU 10.x);
- ARPACK - Already have this but will need to re-build for GNU 10.x;
- SuperLU - need to build for GNU 10.x.

**Comment by balston** [comment]
Updated build script for ARPACK to version 3.8.0 using the following modules:
```
require gcc-libs/10.2.0
require compilers/gnu/10.2.0
require openblas/0.3.13-native-threads/gnu-10.2.0
```
Building using:
```
module load beta-modules
module -f unload gcc-libs
./arpack-ng-3.8.0-gnu_install
```

**Comment by balston** [comment]
ARPACK:
```
Installed to: /shared/ucl/apps/arpack-ng/3.8.0-threaded/gnu-10.2.0
Module files put in: /tmp/arpack-ng-modules.X6D4nIXL
```
on login13.

**Comment by balston** [comment]
I've made a copy of the module files in my Software/ARPACK directory on Myriad and will add them to rcps-modulefiles tomorrow.

**Comment by balston** [comment]
Module added to beta-modules and uploaded to Myriad. Use module commands:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load openblas/0.3.13-native-threads/gnu-10.2.0
module load arpack-ng/3.8.0-threaded/gnu-10.2.0
```

**Comment by balston** [comment]
I've made a copy of _superlu-5.2.1_install_ in _superlu-5.2.1-GNU_install_ so I don't mess up the original.

**Comment by balston** [comment]
SuperLU:
```
Installed to: /shared/ucl/apps/superlu/5.2.1/gnu-10.2.0
Module files put in: /tmp/superlu-modules.WvAmTD1G
```
on login12.

**Comment by balston** [comment]
I've made a copy of the module files in my Software/SuperLU directory on Myriad and will add them to rcps-modulefiles next week.

**Comment by balston** [comment]
Messed up the build of SuperLU on Friday because I missed some necessary updates to the build script. Updating and rebuilding ...

**Comment by balston** [comment]
Completed and module uploaded on Myriad. Need to use the following module commands:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load openblas/0.3.13-native-threads/gnu-10.2.0
module load superlu/5.2.1/gnu-10.2.0
```

**Comment by DcornishUCL** [comment]
Hi, 

Thank you very much for doing this, apologies but just to check is ATLAS itself compiled here, or is this in progress? 

Best, 

Dean

**Comment by balston** [comment]
So both missing prerequisites for building the Armadillo C++ library  have now been built and installed complete with module files. The next step is to build Armadillo.

**Comment by balston** [comment]
First stab at a build script for the Armadillo C++ library ready for testing.

**Comment by balston** [comment]
Running:
```
module -f  unload compilers mpi gcc-libs
module load beta-modules
./Armadillo-10.4.0_install 2>&1 | tee ~/Software/Armadillo-10.4.0_install.log-16042021-1
```

**Comment by balston** [comment]
The make failed before the make install step. Updating the build script to remove the:
```
make check
```
step.

**Comment by balston** [comment]
Another change was needed to reorder the environment variable defines to pick up COMPILER_TAG correctly. Finally installed without errors at the third attempt. Now to produce a module file for Armadillo.

**Comment by balston** [comment]
Module file done and uploaded to Myriad. Need to use the following module commands:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load openblas/0.3.13-native-threads/gnu-10.2.0
module load arpack-ng/3.8.0-threaded/gnu-10.2.0
module load superlu/5.2.1/gnu-10.2.0
module load armadillo/10.4.0/gnu-10.2.0
```

**Comment by balston** [comment]
All perquisites done so the next step is to produce a build script for ATLAS itself using the modules in the last comment.

**Comment by balston** [comment]
I need to fix the Armadillo module as I messed it up.

**Comment by balston** [comment]
Fixed.

**Comment by balston** [comment]
No obvious version number in the ATLAS download - it is just done as a git clone:
```
git clone --depth 1 https://bitbucket.org/WegmannLab/atlas.git
```
from the installation instructions. Will need to include the build date in installation directory and module file.

**Comment by balston** [comment]
Build script ready. Running:
```
module -f  unload compilers mpi gcc-libs
module load beta-modules
./ATLAS-ADNA_install 2>&1 | tee ~/Software/ATLAS-ADNA_install.log-16042021-1
```

**Comment by balston** [comment]
Build has finished and there doesn't appear to be any errors. Now producing a module file.

**Comment by balston** [comment]
Module file done. Need to use the following module files:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load openblas/0.3.13-native-threads/gnu-10.2.0
module load arpack-ng/3.8.0-threaded/gnu-10.2.0
module load superlu/5.2.1/gnu-10.2.0
module load armadillo/10.4.0/gnu-10.2.0
module load atlas-adna/0.9_2021-04-16/gnu-10.2.0
```

**Comment by balston** [comment]
User informed.

**Comment by DcornishUCL** [comment]
Hi, thanks very much for installing all this. I hope it will be useful for everyone.

**Comment by DcornishUCL** [comment]
I have tested out a couple of ATLAS' functionalities: BAMDiagnostics, PMD and GLF and it appears to work perfectly. 

Thanks,
Dean

**Comment by balston** [comment]
This is now completed on Myriad. It cannot run on Kathleen as it doesn't support MPI.

**Comment by balston** [comment]
There is a bug in ATLAS according to the developers which is causing problems with our build:

We need to alter one of the C++ source files. They have suggested we 

> modify line 1520 of file TGenome.cpp replacing "alignmentParser.bamHeader.ReadGroups.Add(readGroupTruncated);" with "alignmentParser.readGroups.addTruncatedOrMergedRG(alignmentParser.bamHeader, vec[0], readGroupTruncated);" 

I'm checking if they have updated their Git repro.

**Comment by balston** [comment]
They haven't updated their Git repro with this fix so I will make a temporary version of our build script that includes the bug fix.

**Comment by DcornishUCL** [comment]
Hi, I just wondered if you had been able to fix this bug yet? If so, I can run a script and see if it works as we anticipate.

**Comment by DcornishUCL** [comment]
Hi, I am sorry to ask again but I wondered if the bug fix has been completed for ATLAS? I really require this to do my analysis.

**Comment by balston** [comment]
I'm updating the build script to try out this fix.

**Comment by balston** [comment]
Build script run without errors. It installs into a new location so now need to update the module file.

**Comment by balston** [comment]
Module file updated. For the bug fixed version use:
```
module -f unload compilers mpi gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load compilers/gnu/10.2.0
module load openblas/0.3.13-native-threads/gnu-10.2.0
module load arpack-ng/3.8.0-threaded/gnu-10.2.0
module load superlu/5.2.1/gnu-10.2.0
module load armadillo/10.4.0/gnu-10.2.0
module load atlas-adna/0.9_2021-08-13/gnu-10.2.0
```

**Comment by DcornishUCL** [comment]
This bug fix was relevant to ATLAS task SplitMerge https://bitbucket.org/wegmannlab/atlas/wiki/splitMerge I have tested SplitMerge and it appears to function normally outputting:

                     Atlas 0.9
                    -----------
 Wegmann Lab - University of Fribourg, Switzerland
      https://bitbucket.org/wegmannlab/atlas
  Commit 647daf792df01c4aa8e686de0e462ddd8f91e6c6
- Splitting single-end reads and merging paired-end reads and in BAM file (task = splitMerge):
