### ISSUE TITLE
Install Request: Space Ranger

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#416]
IN:04581274

Space Ranger is a set of analysis pipelines that process Visium spatial RNA-seq output and brightfield and fluorescence microscope images in order to detect tissue, align reads, generate feature-spot matrices, perform clustering and gene expression analysis, and place spots in spatial context on the slide image. 

https://support.10xgenomics.com/spatial-gene-expression/software/downloads/latest
https://support.10xgenomics.com/spatial-gene-expression/software/overview/system-requirements
https://support.10xgenomics.com/spatial-gene-expression/software/pipelines/latest/installation

License: 10X Genomics
> 4.1    General Restrictions. Licensee shall not, and shall not authorize or permit any third party to: (a) sell, lease, license, sublicense, or otherwise transfer the Licensed Software or the Documentation; (b) provide, disclose, or make the Licensed Software or Documentation available to any third party, or permit access to or use of the Licensed Software or Documentation by any person other than Licensee's employees, agents, or contractors who are, by agreement, bound by the terms of this Agreement to the same extent as Licensee; 

Not sure if that means IT Purchasing need to sign the license for all of UCL.

**Comment by ikirker** [comment]
Having already installed Cell Ranger, another one of their tools with the same licence, I decided it was fine because UCL as an entity already agreed to the licence when they purchased the instrument.

**Comment by ikirker** [comment]
Downloaded Spaceranger and the reference datasets to the `pkg-store`.

**Comment by ikirker** [comment]
Installed, testing.

**Comment by ikirker** [comment]
Seems to work correctly. Have informed user.
