### ISSUE TITLE
Install request: cancerit suite

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#42]
IN01315017

https://github.com/cancerit

In particular these:
BRASS (depends on grass, VAGrENT, cgpVcf)
CaVEMan and cgpCaVEManPostProcessing
gcpIndel
ascatNgs

There are a great many dependencies needed for all these, some of which we have as modules already.

**Comment by balston** [comment]
I've finally been able to build all the dependencies necessary to build BRASS. The build of BRASS appears to have completed successfully. To use BRASS the following modules need to be loaded:
```
module unload compilers mpi
module load r/recommended
module load htslib/1.2.1 
module load perl/5.22.0
module load curl/7.47.1/gnu-4.9.2
module load fasta/36.3.8d/gnu-4.9.2
module load bedtools/2.25.0
module load exonerate/2.2.0
module load velvet/1.2.10
module load python2/recommended
module load boost/1_54_0/gnu-4.9.2
module load cancerit/gnu-4.9.2
```
Next steps are to build the other requested components:
- CaVEMan and cgpCaVEManPostProcessing
- gcpIndel
- ascatNgs

**Comment by balston** [comment]
I've now installed:
- CaVEMan and cgpCaVEManPostProcessing

There is a slight change in the modules needed as cgpCaVEManPostProcessing requires a more recent version of HTSlib. The modules needed now are:
```
module unload compilers mpi
module load r/recommended
module load htslib/1.3.1 
module load perl/5.22.0
module load curl/7.47.1/gnu-4.9.2
module load fasta/36.3.8d/gnu-4.9.2
module load bedtools/2.25.0
module load exonerate/2.2.0
module load velvet/1.2.10
module load python2/recommended
module load boost/1_54_0/gnu-4.9.2
module load cancerit/gnu-4.9.2
```

**Comment by balston** [comment]
- gcpIndel
- ascatNgs

have now been installed.

We've now installed all requested components of cancerit.

**Comment by balston** [comment]
I've added a module bundle that simplifies the module commands need co the cancerit suite. All you need to load now is:
```
module unload compilers mpi
module load cancerit/recommended
```

**Comment by ikirker** [comment]
Not heard anything from requester, appears to be working: closing.
