### ISSUE TITLE
Install Request: DL_POLY 4 version 5.0.0

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#421]
DL_POLY_4 has gone LGPL, so if we install 5.0.0 it will not need to be restricted to members of `lgdlp410` or similar group.

https://gitlab.com/ccp5/dl-poly/-/releases/5.0.0
https://ccp5.gitlab.io/setup-dlpoly/index.html

**Comment by ikirker** [comment]
Installed.

**Comment by ikirker** [comment]
(Note: this is a vanilla, no extras install. It seems like the cmake build mechanism is new? And still has some problems with the optional features and add-ins.)

**Comment by ikirker** [comment]
(Did anyone actually request this?)

**Comment by heatherkellyucl** [comment]
No, I added this when the non-restricted version was announced.

**Comment by ikirker** [comment]
Fair enough. Closing as done, then.
