### ISSUE TITLE
Install Request: GROMACS 2021.2 - IN:04611444

### ISSUE THREAD

**Issue by themkots** [UCL-RITS/rcps-buildscripts#429]
Patch release available:
~~https://gromacs.bioexcel.eu/t/gromacs-2021-1-patch-release-available/1714~~
https://gromacs.bioexcel.eu/t/gromacs-2021-2-patch-release-available/2102

**Comment by heatherkellyucl** [comment]
Updating to request 2021.2 as just released.

**Comment by heatherkellyucl** [comment]
Install was done, modules are:

```
module load beta-modules
module unload -f compilers mpi gcc-libs
module load gcc-libs/7.3.0
module load compilers/gnu/7.3.0
module load mpi/openmpi/3.1.4/gnu-7.3.0
module load python3
module load gromacs/2021.2/gnu-7.3.0
```

**Comment by heatherkellyucl** [comment]
On Michael I've also submitted a job as ccspapp to do the avx512 build for the A-type nodes.

Referred to by this bit in the modulefile:
```
if { [modulefunctions::isCluster michael] } {
   if { [modulefunctions::hasArch avx512] } {
      set prefix /shared/ucl/apps-overrides/avx512/gromacs/2021.2/gnu-7.3.0

   }    
}
```

Script in `/home/ccspapp/Scratch/gromacs-avx512` - this is done as a job because it has to be built on an A-type node and not a login node.
```
#!/bin/bash -l

#$ -l h_rt=6:0:0
#$ -l mem=2G
#$ -pe smp 40
#$ -N GROMACS_2021.2_avx512_install

#$ -cwd

#$ -ac allow=A
#$ -P Unavailable 

cd /shared/ucl/apps/build_scripts
INSTALL_PREFIX=/shared/ucl/apps-overrides/avx512/gromacs/2021.2/gnu-7.3.0 ./gromacs-2021.2_install
```
