### ISSUE TITLE
Install request: CRYSTAL 14 1.0.4

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#43]
IN01315433

> The version contains a fix for a particular bug that I've been experiencing whilst running the current version (v1.0.3) on Grace, to do with restarting vibrational frequency calculations.

**Comment by balston** [comment]
Working on this. Hope to get it sorted next week.

**Comment by balston** [comment]
Our Crystal14 build script has been updated for 1.0.4 and I've downloaded the new archives from the Crystal14 license portal. Beginning the installation now.

**Comment by balston** [comment]
Installation completed and tested with a couple of supplied examples. A new module file has been supplied so need to load the following modules:
```
module unload mpi/intel/2015/update3/intel
module load mpi/openmpi/1.8.4/intel-2015-update2
module load crystal14/v1.0.4
```
There is an example run script in:
```
/shared/ucl/apps/Crystal14/v1.0.4/run_Crystal14_p.sh
```

**Comment by balston** [comment]
We will also install V1.0.4 on Legion as well.

**Comment by heatherkellyucl** [comment]
User has confirmed the new version is working.
