### ISSUE TITLE
Install Request: CellRanger 6 [IN:04630463] on Myriad

### ISSUE THREAD

**Issue by themkots** [UCL-RITS/rcps-buildscripts#433]
Application: CellRanger 6

Single-cell transcriptmics and multimodal analysis now require a new version of Cellranger (version 06):
https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/release-notes?mkt_tok=NDQ2LVBCTy03MDQAAAF7_yP4Qk7pFUYXotI-G44XDS_QETl9l-TeDejGRN_THKbzHQLD3I2u0PGgjdQyMRtc_YT3BRcQBX2KPribRyACg6APAE2ptOP64FKetyFQ6ZOrfA

**Comment by themkots** [comment]
Requester classifies this as an update.
We have CellRanger V05 in Myriad: 
(closed issue:) https://github.com/UCL-RITS/rcps-buildscripts/issues/392

**Comment by ikirker** [comment]
Done, 6.0.1, have informed user.
