### ISSUE TITLE
Install Request: Qiime2 - Microbiome research interface [IN:04631366] on Myriad

### ISSUE THREAD

**Issue by themkots** [UCL-RITS/rcps-buildscripts#434]
Dear Support Team,

I would like to use Myriad to train some taxonomy classifiers.
This is done through Qiime2, a command-line interface that is typically built with conda, as the number of employed packages is huge:
https://raw.githubusercontent.com/qiime2/environment-files/master/2021.2/release/qiime2-2021.2-py36-linux-conda.yml

**Comment by themkots** [comment]
Further requester comments:

Alternatively, I believe Qiime is valuable enough to be installed centrally, as it is a goto platform for microbiome research that evidently has some resource-intensive tasks.

 

A typical local installation would be:

`wget https://data.qiime2.org/distro/core/qiime2-2021.2-py36-linux-conda.yml`

`conda env create -n qiime2-2021.2 --file qiime2-2021.2-py36-linux-conda.yml`

`rm qiime2-2021.2-py36-linux-conda.yml`
 

And my task requires a very popular qiime package RESCRIPt:

`conda install -c conda-forge -c bioconda -c qiime2 -c defaults xmltodict`

`pip install git+https://github.com/bokulich-lab/RESCRIPt.git`

**Comment by ikirker** [comment]
Much like Spack, the whole point of Conda is that the user should be able to do this themselves.

*Un*like Spack, as far as I know Conda will not work well for a centralised installation.
