### ISSUE TITLE
Install Fix: GATK 4.0.8.0 CNNScoreVariants and other tools [IN:04618810]

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#437]
IN: 04618810

Some of the new tools with GATK 4 require Python, Tensorflow and other packages, so are not currently working.

If they are missing, CNNScoreVariants will just hang without errors after
`INFO  CNNScoreVariants - Done initializing engine`

Loading these was not sufficient:
```
module load java/1.8.0_92
module load gatk/4.0.8.0
module load python3/3.7
module load tensorflow/2.0.0/mkl-py37
```

Current requirements: https://github.com/broadinstitute/gatk#requirements
They use conda for their python environment: https://github.com/broadinstitute/gatk/blob/master/scripts/gatkcondaenv.yml.template

**Comment by owainkenwayucl** [comment]
Do we have a test case for this?

**Comment by owainkenwayucl** [comment]
This looks like the kind of software gore that entertains me - I'll take a look.

**Comment by owainkenwayucl** [comment]
I think the best way to achieve this is to:

 - [ ] - Update miniconda (coincidentally I did a miniconda install in my own home dir recently so I can re-use that script)/
 - [ ] - Install latest GATK (4.2.5.0) but make sure it explicitly sets up the tools we need for python/conda

**Comment by owainkenwayucl** [comment]
Right.

So interesting issues.

A while back I spent some time trying to get the aliases set up by conda when it does `source /shared/ucl/apps/miniconda/4.10.3/etc/profile.d/conda.sh` in your `.bashrc` into the module file and deployed a test module for me.  This does *not* work on the newer, more modern version of environment modules on Young/Kathleen - loading the miniconda module results in errors.

I suspect a path of this is:

1. Do not make the gatk module depend on miniconda
2. Make the module print out a message saying that "for some additional tools you need to add the miniconda module and set up the appropriate environment.
3. In the miniconda module print out a message saying you need to `source /shared/ucl/apps/miniconda/4.10.3/etc/profile.d/conda.sh`

**Comment by mmistry4** [comment]
User hasnt responded since Feb 22, closing ticket
