### ISSUE TITLE
Install Request:  Julia 1.6 on Young [IN04634265]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#438]
https://julialang.org/downloads/platform/

 We already have julia/1.5.0 but user wants ton  use new features that are only in 1.6.

**Comment by heatherkellyucl** [comment]
This is just a binary install, so adding everywhere.

- [ ] Young
- [ ] Thomas
- [ ] Kathleen
- [ ] Myriad
- [ ] modulefile

**Comment by heatherkellyucl** [comment]
This version does need a newer gcc-libs than our `gcc-libs/4.9.2` - works with `gcc-libs/10.2.0` from beta-modules.

**Comment by heatherkellyucl** [comment]
For now:
```
module unload -f gcc-libs
module load beta-modules
module load gcc-libs/10.2.0
module load julia/1.6.0
```

**Comment by heatherkellyucl** [comment]
Finished, informed requestor.

**Comment by heatherkellyucl** [comment]
They've tested it with some packages, seems to be working.

**Comment by owainkenwayucl** [comment]
Just a note - I decided to change this approach since Julia bundles the GCC libraries it is linked against - it uses a wrapper now as this should always work: https://github.com/UCL-RITS/rcps-buildscripts/blob/master/files/julia/julia.sh
