### ISSUE TITLE
Install request: Amber 16

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#44]
We've received a request via ISD Purchasing to upgrade Amber on Legion and Grace to version 16.

**Comment by balston** [comment]
ISD Purchasing are arranging the signing of the Amber 16 license.

**Comment by balston** [comment]
The Amber 16 license has been signed and Amber 16 files are now in:
```
/home/ccspapp/Software/Amber/16
```
on Legion.

**Comment by ikirker** [comment]
Installed and modules added.
