### ISSUE TITLE
Install Request: Ipopt on Myriad [IN04636856]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#440]
Economics would like Ipopt on Myriad:

> Ipopt is a software package for solving constrained nonlinear programming
> problems.
> It is available under a free license.
> 
> Could you install it on Myriad?
>

https://coin-or.github.io/Ipopt/INSTALL.html

**Comment by heatherkellyucl** [comment]
Needs a differently-built MUMPS. 

They have a build system to build current MUMPS in a way that lpopt requires: GitHub - coin-or-tools/ThirdParty-Mumps: COIN-OR autotools harness to build Mumps
