### ISSUE TITLE
Install Request: HDF5 1.10.6 with parallel+fortran, built with gcc10

### ISSUE THREAD

**Issue by tmbgreaves** [UCL-RITS/rcps-buildscripts#441]
Application: HDF5 with parallel+fortran, version 1.10.6, built with gcc10.

Link: https://portal.hdfgroup.org/display/support/Download+HDF5

Cluster: Young

Description: high performance data software library and file format to manage, process, and store heterogeneous data

License: open source, other: https://www.hdfgroup.org/licenses

Special versions or variants: I need parallel and fortran enabled, ie:

```
<source>/configure --enable-fortran --enable-parallel
```

Please could you build this using gcc10.

**Comment by mmistry4** [comment]
@tmbgreaves This should be built on young for you, can you give it a go and let me know if it works?

**Comment by mmistry4** [comment]
- [x] Myriad
- [x] Young
- [ ] Kathleen
- [ ] Thomas
- [ ] Michael
