### ISSUE TITLE
Install Request: GATK 4.2.1.0 on Myriad [IN:04814219]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#455]
From the requester:

> I am currently working on a bioinformatics project, and looking to be able to convert vcf files to maf files for further analysis. I have found a tool that can do this, Funcotator, which is part of GATK. However, the version of GATK on Myriad is 4.0.8.0, which only has a beta (and not fully functioning) version of Funcotator. Is there any way that the Myriad version of GATK can be updated to 4.2.0.0 (or higher - the most up-to-date version is 4.2.1.0) so I can use Funcotator on the cluster? I have several hundred samples to analyse,  so running all of these on my local computer isn't very practical but not being able to convert vcf files to maf is a major roadblock to my work. I'm sure that all of the bioinformaticians who regularly use GATK would also appreciate a more up-to-date version with the new tools being available on the cluster. 

All we do is pull down the binary versions from: https://github.com/broadinstitute/gatk/releases I think so should be fairly quick to do.

**Comment by balston** [comment]
Module file updated. Will need to use module commands:
```
module load java/1.8.0_92
module load gatk/4.2.1.0
```
to use this version.

**Comment by heatherkellyucl** [comment]
See #437 with GATK 4.2.5.0
