### ISSUE TITLE
Request access to licensed software: VASP 5.4.4

### ISSUE THREAD

**Issue by urmimala-dey** [UCL-RITS/rcps-buildscripts#464]
Licensed software: VASP 5.4.4

Full Name: Urmimala Dey

username: mmm1076

Email address: urmimala.dey@durham.ac.uk

Name of the main VASP license holder: Dr Nicholas Bristowe

VASP license number: 21-0246 5-2507

**Comment by ikirker** [comment]
As far as I can tell, this has been completed, so I'm closing it. 

Please note, anyone reading this: you should contact the email support address (<mailto:rc-support@ucl.ac.uk>) rather than opening this kind of issue here.
