### ISSUE TITLE
Install Request:  Ansys Fluent install for use by Brunel on Young 

### ISSUE THREAD

**Issue by edwardsmith999** [UCL-RITS/rcps-buildscripts#471]
Application: Latest version (Ansys Fluent 2022)

Link: https://www.ansys.com/products/fluids/ansys-fluent
but install files should be possible to obtain from Brunel from the following,
Jeremy Baxter (Staff) <Jeremy.Baxter@brunel.ac.uk>
Mayo Adetoro (Staff) <Mayo.Adetoro@brunel.ac.uk>
Tony Morris (Staff) <Tony.Morris@brunel.ac.uk>
I've emailed Jeremy, Mayo and Tony to notify about this.

Cluster: Young

Description: fluid dynamics simulation tool

License: Commercial license, will need to link to Brunel license server

Special versions or variants: Standard install with all components

Ticket number: IN:00000000

**Comment by balston** [comment]
Hi Ed,

Please could you email _rc-support AT ucl.ac.uk_ from the email address associated with your Young account so we can tie this request to the correct Young account. Thanks,

Brian

**Comment by heatherkellyucl** [comment]
This one is definitely still current.

**Comment by balston** [comment]
We are going to install ANSYS on Young today. The software installation should be completed by the end of the day but enabling access to the Brunel ANSYS License Manager is likely to take longer and may require changes at the Brunel end to allow access to the Brunel license server for Young.

**Comment by balston** [comment]
ANSYS is now installed on Young with access only for members of the _lgansbru_ reserved application group. The next step is to enable access to the Brunel ANSYS License Manager.

**Comment by balston** [comment]
Access to Brunel ANSYS License Manager enabled.

Test jobs have worked. Now installing module file.

**Comment by balston** [comment]
The module file for ANSYS is now in place and I've run a final test job using the real module. The module commands you need to access ANSYS for Brunel on Young are:
```
module load brunel-modules
module load ansys/2021.r2-brunel
```
These will need to be included in all job scripts. Also before submitting any jobs you MUST load the modules once in an interactive session. This is so the various ANSYS user files are created and correctly linked to your Scratch directory. 

I've also included an example ANSYS Fluent job script in:
```
/shared/ucl/apps/ANSYS/fluent-examples/run-ANSYS-fluent-2021.R2-par-IntelMPI-80_Brunel.sh
```
You can copy this and modify it for your use.

**Comment by balston** [comment]
Users at Brunel have been able to run ANSSYS jobs on Young.
