### ISSUE TITLE
Install Request: Update Emacs to 27.2 [IN05217784]

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#480]
Emacs is part of the default module set on all clusters. We have been asked to  install the latest version - 27.2 https://www.gnu.org/savannah-checkouts/gnu/emacs/emacs.html#Releases

**Comment by owainkenwayucl** [comment]
Actual current version is 28.1.

**Comment by owainkenwayucl** [comment]
Done
