### ISSUE TITLE
Install request: Opensees

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#49]
IN01814544

> OpenSees is a software framework for developing applications to simulate the performance of structural and geotechnical systems subjected to earthquakes.

http://opensees.berkeley.edu
http://opensees.berkeley.edu/WebSVN/listing.php?repname=OpenSees&path=%2Ftrunk%2FSRC

They provide Windows and Mac binaries only, we'd need to compile from source (and edit a Makefile.def as they don't use configure at present).

**Comment by ikirker** [comment]
<http://opensees.berkeley.edu/wiki/index.php/Compilation_Guideline_of_OpenSeeMP_on_Linux_Machines>

I can't say this is the most elegant installation process I've ever seen. I've [posted on their forum](http://opensees.berkeley.edu/community/viewtopic.php?f=3&t=63582) for some clarification over versions: there aren't any version tags in the SVN repo for versions after 2.2.2 but it looks like checking out the SVN repo is the only way to get the source, so...

**Comment by heatherkellyucl** [comment]
User I was helping with OpenSees in their home is still having problems (IN:04596595, IN:04445474).

I had got a serial build to the point where it asks for input, but didn't have any test input for it.

EasyBuild has OpenSees recipes including OpenSees-parallel. This was listed as a potential investigation candidate.

**Comment by ikirker** [comment]
Note that OpenSees is now on GitHub, though the website is still broken and won't get you to [the page where it tells you that](<https://opensees.berkeley.edu/OpenSees/developer/svn.php>). 

<https://github.com/OpenSees/OpenSees/releases/>
