### ISSUE TITLE
Install request: waves2Foam for OpenFOAM (3 or 4?)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#51]
IN01847774

https://openfoamwiki.net/index.php/Contrib/waves2Foam

waves2Foam is an additional library and solver for OpenFOAM. 

Was going to suggest building it for OpenFOAM 3, but it appears OpenFOAM 4 just came out two days ago - check on waves2Foam compatibility when we start this, as 4 is not currently mentioned.

**Comment by heatherkellyucl** [comment]
Sounds like OpenFOAM 3 should be used.

> I have asked waves2Foam if they will be releasing a version for OpenFOAM 4.0.0 soon, they said they should do but due to significant changes to the source code it may lack some of its original functionality. So I personally would recommend updating to version 3 of OpenFOAM.

**Comment by balston** [comment]
OpenFOAM is setup so users can install their own modules.

waves2Foam is designed to be installed by the user and not centrally.

**Comment by ikirker** [comment]
User has been informed and has the version of OpenFOAM they wanted (2.4.0).
