### ISSUE TITLE
Install Request: Update stand alone cuda/cudnn packages to at least 11.4+8.6 respectively

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#517]
Tier 2 users want to build Jax which presently requires at least Cuda 11.4 and CuDNN 8.6.  Both are user installable but we should make sure there are central packages and drivers are updated.

Application: Cuda 11.4 + CuDNN 8.6

Cluster: Myriad/Young

**Comment by owainkenwayucl** [comment]
I think a problem here is going to be driver versions - looks like Young is on 460.32.02.

We need to get at least 470.82.01

**Comment by owainkenwayucl** [comment]
Related Jira issue https://ucldata.atlassian.net/browse/ARI-254

**Comment by heatherkellyucl** [comment]
This was partly done already (Cuda 11.8 and 12.2 are available and the drivers updated to 535.54.03-C12.2).

Have buildscripts and modulefiles for `cudnn/9.2.0.82/cuda-11` and `cudnn/9.2.0.82/cuda-12`.

- [ ] Myriad
- [ ] Young
