### ISSUE TITLE
Install request: GROMACS+plumed+matheval

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#52]
IN01848479

Our plumed isn't built with libmatheval which limits what you can do.

libmatheval needs to be patched to not use guile (which is only used in tests).

https://groups.google.com/forum/#!msg/plumed-users/BE3abBvsPOE/bTHke7bqMnUJ

Patch file for libmatheval-1.1.11.tar.gz added at https://github.com/UCL-RITS/rcps-buildscripts/blob/master/patches/libmatheval-1.1.11_noguile.patch

then

```
autoreconf -fi
./configure --prefix=$INSTALL_PREFIX --with-pic
make
make install
```

**Comment by heatherkellyucl** [comment]
Libmatheval installed on Legion as `libmatheval/1.1.11`

- [ ] Build on Grace after outage.

**Comment by ikirker** [comment]
Built PLUMED 2.2.3 on Legion with libmatheval.

- [ ] Build on Grace after outage.
