### ISSUE TITLE
Install request: CUDA drivers   [IN05893965]

### ISSUE THREAD

**Issue by cjlegg** [UCL-RITS/rcps-buildscripts#528]
Package: CUDA Drivers (Update)
Detail: Heather Kelly says there is a plan somewhere to update these
Ticket/requester: [IN05893965](https://ucl--bmcservicedesk.vf.force.com/apex/BMCServiceDesk__ConsoleRedirect?formulaFieldName=IncidentLaunchConsole&recordName=05893965&recordId=a1N07000004WYRs&incType=Incident&isdtp=vw&uiTheme=Theme3&formLayoutId=)
Cluster: Myriad GPU nodes

**Comment by heatherkellyucl** [comment]
These are done. CUDA 12.2 equivalent drivers.
