### ISSUE TITLE
Install Request: FreeSurfer 7.4

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#544]
IN:06092300

Wanted for EasyReg "deep learning registration of brain MRI", which exists in 7.4: https://surfer.nmr.mgh.harvard.edu/fswiki/EasyReg

Uses tensorflow? Checking to see which version it would want to install as the docs do not say.

Paper [A ready-to-use machine learning tool for symmetric multi-modality registration of brain MRI](https://www.nature.com/articles/s41598-023-33781-0) says "The networks are implemented in TensorFlow/Keras. Crucially, the inference code is implemented in a version of Python that is distributed with FreeSurfer, such that users do not need to create virtual environments and install dependencies."

**Comment by balston** [comment]
build script is erroring at the MATLAB runtime stage:
```
ERROR: must set FREESURFER_HOME before installing
INFO: if you're using sudo, make sure to pass the FS home variable with
INFO: sudo FREESURFER_HOME=$FREESURFER_HOME fs_install_mcr R2019b
```
We didn't need this with the previous version. Will correct and rerun.

**Comment by balston** [comment]
This time the build script completes with out errors.

**Comment by balston** [comment]
module file ready.

Now need to test.

**Comment by balston** [comment]
Almost there - I forgot to download and install an updated license file.

**Comment by balston** [comment]
Test job worked! Took almost 3 hours to run.

**Comment by balston** [comment]
User contacted.

**Comment by heatherkellyucl** [comment]
(Does this still need installing anywhere else or is it done?)

**Comment by balston** [comment]
FreeSurfer doesn't support MPI so we don't really need to install it on Kathleen.
