### ISSUE TITLE
Install Request: Singularity/Apptainer MRSR

### ISSUE THREAD

**Issue by cdkharris** [UCL-RITS/rcps-buildscripts#553]
Application: Singularity v3.8 and/or Apptainer (most recent stable release)

Link:
Singularity v3.8 <https://apptainer.org/admin-docs/3.8/>
Apptainer mrsr <https://apptainer.org/docs/admin/latest/>

Cluster: Myriad

Description: Singularity is a container platform for HPC clusters. Apptainer is the continuation of Singularity under a new name.

License: [mostly LBNL](https://github.com/apptainer/apptainer/blob/main/LICENSE.md)

Special versions or variants: The request was not specific about what version they need, just a later version than Singularity v3.5 which we have installed. Singularity v3.8 is the last version under the name "Singularity". If possible I recommend that we install Apptainer, since it is currently being maintained.

Ticket number: IN06189958

**Comment by heatherkellyucl** [comment]
Apptainer is able to run Docker containers without converting them first, unlike earlier versions of Singularity so updating is a benefit. 

This change requires an update to the system image on the clusters, so needs involvement from the Infrastructure team.

(In theory you can install Apptainer as a user but we haven't got that working).

**Comment by heatherkellyucl** [comment]
Jira: https://ucldata.atlassian.net/browse/ARI-376

**Comment by gemmashireby** [comment]
Hi, has this been updated yet? Thanks for your help.

**Comment by heatherkellyucl** [comment]
Not yet, we've been doing some testing and planning. There'll be an email to the mailing lists soonish with dates once those are confirmed. (There are other outages to schedule that we might try and do this at the same time as).

**Comment by cdkharris** [comment]
Completed at the end of October; see [this page](https://www.rc.ucl.ac.uk/docs/Software_Guides/Singularity/) in our documentation for details. Myriad is currently running Apptainer v1.2.4-1.
