### ISSUE TITLE
Install request: Novoalign

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#56]
IN01871825

http://www.novocraft.com/products/novoalign/

With MPI support, specifically for Grace usage. License file provided.

**Comment by ikirker** [comment]
Installed on Legion. Note that the MPI version license is a trial license and will have to be replaced at some point. (I don't know what the duration is.)

**Comment by ikirker** [comment]
Note: this was also installed on Grace on 2016-08-30. See UCL-RITS/research-computing#1341. (I believe the user was informed at the time, but the issue doesn't record that. 😨)

Closing, accordingly.
