### ISSUE TITLE
Install Request: Gnuplot 6.0

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#562]
IN:06307269

Requested for new features, fewer bugs than 5.2.

Good candidate for updating an old buildscript (https://github.com/UCL-RITS/rcps-buildscripts/blob/master/gnuplot-5.0.1_install) to the new style.

**Comment by cdkharris** [comment]
from the v6.0 rc2 release notes:

> Installation
> ------------
> 
> You can download a source tarball for the current gnuplot version
> from the gnuplot development site on SourceForge.
> 	http://sourceforge.net/projects/gnuplot
> 
> Some platform-specific installation tips are given in the INSTALL
> file of the source package; the short version for linux/unix-like
> systems is to unpack the tarball and then
> <PRE>
> build it:
>       cd gnuplot-6.0.rc2 ; ./configure ; make
> test it:
>       make check
> install it:
>       make install
> </PRE>
> 
> Pay careful attention to the output of the ./configure script.
> It may indicate that some output modes have been omitted because the
> necessary support libraries were not found.  In general you need to have
> previously installed the "*-devel-*" versions of these libraries.

**Comment by cdkharris** [comment]
64855ca builds on myriad

**Comment by cdkharris** [comment]
https://github.com/UCL-RITS/rcps-modulefiles/commit/7789064399185deb0a47cedcba4b070648dd3558 adds the modulefile.

**Comment by heatherkellyucl** [comment]
Done on all four clusters.
