### ISSUE TITLE
Install request: Tensorflow

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#57]
IN01877354

https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#download-and-setup
- [x] Cuda Toolkit 7.5 (already have)
- [x] cuDNN v4
- [x] Bazel

**Comment by ikirker** [comment]
General warning: I tried this a while ago (when it was first open-sourced, I think) and I remember bazel being very problematic to get built from source. I don't remember exactly how, though.

Using the binary distribution of bazel instead was much less of a problem and worked to build TensorFlow.

**Comment by heatherkellyucl** [comment]
cuDNN from NVIDIA:
> The content you requested requires membership in the Accelerated Computing Developer Program. Please login if you are already a member, or join today.

Am checking whether we are already members.

**Comment by heatherkellyucl** [comment]
We can't install cuDNN centrally as it is part of NVIDIA's Accelerated Computing Developer Program and that gives access to individuals:

>"Do I have to sign a Non-Disclosure Agreement (NDA) to be in the Registered Developer Program?"
"No.  The Registered Developer Program does not require an NDA.  You are, however, expected to not share files or information within the program with others."

https://developer.nvidia.com/registered-developer-agreement

> Any items we post can be removed anytime and any software will have its own license and we may not be able to respond to all your inquiries or requests. For other stuff, you get a non-exclusive right to use it subject to certain restrictions (for example, no modifying it or giving it to someone else – for a full list, read below). The rights you get are what we explicitly say they are – no implied licenses or interpretational assumptions. 

Will ask if a version without cuDNN is any use - otherwise, we will only be able to give installation instructions.

**Comment by heatherkellyucl** [comment]
Have signed up and downloaded a copy myself so I can write an install script for those users who have downloaded their own copies.

**Comment by heatherkellyucl** [comment]
> TensorFlow GPU support requires having a GPU card with NVidia Compute Capability >= 3.0

The M2070 cards in the type V nodes are Compute Capability 2.0, so this states it will only work on the K40c in the type P node.

**Comment by heatherkellyucl** [comment]
- [ ] Run the test at https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#test-the-tensorflow-installation on the P node

**Comment by heatherkellyucl** [comment]
I successfuly got a gpu on the P node today and ran the test.

First tested the basic eigenvalues CUDA example to make sure that worked:

```
[cceahke@node-p00a-001 ~]$ cd Scratch/cuda/NVIDIA_CUDA-7.5_Samples/6_Advanced/eigenvalues/
[cceahke@node-p00a-001 eigenvalues]$ ./eigenvalues 
Starting eigenvalues
GPU Device 0: "Tesla K40c" with compute capability 3.5

Matrix size: 2048 x 2048
Precision: 0.000010
Iterations to be timed: 100
Result filename: 'eigenvalues.dat'
Gerschgorin interval: -2.894310 / 2.923303
Average time step 1: 6.745590 ms
Average time step 2, one intervals: 8.141781 ms
Average time step 2, mult intervals: 16.948547 ms
Average time TOTAL: 31.863350 ms
Test Succeeded!
```

Then Tensorflow binary:
```
[cceahke@node-p00a-001 cuda]$ export LD_LIBRARY_PATH=/home/cceahke/cudnn-7.0/cuda/lib64:$LD_LIBRARY_PATH
[cceahke@node-p00a-001 cuda]$ python
Python 2.7.9 (default, Sep 10 2015, 11:09:45) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:82:00.0
Total memory: 11.25GiB
Free memory: 11.15GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:806] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:82:00.0)
>>> print(sess.run(hello))
Hello, TensorFlow!
>>> a = tf.constant(10)
>>> b = tf.constant(32)
>>> print(sess.run(a + b))
42
>>> exit()
```

Working.

I also just had to give a user instructions on how to install it, so here is that, which can be tidied up for a how to page.

> To install Python packages, load either python2/recommended or python3/recommended, change to the compilers/gnu/4.9.2 compiler module for installation and you can then do a pip user install: https://wiki.rc.ucl.ac.uk/wiki/Compiling#Python

> Tensorflow definitely needs to be installed by the person using it, and I seem to recall Theano should be too.

> Tensorflow was quite straightforward and you just need to follow the instructions on its page:
You need to sign up as an individual for the NVIDIA Accelerated Computing Developer Program and download CuDNN: https://developer.nvidia.com/rdp/cudnn-download
Untar CuDNN and it creates a directory called cuda wherever you expanded it. It is a binary so that is all you need to do.

> Then the Tensorflow instructions:
Pick the one for the version of Python you want to use

>```
# Ubuntu/Linux 64-bit, GPU enabled, Python 2.7 
# Requires CUDA toolkit 7.5 and CuDNN v4. For other versions, see "Install from sources" below.
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp27-none-linux_x86_64.whl
# Ubuntu/Linux 64-bit, GPU enabled, Python 3.4 
# Requires CUDA toolkit 7.5 and CuDNN v4. For other versions, see "Install from sources" below.
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.9.0-cp34-cp34m-linux_x86_64.whl
```

> `pip install --user --upgrade $TF_BINARY_URL`

> Then to actually run, you will need to include these in your runscript (load the version of python you installed it for):
```
module unload compilers mpi
module load compilers/gnu/4.9.2
module load python2/recommended
module load cuda/7.5.18/gnu-4.9.2
```

> This should be set to where you installed CuDNN
`export LD_LIBRARY_PATH=/home/cceahke/cuda/lib64:$LD_LIBRARY_PATH`

> You can then run tensorflow. I got interactive access with qrsh to the GPU node and ran the example at https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html#run-tensorflow-from-the-command-line. On Legion Tensorflow will only work on the newest GPU node we have (type P), so you may want to run on Emerald instead, or you can put `#$ -ac allow=P` in your jobscript.

> For interactive access:
`qrsh -l gpu=1,mem=1G,h_rt=0:30:0 -ac allow=P -now no`
Wait until your job is scheduled on the node - your prompt will change to show you've logged in to node-p00a-001
Load the modules and export the path above
Run python or python3 interactively and run the example test.

**Comment by heatherkellyucl** [comment]
**Tensorflow 1.0:**

Binaries require CUDA 8.0 to be installed centrally. After we have done that, do this:

* If you already had CuDNN installed for an earlier Tensorflow, you shouldn't need to change anything about that. 

* If not, install CuDNN by downloading from https://developer.nvidia.com/rdp/cudnn-download, copying to Legion and untarring somewhere into your space, where it will create a cuda directory. It is a binary, so that is its install location.

* Add the CuDNN location to your `LD_LIBRARY_PATH`. This can be put in your .bashrc to be automatically run in every new session, or added to your jobscript each time. Make sure this path is correct for your install location:
`export LD_LIBRARY_PATH=/home/username/cuda/lib64:$LD_LIBRARY_PATH`

* Install Tensorflow using a pip user install:

```
# load the correct modules (pick either python2 or python3)
module unload compilers mpi
module load compilers/gnu/4.9.2
module load python3/recommended
module load cuda/8

pip install --user --upgrade tensorflow-gpu  # for Python 2.7 and GPU
pip3 install --user --upgrade tensorflow-gpu # for Python 3.n and GPU
```

If those pip commands don't work, use one of these links. `TF_PYTHON_URL` can be found from https://www.tensorflow.org/install/install_linux#the_url_of_the_tensorflow_python_package - pick the GPU link for the relevant python version. Eg for `python3/recommended`:

```
export TF_PYTHON_URL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.1-cp35-cp35m-linux_x86_64.whl
pip3 install --user --upgrade TF_PYTHON_URL  # Python 3.N
```

Tensorflow can still only run on the single P node on Legion at present (requires NVIDIA Compute Capability 3.0). 
Add this to your jobscript to specify that node:
`#$ -ac allow=P`

**Comment by owainkenwayucl** [comment]
Note: Compute nodes such as those of class P cannot write to home so you need to install to Scratch, either implicitly by linking .python2local/.python3local to directories on Scratch or explicitly with options to pip.

**Comment by owainkenwayucl** [comment]
At the moment, Tensorflow is not compatible with CuDNN 6.0 so you *must* download 5.1 instead.

At some point, Tensorflow will be updated and this advice will be wrong.  Welcome to GPUs.

**Comment by heatherkellyucl** [comment]
This issue is relevant again as CuDNN can be installed centrally now, see #112

**Comment by heatherkellyucl** [comment]
For pip installs when on the GPU node: you can do 
`export PYTHONUSERBASE=/home/username/Scratch/python3` 
and then `pip install --user` will install into there.

**Comment by owainkenwayucl** [comment]
OK, I'm going to have a look at doing a central install.

**Comment by owainkenwayucl** [comment]
I've emailed UCL ISD purchasing to chase up the CuDNN license.

**Comment by owainkenwayucl** [comment]
OK, ISD Purchasing have told me to register and install the software.

**Comment by owainkenwayucl** [comment]
OK, that's cuDNN installed:

```none
Legion [login06] ~ ☻ ➤ module avail cudnn

------------------- /shared/ucl/apps/modulefiles/development -------------------
cudnn/5.1/cuda-7.5   cudnn/6.0/cuda-7.5   cudnn/7.0.4/cuda-8.0
cudnn/5.1/cuda-8.0   cudnn/6.0/cuda-8.0
```

**Comment by owainkenwayucl** [comment]
Right.  Tensorflow.

It probably makes sense to install the CPU version on all resources, and the GPU version on Legion.t

If we are doing the CPU version we can either install the default one from `pip3` or we can do a build from source with MKL. (https://software.intel.com/en-us/articles/build-and-install-tensorflow-on-intel-architecture)

The latter may or may not work but I'll try that first.  If it becomes intractable I'll switch to the `pip3` one.

Either way, we are going for Python 3 and not bothering with Python 2.

**Comment by owainkenwayucl** [comment]
Right, I've installed bazel (a prerequisite for building Tensorflow from source).

**Comment by owainkenwayucl** [comment]
So I'm now at this point:

```none
/dev/shm/tensorflow/tmp.wmx4hVJm50/tensorflow
Fri 24 Nov 18:09:55 GMT 2017 : === Output wheel file is in: /dev/shm/tensorflow/tmp.wmx4hVJm50/tf_pip
/shared/ucl/apps/python/bundles/1507713910-3/venv/lib/python3.6/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Processing ./tf_pip/tensorflow-1.4.0-cp36-cp36m-linux_x86_64.whl
Collecting enum34>=1.1.6 (from tensorflow==1.4.0)
  Downloading enum34-1.1.6.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 2.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/shared/ucl/apps/python/bundles/1507713910-3/venv/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/shared/ucl/apps/python/bundles/1507713910-3/venv/lib/python3.6/distutils/__init__.py", line 4, in <module>
        import imp
      File "/shared/ucl/apps/python/bundles/1507713910-3/venv/lib/python3.6/imp.py", line 27, in <module>
        import tokenize
      File "/shared/ucl/apps/python/bundles/1507713910-3/venv/lib/python3.6/tokenize.py", line 33, in <module>
        import re
      File "/shared/ucl/apps/python/bundles/1507713910-3/venv/lib/python3.6/re.py", line 142, in <module>
        class RegexFlag(enum.IntFlag):
    AttributeError: module 'enum' has no attribute 'IntFlag'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_l4h8sy1/enum34/
[ccspapp@node-y00a-034 build_scripts]$ 
```

**Comment by owainkenwayucl** [comment]
So this issue is that it's trying to install a compatibility library which allows Python 3.4 to use enum, but we have Python 3.6 which has its own.

I know need to work out how to tell it not to do that.

**Comment by owainkenwayucl** [comment]
That seems to work but it ignores the option to install in a particular directory.

**Comment by owainkenwayucl** [comment]
Right. So on Monday I got it to install into the right directory, but it wouldn't load into Python because it didn't have the "google" module.  Which is right - I told it to build without it.  Rebuilding with the Google cloud support recreates the curl problem I fixed earlier for no reason.

**Comment by owainkenwayucl** [comment]
Nope.  Still complaining about a missing 'google' package :/

**Comment by owainkenwayucl** [comment]
So you have to delete `enum34` after installing tensorflow on python 3.6 otherwise it breaks everything.

**Comment by owainkenwayucl** [comment]
```python
Python 3.6.3 (default, Oct 10 2017, 15:11:55)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
/shared/ucl/apps/python/3.6.3/gnu-4.9.2/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
>>> hello = tf.constant('Hello, TensorFlow!')
>>> sess = tf.Session()
2017-12-13 11:51:25.613043: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
>>> print(sess.run(hello))
b'Hello, TensorFlow!'
>>> 
```

Success of a sort.

**Comment by owainkenwayucl** [comment]
```none
Legion [login06] tensorflow ☹ ➤ cat ~/Scratch/test-gpu.sh.e4266367
2017-12-13 12:35:46.403007: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2017-12-13 12:35:49.346287: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: Tesla K40c major: 3 minor: 5 memoryClockRate(GHz): 0.745
pciBusID: 0000:82:00.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2017-12-13 12:35:49.347529: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:82:00.0, compute capability: 3.5)
/shared/ucl/apps/python/3.6.3/gnu-4.9.2/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Legion [login06] tensorflow ☻ ➤ cat ~/Scratch/test-gpu.sh.o4266367
b'Hello, TensorFlow!'
```

👍

**Comment by owainkenwayucl** [comment]
![tf-mkl](https://user-images.githubusercontent.com/4256093/34112448-7e505e1a-e404-11e7-82e0-9025f5fbc201.png)

So that's working and I can close this issue.
