### ISSUE TITLE
Install request: Armadillo, Arpack, SuperLU

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#63]
IN01901352

Armadillo C++ Linear Algebra Library and the Arpack and SuperLU libraries.

http://arma.sourceforge.net/
http://www.caam.rice.edu/software/ARPACK/
http://crd-legacy.lbl.gov/~xiaoye/SuperLU/

**Comment by ikirker** [comment]
SuperLU also depends on METIS or ParMETIS.

SuperLU has serial, multi-threaded, and distributed versions.

SuperLU's installs depend on copying and altering a `make.inc` file. :(

ARPACK has serial and parallel versions.

ARPACK's installs also depend on copying and altering an `ARmake.inc` file.

Looks like Armadillo (optionally) depends on ARPACK, SuperLU, and HDF5.

Armadillo appears to have a CMake option that detects whether HDF5 is build with parallel features, but I don't think it does anything with that information: it may be a modular HDF5-detector.

Armadillo does not support out-of-tree builds. (Despite using CMake.)

**Comment by ikirker** [comment]
Correction: only SuperLU_DIST uses ParMETIS I think: the serial SuperLU doesn't use METIS or ParMETIS as far as I can tell.

And thanks to the xSDK initiative, SuperLU and (?:Par)METIS have both their original build system *and* CMake, so I'm using CMake. ARPACK not so much.

**Comment by ikirker** [comment]
Added SuperLU and SuperLU_Dist build scripts to the repo.

**Comment by ikirker** [comment]
ARPACK appears to have been forked into ARPACK-NG since development on ARPACK stalled (almost 20 years ago?).

It looks like it's a drop-in replacement.

Will try instead because it supports CMake and has self-tests.

**Comment by ikirker** [comment]
Ah, but the CMake setup for the latest release (3.4.0) doesn't have an install target, so the parallel library comes with an rpath-ed in dependency on the serial library *in the directory you built it*. Might need to reinstall chrpath, or use git for the installation and cherrypick the commit that adds the install target...

**Comment by ikirker** [comment]
Ah, *or* I could use the autotools setup that's also included. I'm going to do that.

**Comment by ikirker** [comment]
Added ARPACK-NG build script to the repo.

**Comment by ikirker** [comment]
Added SuperLU (serial) build script.

**Comment by ikirker** [comment]
Installed and added modules for SuperLU, SuperLU_DIST, ARPACK-NG.

**Comment by ikirker** [comment]
Looks like Armadillo (and anything else trying to build a shared library) can't use the SuperLU static library as it's built without `-fPIC`. The build system for SuperLU had the option of building a shared library, which sounds like the simplest option here. I'll remove the existing SuperLU installation, alter the build script, and reinstall.

**Comment by ikirker** [comment]
Done, added build script for Armadillo, installed Armadillo and modules.

All done.

**Comment by heatherkellyucl** [comment]
Modules to load are

```
module load superlu/5.2.1/intel-2015-update2
module load arpack-ng/3.4.0/intel-2015-update2
module load armadillo/7.400.3/intel-2015-update2
```

Have informed user.
