### ISSUE TITLE
Install SOD

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#64]
In preparation for Aristotle.

http://www.seis.sc.edu/SOD/download.html

**Comment by heatherkellyucl** [comment]
Installed on Legion and Aristotle00 as `sod/3.2.7`. Need to run demo example and sync to rest of Aristotle.

**Comment by heatherkellyucl** [comment]
SOD's demo run worked on Aristotle00 - I now have a directory full of seismograms. (http://www.seis.sc.edu/SOD/documentation/demo.html)

**Comment by heatherkellyucl** [comment]
Aristotle02 and 03 are synced (has to be done by root).

**Comment by balston** [comment]
Aristotle is syncing correctly every night now.

Closing.
