### ISSUE TITLE
Install request: CGAL library

### ISSUE THREAD

**Issue by carlosmolinero** [UCL-RITS/rcps-buildscripts#68]
I would like to have available the **CGAL library** for geometry computation if it would be possible.

Thank you in advanced.

_________________________________________________________________________________

I already installed it into my user account, so I am pasting the code I used, in case that speeds up things:
(*I am no expert in installing things so there might be some errors there).

```
wget https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.9-beta1/CGAL-4.9-beta1.tar.xz

tar -xvf CGAL-4.9-beta1.tar.xz

module unload compilers mpi mkl
module load compilers/gnu/4.9.2
module load mpi/openmpi/1.10.1/gnu-4.9.2
module load boost/1_54_0/gnu-4.9.2

cmake CMakeLists.txt

make

make install
```

_(*this last step does not work as a normal user, because of not having enough privileges)_

_________________________________________________________________________________

**Some info about the library:**

http://www.cgal.org

CGAL is a software project that provides easy access to efficient and reliable geometric algorithms in the form of a C++ library. CGAL is used in various areas needing geometric computation, such as geographic information systems, computer aided design, molecular biology, medical imaging, computer graphics, and robotics.

The library offers data structures and algorithms like triangulations, Voronoi diagrams, Boolean operations on polygons and polyhedra, point set processing, arrangements of curves, surface and volume mesh generation, geometry processing, alpha shapes, convex hull algorithms, shape analysis, AABB and KD trees...

Learn more about CGAL by browsing through the Package Overview.

**Comment by owainkenwayucl** [comment]
We'll add it to the list of the things to install.

In the mean time, you should be able to get it to install in your home directory by telling cmake to install it in your home directory by adding -DCMAKE_INSTALL_PREFIX=/some/path/you/can/write/to to your cmake command.

e.g.

```
cmake -DCMAKE_INSTALL_PREFIX=$HOME/cgal CMakeLists.txt
```

**Comment by heatherkellyucl** [comment]
(Reference ticket was IN01284640 - Carlos successfully installed his own copy)

**Comment by heatherkellyucl** [comment]
CGAL with Qt5 support is installed as `cgal/4.9/gnu-4.9.2` on Grace.

Modules necessary:

```
module unload compilers
module load compilers/gnu/4.9.2
module load python/2.7.9
module load boost/1_54_0/gnu-4.9.2
module load bison/3.0.4/gnu-4.9.2
module load gperf/3.0.4/gnu-4.9.2
module load qt/5.4.2/gnu-4.9.2
module load cgal/4.9/gnu-4.9.2
```

To do:
- [ ] install on Legion after outage.

**Comment by heatherkellyucl** [comment]
Installed on Legion too.

**Comment by carlosmolinero** [comment]
Thank you very much.
