### ISSUE TITLE
Install request: STAR-CCM+ 11.04.010

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#69]
IN01981923

Requests update to 11.04.010.
Arash has the installer.

**Comment by heatherkellyucl** [comment]
Have copied installer into `/shared/ucl/apps/STAR-CCM+/installers`

**Comment by balston** [comment]
I've run the installer and installed _11.04.010_ on Grace. I'm now going to run some tests to make sure it works!

**Comment by balston** [comment]
Unfortunately neither @heatherkellyucl or myself have any examples on Grace so will need to wait until Legion is back.

**Comment by balston** [comment]
We've been able to run a test job over the weekend for 15 hours and it appeared to be working OK on 32 cores. Version 11.04.010 of STAR-CCM+ is now available on Grace. Use:
```
module unload mpi
module load mpi/openmpi/1.8.4/intel-2015-update2
module load star-ccm+/11.04.010-R8
```
module commands to access this version.

**Comment by balston** [comment]
STAR-CCM+ Version 11.04.010 has now been installed on legion as well.

All done so closing issue.
