### ISSUE TITLE
Install request: AFNI

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#7]
Request for the AFNI software suite to be installed on Legion, available at afni.nimh.nih.gov.

Ticket IN00770976.

(Website currently not loading).

**Comment by heatherkellyucl** [comment]
Website still down.

**Comment by heatherkellyucl** [comment]
... but they do have a github at https://github.com/afniHQ/AFNI

**Comment by owainkenwayucl** [comment]
OK - I'll take a look at this.

**Comment by owainkenwayucl** [comment]
AFNI is now installed.
