### ISSUE TITLE
Install request: Intel compiler suite 2017

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#72]
IN02022747

Request as 2017 fixes some MKL bugs.

**Comment by balston** [comment]
Downloaded _parallel_studio_xe_2017_update1.tgz_ from https://registrationcenter.intel.com/en/products/download/2990/ using my UCL site login.

**Comment by balston** [comment]
I'm testing if this version will work with the UCL license manager.

**Comment by balston** [comment]
The tests appear to work so I'm proceeding to do a full install using this installer on Legion.

**Comment by balston** [comment]
Installation is complete and simple FORTRAN and C compilations are working and licensing correctly.

**Comment by balston** [comment]
Modules for the compilers and MPI are now installed. To use Intel Parallel Studio 2017 use the following module commands:
```
module unload compilers mpi
module load compilers/intel/2017/update1
module load mpi/intel/2017/update1/intel
```

**Comment by balston** [comment]
I've also installed the GNU Compilers version of the 2017 MPI module.

**Comment by balston** [comment]
Installation completed on:
- [ ] Legion;
- [ ] Grace.

**Comment by balston** [comment]
Wiki pages updated.

**Comment by balston** [comment]
Also tested and working on Aristotle. All done closing.
