### ISSUE TITLE
Install request: build additional tools bundled with CESM

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#82]
CESM has some additional tools under its `model` directory which are not built. I had a request for mksurfdata, part of the Community Land Surface Model (CLM4).

I have built mksurfdata for CLM4.5 on Legion and Grace and added it to the build script. There is also CLM 4.0 bundled with its own version. It would probably make sense to also build other bits in there by default.

The CLM tools all build like this:
```
cd /shared/ucl/apps/cesm/cesm1_2_2/models/lnd/clm/tools/clm4_5/mksurfdata_map/src
export INC_NETCDF=/shared/ucl/apps/cesm/support/netcdf/include
export LIB_NETCDF=/shared/ucl/apps/cesm/support/netcdf/lib
gmake
```
Some can be built with OpenMP support, with `gmake SMP=TRUE`

**Comment by owainkenwayucl** [comment]
This is now done, scripted, applied on all services.
