### ISSUE TITLE
Install request: Tesseract

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#83]
IN02295733

Tesseract
(https://github.com/tesseract-ocr/tesseract/wiki/Compiling)

User tried themselves in the past but got stuck with the Leptonica dependency.

**Comment by owainkenwayucl** [comment]
OK, I'm taking a pass at this.

**Comment by owainkenwayucl** [comment]
- [ ] - Leptonica
 - [ ] - Tesseract

**Comment by owainkenwayucl** [comment]
Right.  Leptonica build sorted out.  Done on Grace, now building on Legion/Thomas.

Will now start on Tesseract.

**Comment by owainkenwayucl** [comment]
Tesseract now installed, version 3.05.01, with the full set of language data for 3.0x in `$TESSDATA_PREFIX`, in module tesseract/3.05.01.

**Comment by owainkenwayucl** [comment]
Emailed user to test.
