### ISSUE TITLE
Fix python requirements for postgres+postgis (gdal)

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-RITS/rcps-buildscripts#88]
The update to python2/recommended has meant that `postgres+postgis/9.5.3+2.2.2/gnu-4.9.2` requires `python/2.7.9`(and so does `gmt/5.1.2`), but `gdal/2.0.0` requires `python2/recommended` so you can't load postgis without switching python modules twice.

- [x] find out if gdal actually requires the whole bundle or just any python2.7
- [x] fix the module requirements so they can actually all be loaded

We might need to put them all as `prereq python` and note that they don't work with python3. 

(Really, all our python modules need to be named like python/2/7/9 to solve this, then you can require python/2/7).

**Comment by heatherkellyucl** [comment]
http://trac.osgeo.org/gdal/wiki/GdalOgrInPython

> Dependencies
> * Python 2.X (and 3.X since GDAL 1.7.0). Python 2 versions known to work range from 2.3 to 2.7.
> * libgdal (1.5.0 or greater) and header files (gdal-devel)
> * numpy (1.0.0 or greater) and header files (numpy-devel) (**not explicitly required, but many examples and utilities will not work without it**).

Nooooooo.

**Comment by heatherkellyucl** [comment]
But it isn't obvious that we're actually building any python bindings. We aren't specifying either `--with-python` or `--without-python`, and the gdal build script only requires python/2.7.9

**Comment by heatherkellyucl** [comment]
We definitely don't have any python bindings with `gdal/2.0.0` so numpy isn't an issue.

**Comment by heatherkellyucl** [comment]
I've updated both gdal modules so they only require python and not python2/recommended for now, since neither of them build the bindings.

**Comment by ikirker** [comment]
If no one's using this (since as I understand it, Will Usher left and the project using it sort of died), I'd suggest just removing it, to avoid people trying to run their own Postgresql instances on normal nodes.
