### ISSUE TITLE
Install request: CPLEX solver for MatLab (IN02356883)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#90]
We've had a request for the CPLEX solver either from IBM or Tomlab.

**Comment by owainkenwayucl** [comment]
Note: the Tomlab version appears to have a cost associated, as does the IBM one.

There is however a "community edition" version of the IBM one which appears to be free.

**Comment by balston** [comment]
I've been able to register and download the IBM community edition. It is restricted to 1000 variables and 1000 constraints.

**Comment by balston** [comment]
The free (community) version is too small so we are investigating the academic version. Unfortunately the license portal for this version is currently unavailable.

**Comment by balston** [comment]
The portal is now available again. Here is the relevant part of the academic license:

> License
> 
> IBM grants you a nonexclusive, nontransferable license to use Eligible Resources solely for instruction and learning, as well as noncommercial research at the Institution. This use includes the design, development and testing of applications, hardware or virtual environments created by you. Eligible Resources cannot be used in production environments. Only Registered Educators may make copies, including backup copies, to support the level of use authorized, provided that the copyright notices and any other legends of ownership are reproduced on each copy or partial copy of the Eligible Resources. Registered Educators may use Eligible Resources and distribute them only to Registered Students enrolled in specific courses/programs requiring access.
> 
> Eligible Resources may not be 1) used, copied, modified, or distributed except as provided in this Agreement; 2) reverse assembled, reverse compiled, or otherwise translated, except as specifically permitted by law without the possibility of contractual waiver; 3) sublicensed, rented, or leased; 4) have Internet "links" to or from the offering for third parties to access. No Eligible Resource may be used for commercial or administrative purposes. In addition, Eligible Resources may not be used for noncredit courses which do not lead to nationally recognized qualifications or levels of academic achievement unless indicated to the contrary by IBM on the hub catalog at ibm.biz/ibmonhub2. IBM shall have no responsibility for any costs required for certification examinations and training for any Registered Educator and Registered Students.

**Comment by balston** [comment]
Downloading CPLEX Studio is not possible as the portal requires us to register with course codes and content. I'm emailing IBM to find out if a central install is possible.

**Comment by balston** [comment]
We've not been able to contact the relevant parties at IBM about the central install issue.

Suggest users install in their home directory on legion.  This should be fairly straightforward and when prompted enter an instllation directory like:

/home/ucbcxxx/ibm/CPLEX_Studio_V12.7

for example. You would then need to add the following directories to Matlab:

addpath ('/home/ucbcxxx/ibm/CPLEX_Studio_V12.7/cplex/matlab/x86-64_linux');
addpath ('/home/ucbcxxx/ibm/CPLEX_Studio_V12.7/cplex/examples/src/matlab');

replacing ucbcxxx with your userid.
