### ISSUE TITLE
Install VASP 5.4.4 (IN02360084)

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#91]
A user has requested that we install the latest version of VASP on Grace and Legion.

**Comment by utf** [comment]
Any luck with this? I'm having trouble compiling it myself.

With:

```bash
module load mpi/intel/2015/update3/intel
module load compilers/intel/2015/update2
```

I get the following seg fault:

`rhfatm.f90: catastrophic error: **Internal compiler error: segmentation violation signal raised** Please report this error along with the circumstances in which it occurred in a Software Problem Report.  Note: File and line given may not be explicit cause of this error.`

**Comment by ikirker** [comment]
It works for me with the 2017 Intel compiler + MPI collection, though something seems to have changed with the website that breaks my downloader script. :(

**Comment by ikirker** [comment]
Installed on Grace, will install on Legion tomorrow.

**Comment by utf** [comment]
Brilliant, thanks!
