### ISSUE TITLE
Install UMN Gaussrate+Polyrate+MSTor (IN:02384751)

### ISSUE THREAD

**Issue by ikirker** [UCL-RITS/rcps-buildscripts#93]
Obtained UCL site license via ISD IT Purchasing.

(Download credentials on RC section of central Wiki.)

Manual for Polyrate is license-walled (included in bundle stored).

Manual for Gaussrate: <https://comp.chem.umn.edu/gaussrate/gaussrate_Manual_v2017.2017.04.09.pdf>

Manual for MSTor: <https://comp.chem.umn.edu/mstor/mstor_Manual_v2013.2014.03.26.pdf>

Looks like Gaussrate is a modification for Polyrate which requires recompilation and a separate stored version?

No proper build system, just Perl scripts. 😞

**Comment by ikirker** [comment]
Hm. I'm not actually sure this is possible. It looks like it might depend on having write access to its own directories at run-time.

**Comment by ikirker** [comment]
NB: the Gaussrate test runs take at least several hours. Submit as a job.

**Comment by heatherkellyucl** [comment]
MSTor was requested as the priority.

**Comment by ikirker** [comment]
Have installed MSTor.

**Comment by ikirker** [comment]
My reading of the Polyrate manual is that it's not possible to install it usefully as a centrally installed program, because you have to edit the Makefile and build new binaries with it when you want to add new forcefields, which is the whole point of Polyrate and Gaussrate.

**Comment by ikirker** [comment]
(Because of this, I'm closing this, which I apparently didn't think to do at the time. I have informed the user of the situation.)
