### ISSUE TITLE
Install request: bcl2fastq (IN02394596)

### ISSUE THREAD

**Issue by balston** [UCL-RITS/rcps-buildscripts#94]
Cristina Venturini (c.venturini@ucl.ac.uk) has asked for installation of:

bcl2fastq https://support.illumina.com/sequencing/sequencing_software/bcl2fastq-conversion-software/downloads.html 

on Legion.

**Comment by balston** [comment]
bcl2fastq has also been requested by Tina Baker (tina.baker@ucl.ac.uk) (IN02395658).

**Comment by owainkenwayucl** [comment]
OK, I'll give this a whirl.

**Comment by owainkenwayucl** [comment]
Note: Both users are requesting bcl2fastq**2**, guessing by the version numbers they are requesting, so I'll install that rather than bcl2fastq.

**Comment by owainkenwayucl** [comment]
Built and installed.

**Comment by owainkenwayucl** [comment]
(I've emailed the two users asking them to test)

**Comment by owainkenwayucl** [comment]
I've not had a response from either user so closing for now.
