### ISSUE TITLE
Fix PGI2016.5 script

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL-RITS/rcps-buildscripts#99]
By default, when you install PGI 2016.5, it creates a file `bin/localrc.<hostname>` in the install folder.  This is (not really) host specific, and not being there results in errors like this:

```
$ make -f Makefile.pgi 
pgfortran -O2 -o pi pi.f90
pgfortran-Error-Please run makelocalrc to complete your installation
make: *** [pi] Error 1
```

This is trivially fixed by sym-linking appropriately, so on Grace/Thomas:

```
-rw-r--r-- 1 ccspapp ccsp 2.7K May 16 16:32 localrc.login01
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:31 localrc.login02 -> localrc.login01
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:31 localrc.login03 -> localrc.login01
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:31 localrc.login04 -> localrc.login01
```

And on Legion:

```
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:32 localrc.login05 -> localrc.login09
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:32 localrc.login06 -> localrc.login09
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:32 localrc.login07 -> localrc.login09
lrwxrwxrwx 1 ccspapp ccsp   15 May 24 13:32 localrc.login08 -> localrc.login09
-rw-r--r-- 1 ccspapp ccsp 2.4K Jun 30  2016 localrc.login09
```

This needs to be automated in the build script and obviously depends on the host the install is done from.

It also means that as things stand, you can't used PGI 2016.5 to build things in a build script (as you need a sym-link for compute host it runs on.

Interestingly, 2017.3 doesn't seem to have this problem...

**Comment by owainkenwayucl** [comment]
(I've added in sym-links for `aristotle0[1-4]` as well).

**Comment by ikirker** [comment]
2015.7 doesn't seem to have this problem, either.

**Comment by owainkenwayucl** [comment]
I had a look and I think this was me messing up when I did the install rather than a bug so I'm closing.
